\set ON_ERROR_STOP on
begin;
do $$
declare admin_id uuid:=gen_random_uuid();ordinary_id uuid:=gen_random_uuid();p1 uuid:=gen_random_uuid();p2 uuid:=gen_random_uuid();missing_player uuid:=gen_random_uuid();candidates jsonb;candidate_one jsonb;candidate_two jsonb;result jsonb;case_id uuid;r record;
begin
 insert into auth.users(id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)values(admin_id,'authenticated','authenticated','f4-guards-admin@example.invalid','',now(),'{}','{}',now(),now()),(ordinary_id,'authenticated','authenticated','f4-guards-member@example.invalid','',now(),'{}','{}',now(),now());
 insert into public.e10_platform_admins(user_id,created_by)values(admin_id,admin_id);insert into public.e10_players(id,name)values(p1,'Guard Same Name'),(p2,'Guard Same Name');
 candidate_one:=jsonb_build_object('player_id',p1,'confidence_status','known','confidence',0.8,'evidence','{}'::jsonb);candidate_two:=jsonb_build_object('player_id',p2,'confidence_status','unknown','confidence',null,'evidence','{}'::jsonb);candidates:=jsonb_build_array(candidate_one,candidate_two);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ordinary_id,'role','authenticated')::text,true);execute'set local role authenticated';
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','ordinary','Guard Same Name','manual','Guard test',null,'{}',candidates,'Denied','{}','guard-ordinary');raise exception'ordinary proposal allowed';exception when insufficient_privilege then if sqlerrm<>'platform_identity_review_denied'then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','duplicate','Guard Same Name','manual','Guard test',null,'{}',jsonb_build_array(candidate_one,candidate_one),'Invalid','{}','guard-duplicate');raise exception'duplicate candidates allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_candidate_invalid'then raise;end if;end;
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','missing','Guard Same Name','manual','Guard test',null,'{}',jsonb_build_array(candidate_one,jsonb_build_object('player_id',missing_player,'confidence_status','unknown','confidence',null,'evidence','{}'::jsonb)),'Invalid','{}','guard-missing');raise exception'nonexistent candidate allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_candidate_invalid'then raise;end if;end;
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','range','Guard Same Name','manual','Guard test',null,'{}',jsonb_build_array(candidate_one,jsonb_build_object('player_id',p2,'confidence_status','known','confidence',1.1,'evidence','{}'::jsonb)),'Invalid','{}','guard-range');raise exception'out-of-range confidence allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_candidate_invalid'then raise;end if;end;
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','nonnumeric','Guard Same Name','manual','Guard test',null,'{}',jsonb_build_array(candidate_one,jsonb_build_object('player_id',p2,'confidence_status','known','confidence','high','evidence','{}'::jsonb)),'Invalid','{}','guard-nonnumeric');raise exception'nonnumeric confidence allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_candidate_invalid'then raise;end if;end;
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','unknown-value','Guard Same Name','manual','Guard test',null,'{}',jsonb_build_array(candidate_one,jsonb_build_object('player_id',p2,'confidence_status','unknown','confidence',0,'evidence','{}'::jsonb)),'Invalid','{}','guard-unknown-value');raise exception'unknown confidence value allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_candidate_invalid'then raise;end if;end;
 begin perform public.e10_platform_propose_player_identity_review('model:guards','no-version','Guard Same Name','model','matcher',null,'{}',candidates,'Invalid','{}','guard-no-version');raise exception'model without version allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_proposal_invalid'then raise;end if;end;
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','oversize','Guard Same Name','manual','Guard test',null,jsonb_build_object('x',repeat('x',65536)),candidates,'Invalid','{}','guard-oversize');raise exception'oversized evidence allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_proposal_invalid'then raise;end if;end;
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','too-many','Guard Same Name','manual','Guard test',null,'{}',(select jsonb_agg(candidate_one)from generate_series(1,21)),'Invalid','{}','guard-too-many');raise exception'oversized candidate array allowed';exception when invalid_parameter_value then if sqlerrm<>'player_identity_review_proposal_invalid'then raise;end if;end;
 execute'reset role';if exists(select 1 from public.e10_catalog_identity_review_cases where source_namespace in('manual:guards','model:guards'))then raise exception'invalid proposal residue';end if;execute'set local role authenticated';
 result:=public.e10_platform_propose_player_identity_review('manual:guards','valid','Guard Same Name','manual','Guard test',null,'{}',candidates,'Review','{}','guard-valid');case_id:=(result->>'case_id')::uuid;
 begin perform public.e10_platform_propose_player_identity_review('manual:guards','valid','Guard Same Name','manual','Guard test',null,'{}',candidates,'Review','{}','guard-new-idem');raise exception'duplicate source with new key allowed';exception when unique_violation then if sqlerrm<>'player_identity_review_source_exists'then raise;end if;end;
 result:=public.e10_platform_reject_player_identity_review(case_id,1,'Reject','{}','guard-reject');
 begin perform public.e10_platform_reject_player_identity_review(case_id,1,'Changed reject','{}','guard-reject');raise exception'changed reject replay allowed';exception when invalid_parameter_value then if sqlerrm<>'idempotency_key_mismatch'then raise;end if;end;
 execute'reset role';
 for r in select * from(values('e10_catalog_identity_review_cases','source_key'),('e10_catalog_identity_review_candidates','player_id'),('e10_catalog_identity_review_decisions','revision'))v(table_name,column_name)loop
  begin execute format('update public.%I set %I=%I',r.table_name,r.column_name,r.column_name);raise exception'% update allowed',r.table_name;exception when object_not_in_prerequisite_state then if sqlerrm<>r.table_name||'_is_append_only'then raise;end if;end;
  begin execute format('delete from public.%I',r.table_name);raise exception'% delete allowed',r.table_name;exception when object_not_in_prerequisite_state then if sqlerrm<>r.table_name||'_is_append_only'then raise;end if;end;
 end loop;
end $$;
rollback;
select'TA-F4 identity ambiguity guards PASS'result;
