const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const ids={admin:randomUUID(),p1:randomUUID(),p2:randomUUID()};
async function actor(){const c=new Client({connectionString:db});await c.connect();await c.query("select set_config('request.jwt.claims',jsonb_build_object('sub',$1::text,'role','authenticated')::text,false)",[ids.admin]);await c.query('set role authenticated');return c}
async function main(){const setup=new Client({connectionString:db}),locker=new Client({connectionString:db});await Promise.all([setup.connect(),locker.connect()]);let a,b,c;let ok=false;
 try{
  await setup.query('set session_replication_role=replica');await setup.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[ids.admin,`f4-${ids.admin}@x.invalid`]);await setup.query('insert into public.e10_platform_admins(user_id,created_by)values($1,$1)',[ids.admin]);await setup.query("insert into public.e10_players(id,name)values($1,'Concurrent Same Name'),($2,'Concurrent Same Name')",[ids.p1,ids.p2]);
  [a,b,c]=await Promise.all([actor(),actor(),actor()]);const candidates=[{player_id:ids.p1,confidence_status:'known',confidence:0.7,evidence:{}},{player_id:ids.p2,confidence_status:'unknown',confidence:null,evidence:{}}];
  const propose=async(client,key,idem)=>(await client.query("select public.e10_platform_propose_player_identity_review($1,$2,'Concurrent Same Name','manual','Concurrency test',null,'{}',$3,'Race','{}',$4)j",['manual:concurrency',key,JSON.stringify(candidates),idem])).rows[0].j;
  const first=await propose(a,'race-case','f4-race-propose'),second=await propose(a,'revocation-case','f4-revoke-propose');const case1=first.case_id,case2=second.case_id;
  const reject=(client,caseId,key)=>client.query("select public.e10_platform_reject_player_identity_review($1,1,'Concurrent rejection','{}',$2)j",[caseId,key]).then(r=>({ok:true,j:r.rows[0].j}),e=>({ok:false,e}));
  const raced=await Promise.all([reject(a,case1,'f4-race-a'),reject(b,case1,'f4-race-b')]);if(raced.filter(x=>x.ok).length!==1||raced.filter(x=>!x.ok).length!==1||raced.find(x=>!x.ok).e.code!=='40001'||raced.find(x=>!x.ok).e.message!=='player_identity_review_revision_conflict')throw Error('reject race did not yield one winner '+JSON.stringify(raced.map(x=>x.ok?x.j:{code:x.e.code,message:x.e.message})));
  await locker.query('begin');await locker.query('select 1 from public.e10_catalog_identity_review_cases where id=$1 for update',[case2]);const pid=Number((await c.query('select pg_backend_pid()pid')).rows[0].pid);const pending=reject(c,case2,'f4-post-lock-revoke');let blocked=false;for(let i=0;i<60;i++){const state=(await setup.query('select wait_event_type from pg_stat_activity where pid=$1',[pid])).rows[0];if(state&&state.wait_event_type==='Lock'){blocked=true;break}await new Promise(r=>setTimeout(r,50))}if(!blocked)throw Error('post-lock rejection wait not established');await setup.query('delete from public.e10_platform_admins where user_id=$1',[ids.admin]);await locker.query('commit');const denied=await pending;if(denied.ok||denied.e.code!=='42501'||denied.e.message!=='platform_identity_review_denied')throw Error('post-lock platform authority was not rechecked');if((await setup.query('select count(*)n from public.e10_catalog_identity_review_decisions where case_id=$1',[case2])).rows[0].n!=='1')throw Error('denied rejection left residue');ok=true;
 }finally{await locker.query('rollback').catch(()=>{});for(const q of[a,b,c].filter(Boolean))await q.query('reset role').catch(()=>{});await setup.query('set session_replication_role=replica');await setup.query('delete from public.e10_catalog_identity_review_decisions where case_id in(select id from public.e10_catalog_identity_review_cases where source_namespace=$1)',['manual:concurrency']);await setup.query('delete from public.e10_catalog_identity_review_candidates where case_id in(select id from public.e10_catalog_identity_review_cases where source_namespace=$1)',['manual:concurrency']);await setup.query('delete from public.e10_catalog_identity_review_cases where source_namespace=$1',['manual:concurrency']);await setup.query('delete from public.e10_platform_admins where user_id=$1',[ids.admin]);await setup.query('delete from public.e10_players where id in($1,$2)',[ids.p1,ids.p2]);await setup.query('set session_replication_role=origin');await setup.query('delete from auth.users where id=$1',[ids.admin]);await Promise.all([setup.end(),locker.end(),...[a,b,c].filter(Boolean).map(q=>q.end())])}
 if(ok)console.log('TA-F4 identity ambiguity concurrency: PASS (one reject winner; post-lock revocation denied; zero denied residue)')
}
main().catch(e=>{console.error(e.stack||e);process.exit(1)});
