const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';const ids={admin:randomUUID(),p1:randomUUID(),p2:randomUUID()};
async function actor(){const c=new Client({connectionString:db});await c.connect();await c.query("select set_config('request.jwt.claims',jsonb_build_object('sub',$1::text,'role','authenticated')::text,false)",[ids.admin]);await c.query('set role authenticated');return c}
async function waitLock(setup,pid,label){for(let i=0;i<80;i++){const s=(await setup.query('select wait_event_type from pg_stat_activity where pid=$1',[pid])).rows[0];if(s&&s.wait_event_type==='Lock')return;await new Promise(r=>setTimeout(r,50))}throw Error(label+' lock wait not established')}
async function main(){const setup=new Client({connectionString:db}),locker=new Client({connectionString:db});await Promise.all([setup.connect(),locker.connect()]);let a,b,c;let ok=false;
 try{
  await setup.query('set session_replication_role=replica');await setup.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[ids.admin,`f4-${ids.admin}@x.invalid`]);await setup.query('insert into public.e10_platform_admins(user_id,created_by)values($1,$1)',[ids.admin]);await setup.query("insert into public.e10_players(id,name)values($1,'Concurrent Same Name'),($2,'Concurrent Same Name')",[ids.p1,ids.p2]);[a,b,c]=await Promise.all([actor(),actor(),actor()]);
  const candidates=[{player_id:ids.p1,confidence_status:'known',confidence:0.7,evidence:{}},{player_id:ids.p2,confidence_status:'unknown',confidence:null,evidence:{}}];const propose=(client,key,idem)=>client.query("select public.e10_platform_propose_player_identity_review('manual:concurrency',$1,'Concurrent Same Name','manual','Concurrency test',null,'{}',$2,'Race','{}',$3)j",[key,JSON.stringify(candidates),idem]).then(r=>({ok:true,j:r.rows[0].j}),e=>({ok:false,e}));
  let pair=await Promise.all([propose(a,'same-idem','f4-same-idem'),propose(b,'same-idem','f4-same-idem')]);if(pair.some(x=>!x.ok)||new Set(pair.map(x=>x.j.case_id)).size!==1||pair.filter(x=>x.j.replay).length!==1||(await setup.query("select count(*)n from public.e10_catalog_identity_review_cases where source_namespace='manual:concurrency'and source_key='same-idem'")).rows[0].n!=='1')throw Error('same-idempotency proposal race failed');const case1=pair[0].j.case_id;
  pair=await Promise.all([propose(a,'same-source','f4-source-a'),propose(b,'same-source','f4-source-b')]);const sourceWinner=pair.find(x=>x.ok),sourceLoser=pair.find(x=>!x.ok);if(!sourceWinner||!sourceLoser||sourceLoser.e.code!=='23505'||sourceLoser.e.message!=='player_identity_review_source_exists'||(await setup.query("select count(*)n from public.e10_catalog_identity_review_cases where source_namespace='manual:concurrency'and source_key='same-source'")).rows[0].n!=='1')throw Error('competing-source proposal race failed');const case2=sourceWinner.j.case_id;
  await locker.query('begin');await locker.query("select pg_advisory_xact_lock(hashtextextended('player-identity-review-idempotency|f4-revoked-idem',0))");let pid=Number((await c.query('select pg_backend_pid()pid')).rows[0].pid);let pending=propose(c,'revoked-idem','f4-revoked-idem');await waitLock(setup,pid,'idempotency');await setup.query('delete from public.e10_platform_admins where user_id=$1',[ids.admin]);await locker.query('commit');let denied=await pending;if(denied.ok||denied.e.code!=='42501'||denied.e.message!=='platform_identity_review_denied')throw Error('idempotency-wait authority not rechecked');if((await setup.query("select count(*)n from public.e10_catalog_identity_review_cases where source_namespace='manual:concurrency'and source_key='revoked-idem'")).rows[0].n!=='0')throw Error('idempotency-wait denial residue');await setup.query('insert into public.e10_platform_admins(user_id,created_by)values($1,$1)',[ids.admin]);
  await locker.query('begin');await locker.query("select pg_advisory_xact_lock(hashtextextended('player-identity-review-source|manual:concurrency|player|revoked-source',0))");pid=Number((await c.query('select pg_backend_pid()pid')).rows[0].pid);pending=propose(c,'revoked-source','f4-revoked-source');await waitLock(setup,pid,'source');await setup.query('delete from public.e10_platform_admins where user_id=$1',[ids.admin]);await locker.query('commit');denied=await pending;if(denied.ok||denied.e.code!=='42501'||denied.e.message!=='platform_identity_review_denied')throw Error('source-wait authority not rechecked');if((await setup.query("select count(*)n from public.e10_catalog_identity_review_cases where source_namespace='manual:concurrency'and source_key='revoked-source'")).rows[0].n!=='0')throw Error('source-wait denial residue');await setup.query('insert into public.e10_platform_admins(user_id,created_by)values($1,$1)',[ids.admin]);
  const reject=(client,id,key)=>client.query("select public.e10_platform_reject_player_identity_review($1,1,'Concurrent rejection','{}',$2)j",[id,key]).then(r=>({ok:true,j:r.rows[0].j}),e=>({ok:false,e}));pair=await Promise.all([reject(a,case1,'f4-reject-a'),reject(b,case1,'f4-reject-b')]);if(pair.filter(x=>x.ok).length!==1||pair.filter(x=>!x.ok).length!==1||pair.find(x=>!x.ok).e.code!=='40001')throw Error('reject race did not yield one winner');
  await locker.query('begin');await locker.query('select 1 from public.e10_catalog_identity_review_cases where id=$1 for update',[case2]);pid=Number((await c.query('select pg_backend_pid()pid')).rows[0].pid);pending=reject(c,case2,'f4-post-lock-reject');await waitLock(setup,pid,'reject');await setup.query('delete from public.e10_platform_admins where user_id=$1',[ids.admin]);await locker.query('commit');denied=await pending;if(denied.ok||denied.e.code!=='42501'||denied.e.message!=='platform_identity_review_denied')throw Error('reject post-lock authority not rechecked');if((await setup.query('select count(*)n from public.e10_catalog_identity_review_decisions where case_id=$1',[case2])).rows[0].n!=='1')throw Error('denied reject residue');ok=true;
 }finally{await locker.query('rollback').catch(()=>{});for(const q of[a,b,c].filter(Boolean))await q.query('reset role').catch(()=>{});await setup.query('set session_replication_role=replica');await setup.query("delete from public.e10_catalog_identity_review_decisions where case_id in(select id from public.e10_catalog_identity_review_cases where source_namespace='manual:concurrency')");await setup.query("delete from public.e10_catalog_identity_review_candidates where case_id in(select id from public.e10_catalog_identity_review_cases where source_namespace='manual:concurrency')");await setup.query("delete from public.e10_catalog_identity_review_cases where source_namespace='manual:concurrency'");await setup.query('delete from public.e10_platform_admins where user_id=$1',[ids.admin]);await setup.query('delete from public.e10_players where id in($1,$2)',[ids.p1,ids.p2]);await setup.query('set session_replication_role=origin');await setup.query('delete from auth.users where id=$1',[ids.admin]);await Promise.all([setup.end(),locker.end(),...[a,b,c].filter(Boolean).map(q=>q.end())])}
 if(ok)console.log('TA-F4 identity ambiguity concurrency: PASS (proposal idempotency/source races; proposal/reject post-lock revocation; one reject winner; zero denied residue)')
}
main().catch(e=>{console.error(e.stack||e);process.exit(1)});
