\set ON_ERROR_STOP on
begin;
do $$declare o uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();r uuid:=gen_random_uuid();v uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();dk uuid:=gen_random_uuid();prior uuid;u jsonb;s text;i integer;begin
 insert into public.e10_organizations(id,slug,name)values(o,'x7dh-'||substr(o::text,1,8),'Helpers'),(o2,'x7dh-'||substr(o2::text,1,8),'Helpers Other');insert into public.e10_catalog_releases(id,release_name)values(r,'Helpers');insert into public.e10_catalog_variants(id,release_id)values(v,r);
 set local session_replication_role=replica;insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,occurred_at,currency,amount,quantity,source_kind,source_connection_id,raw_payload_snapshot)values(a,o,'completed_sale',v,'2026-01-01T00:00:00Z','USD',10,1,'manual',null,'{}'),(b,o,'completed_sale',v,'2026-01-01T00:00:00Z','USD',10,1,'csv','shop','{}');set local session_replication_role=origin;
 insert into public.e10_market_observation_coverage_decisions(organization_id,decision_key,observation_kind,source_kind,source_connection_id,currency,covered_from,covered_to,revision,action,coverage_status,reason,evidence,idempotency_key,request_fingerprint)values
 (o,gen_random_uuid(),'completed_sale','csv','shop','USD','2026-01-01T00:00:00Z','2026-02-01T00:00:00Z',1,'assert','complete','x','{}','helper-shop-complete','fp'),
 (o,gen_random_uuid(),'completed_sale','csv','shop','USD','2026-01-10T00:00:00Z','2026-01-11T00:00:00Z',1,'assert','partial','x','{}','helper-shop-partial','fp'),
 (o,gen_random_uuid(),'completed_sale','manual',null,'USD','2026-01-01T00:00:00Z','2026-02-01T00:00:00Z',1,'assert','complete','x','{}','helper-manual-complete','fp');
 insert into public.e10_market_observation_coverage_decisions(organization_id,decision_key,observation_kind,source_kind,source_connection_id,currency,covered_from,covered_to,revision,action,coverage_status,reason,evidence,idempotency_key,request_fingerprint)values
 (o,gen_random_uuid(),'asking_price','native','adjacent','USD','2026-01-01','2026-01-15',1,'assert','complete','x','{}','helper-adjacent-1','fp'),
 (o,gen_random_uuid(),'asking_price','native','adjacent','USD','2026-01-15','2026-02-01',1,'assert','complete','x','{}','helper-adjacent-2','fp'),
 (o,gen_random_uuid(),'estimated_value','api','gap-a','USD','2026-01-01','2026-01-15',1,'assert','complete','x','{}','helper-gap-a','fp'),
 (o,gen_random_uuid(),'estimated_value','api','gap-b','USD','2026-01-15','2026-02-01',1,'assert','complete','x','{}','helper-gap-b','fp'),
 (o2,gen_random_uuid(),'completed_sale','csv','other-org','CAD','2026-01-01','2026-02-01',1,'assert','complete','x','{}','helper-other-org','fp');
 u:=e10.market_source_universe(o,'explicit','completed_sale','csv','USD','["shop","shop"]');if u<>'["shop"]'::jsonb then raise exception'explicit universe not canonical %',u;end if;
 if e10.market_source_universe(o,'explicit','completed_sale','manual','USD','[null]')<>'[null]'::jsonb then raise exception'null connection universe lost';end if;
 if e10.market_source_universe(o,'all_reviewed_connections','completed_sale','csv','USD',null)<>'["shop"]'::jsonb then raise exception'all-reviewed universe wrong';end if;
 s:=e10.market_coverage_status(o,'completed_sale','csv','USD','2026-01-01T00:00:00Z','2026-02-01T00:00:00Z','["shop"]');if s<>'partial'then raise exception'partial subtraction wrong %',s;end if;
 s:=e10.market_coverage_status(o,'completed_sale','manual','USD','2026-01-01T00:00:00Z','2026-02-01T00:00:00Z','[null]');if s<>'complete'then raise exception'complete null-source coverage wrong %',s;end if;
 s:=e10.market_coverage_status(o,'completed_sale','csv','USD','2026-01-01T00:00:00Z','2026-02-01T00:00:00Z','["unknown"]');if s<>'unknown'then raise exception'absent source implied coverage %',s;end if;
 s:=e10.market_coverage_status(o,'asking_price','native','USD','2026-01-01','2026-02-01','["adjacent"]');if s<>'complete'then raise exception'adjacent complete intervals did not union %',s;end if;
 s:=e10.market_coverage_status(o,'estimated_value','api','USD','2026-01-01','2026-02-01','["gap-a","gap-b"]');if s='complete'then raise exception'separate source gaps filled each other';end if;
 if e10.market_source_universe(o,'all_reviewed_connections','completed_sale','csv','USD',null)@>'["other-org"]'::jsonb or e10.market_source_universe(o,'all_reviewed_connections','completed_sale','csv','CAD',null)<>'[]'::jsonb then raise exception'org/kind/currency isolation failed';end if;
 if e10.market_coverage_status(o,'completed_sale','csv','USD','2026-01-01','2026-02-01','[]')<>'unknown'then raise exception'empty universe implied coverage';end if;
 if not e10.market_provenance_matches(o,array[a,b],'csv','["shop"]')or not e10.market_provenance_matches(o,array[a,b],'manual','[null]')or e10.market_provenance_matches(o,array[a,b],'api','[null]')then raise exception'provenance source membership wrong';end if;
 begin perform e10.market_source_universe(o,'explicit','completed_sale','csv','USD','[]');raise exception'empty explicit universe accepted';exception when invalid_parameter_value then null;end;
 begin perform e10.market_source_universe(o,null,'completed_sale',null,'USD',null);raise exception'NULL source mode accepted';exception when invalid_parameter_value then null;end;
 begin perform e10.market_source_universe(o,'explicit','completed_sale',null,'USD','[null]');raise exception'NULL explicit source kind accepted';exception when invalid_parameter_value then null;end;
 begin perform e10.market_source_universe(null,'none','completed_sale',null,'USD',null);raise exception'NULL org accepted';exception when invalid_parameter_value then null;end;
 begin perform e10.market_coverage_status(o,'completed_sale','csv','USD','2026-01-01','2026-01-01','["shop"]');raise exception'empty coverage interval accepted';exception when invalid_parameter_value then null;end;
 begin perform e10.market_coverage_status(o,'completed_sale','csv','USD',null,'2026-01-02','["shop"]');raise exception'NULL coverage bound accepted';exception when invalid_parameter_value then null;end;
 begin perform e10.market_provenance_matches(o,array[a,b],null,'[null]');raise exception'provenance filter mismatch accepted';exception when invalid_parameter_value then null;end;
 select id into prior from public.e10_market_observation_coverage_decisions where organization_id=o and source_kind='manual'and source_connection_id is null and observation_kind='completed_sale';
 insert into public.e10_market_observation_coverage_decisions(organization_id,decision_key,observation_kind,source_kind,source_connection_id,currency,covered_from,covered_to,revision,action,coverage_status,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,(select decision_key from public.e10_market_observation_coverage_decisions where id=prior),'completed_sale','manual',null,'USD','2026-01-01','2026-02-01',2,'revoke',null,prior,'x','{}','helper-manual-revoke','fp');
 if e10.market_source_universe(o,'all_reviewed_connections','completed_sale','manual','USD',null)<>'[]'::jsonb then raise exception'revoked coverage still contributes';end if;
 for i in 1..51 loop insert into public.e10_market_observation_coverage_decisions(organization_id,decision_key,observation_kind,source_kind,source_connection_id,currency,covered_from,covered_to,revision,action,coverage_status,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),'asking_price','api','feed-'||i,'USD','2026-01-01T00:00:00Z','2026-02-01T00:00:00Z',1,'assert','complete','x','{}','helper-bound-'||i,'fp');end loop;
 begin perform e10.market_source_universe(o,'all_reviewed_connections','asking_price','api','USD',null);raise exception'oversized reviewed universe accepted';exception when program_limit_exceeded then null;end;
 if has_function_privilege('authenticated','e10.market_source_universe(uuid,text,text,text,text,jsonb)','execute')or has_function_privilege('authenticated','e10.market_provenance_matches(uuid,uuid[],text,jsonb)','execute')or has_function_privilege('authenticated','e10.market_coverage_status(uuid,text,text,text,timestamp with time zone,timestamp with time zone,jsonb)','execute')or has_function_privilege('anon','e10.market_source_universe(uuid,text,text,text,text,jsonb)','execute')or has_function_privilege('anon','e10.market_provenance_matches(uuid,uuid[],text,jsonb)','execute')or has_function_privilege('anon','e10.market_coverage_status(uuid,text,text,text,timestamp with time zone,timestamp with time zone,jsonb)','execute')then raise exception'helper ACL leak';end if;
end $$;
rollback;
select'TA-X7d.2 market query helpers PASS'as result;
