\set ON_ERROR_STOP on
begin;
do $$declare o uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();r uuid:=gen_random_uuid();v uuid:=gen_random_uuid();p uuid:=gen_random_uuid();p2 uuid:=gen_random_uuid();obs uuid:=gen_random_uuid();cg uuid:=gen_random_uuid();cp uuid:=gen_random_uuid();fg uuid:=gen_random_uuid();fp uuid:=gen_random_uuid();cpid uuid;fpid uuid;seasonkey uuid:=gen_random_uuid();seasonmask uuid;n integer;begin
 insert into public.e10_organizations(id,slug,name)values(o,'x7dce-'||substr(o::text,1,8),'Catalog Entity'),(o2,'x7dcef-'||substr(o2::text,1,8),'Catalog Entity Foreign');
 insert into public.e10_catalog_releases(id,manufacturer,brand_line,release_name,release_year,season,sport,language,region,edition)values(r,'Maker','Line','No Evidence',2024,'2023-24','basketball','en','US','hobby');insert into public.e10_players(id,name)values(p,'Player One'),(p2,'Player Two');insert into public.e10_catalog_variants(id,release_id,card_number,exact_parallel,language,edition,print_run_denominator)values(v,r,'10','Gold','fr','retail',50);insert into public.e10_catalog_variant_subjects(variant_id,player_id,position)values(v,p,1),(v,p2,2);
 if(select count(*)from e10.market_catalog_entities(o)x where x.catalog_variant_id=v)<>1 or exists(select 1 from public.e10_market_observations where catalog_variant_id=v)then raise exception'zero-observation catalog row missing or duplicated';end if;
 insert into public.e10_catalog_facet_term_keys(id,namespace)values(cg,'color_family'),(cp,'color_family'),(fg,'finish_family'),(fp,'finish_family');insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(cg,'color_family','Global Gold',1,'assert','x','{}','ce-cg','fp');insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(cp,'color_family','Private Blue',1,'assert','x','{}','ce-cp','fp')returning id into cpid;insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(fg,'finish_family','Global Chrome',1,'assert','x','{}','ce-fg','fp');insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(fp,'finish_family','Private Prizm',1,'assert','x','{}','ce-fp','fp')returning id into fpid;
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,term_key,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,'color_family',1,'assert',cg,'x','{}','ce-color','fp'),(gen_random_uuid(),v,'finish_family',1,'assert',fg,'x','{}','ce-finish','fp');insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,boolean_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,'rookie_designation',1,'assert',true,'x','{}','ce-rookie','fp');
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,subject_id,facet_key,revision,action,boolean_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,p,'rookie_designation',1,'assert',true,'x','{}','ce-rp1','fp'),(gen_random_uuid(),v,p2,'rookie_designation',1,'assert',false,'x','{}','ce-rp2','fp');insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,subject_id,facet_key,revision,action,integer_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,p,'rookie_season',1,'assert',2024,'x','{}','ce-rs1','fp'),(gen_random_uuid(),v,p2,'rookie_season',1,'assert',2023,'x','{}','ce-rs2','fp');
 insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,facet_key,revision,action,term_key,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),v,'color_family',1,'assert',cp,'x','{}','ce-private-color','fp'),(o,gen_random_uuid(),v,'finish_family',1,'assert',fp,'x','{}','ce-private-finish','fp');insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,subject_id,facet_key,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(o,seasonkey,v,p,'rookie_season',1,'mask','x','{}','ce-season-mask','fp')returning id into seasonmask;if not exists(select 1 from e10.market_catalog_entities(o)x where x.catalog_variant_id=v and x.rookie_season_by_subject->p::text->'value'='null'::jsonb and x.rookie_season_by_subject->p::text->>'status'='org_masked')then raise exception'rookie-season mask was not observable before clear';end if;insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,subject_id,facet_key,revision,action,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,seasonkey,v,p,'rookie_season',2,'clear',seasonmask,'x','{}','ce-season-clear','fp');
 if not exists(select 1 from e10.market_catalog_entities(o)x where x.catalog_variant_id=v and x.subject_ids=array[p,p2]::uuid[] and x.color_family_term_id=cp and x.finish_family_term_id=fp and x.rookie_designation_by_subject->p::text->>'value'='true'and x.rookie_designation_by_subject->p2::text->>'value'='false'and x.rookie_season_by_subject->p::text->>'value'='2024'and x.rookie_season_by_subject->p2::text->>'value'='2023')then raise exception'private precedence or dual-subject rookie mismatch';end if;
 if not exists(select 1 from e10.market_catalog_entities(o2)x where x.catalog_variant_id=v and x.color_family_term_id=cg and x.finish_family_term_id=fg)then raise exception'foreign global fallback mismatch';end if;
 set local session_replication_role=replica;insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,occurred_at,currency,amount,quantity,source_kind,raw_payload_snapshot)values(obs,o,'completed_sale',v,'2026-01-01','USD',10,1,'manual','{}');set local session_replication_role=origin;
 if not exists(select 1 from e10.market_catalog_entities(o)c join public.e10_market_eligible_canonical_observations e on e.organization_id=o and e.observation_id=obs and e.catalog_variant_id=c.catalog_variant_id where c.subject_ids=e.subject_ids and c.color_family_term_id is not distinct from e.color_family_term_id and c.color_family_status=e.color_family_status and c.finish_family_term_id is not distinct from e.finish_family_term_id and c.finish_family_status=e.finish_family_status and c.rookie_designation is not distinct from e.rookie_designation and c.rookie_designation_status=e.rookie_designation_status and c.rookie_designation_by_subject=e.rookie_designation_by_subject and c.rookie_season_by_subject=e.rookie_season_by_subject)then raise exception'X7d.1 direct parity mismatch';end if;
 insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,supersedes_term_id,reason,evidence,idempotency_key,request_fingerprint)values(cp,'color_family','Private Blue',2,'revoke',cpid,'x','{}','ce-cp-revoke','fp'),(fp,'finish_family','Private Prizm',2,'revoke',fpid,'x','{}','ce-fp-revoke','fp');
 if not exists(select 1 from e10.market_catalog_entities(o)c join public.e10_market_eligible_canonical_observations e on e.organization_id=o and e.observation_id=obs where c.catalog_variant_id=v and c.color_family_term_id is null and e.color_family_term_id is null and c.color_family_status='org_term_revoked'and e.color_family_status=c.color_family_status and c.finish_family_term_id is null and e.finish_family_term_id is null and c.finish_family_status='org_term_revoked'and e.finish_family_status=c.finish_family_status)then raise exception'revoked private term parity mismatch';end if;
 select count(*)into n from e10.market_catalog_entities(null);if n<>0 then raise exception'NULL org projection was not empty';end if;
 if has_function_privilege('anon','e10.market_catalog_entities(uuid)','execute')or has_function_privilege('authenticated','e10.market_catalog_entities(uuid)','execute')then raise exception'catalog projection ACL leak';end if;
end $$;
rollback;
select'TA-X7d.2 catalog entity projection PASS'as result;
