const {Client}=require("pg");const{randomUUID}=require("crypto");
const db=process.env.E10_DB_URL||"postgresql://postgres:postgres@127.0.0.1:54322/postgres";
async function rejected(p,code,msg){try{await p;return false}catch(e){return e.code===code&&(!msg||e.message===msg)}}
async function main(){const c=new Client({connectionString:db});await c.connect();
 const x={org:randomUUID(),user:randomUUID(),session:randomUUID(),policy:randomUUID(),coverage:randomUUID()};let ok=false;
 const streams=[];const segments=[];for(let i=0;i<8;i++){streams.push(randomUUID());segments.push(randomUUID())}
 const addEvent=async(stream,segment,seq,kind,at,corrects=null,id=randomUUID())=>{await c.query("insert into public.e10_session_presence_events(id,organization_id,stream_id,segment_id,event_sequence,event_kind,provider_occurred_at,server_received_at,provider_event_id,provider_key,corrects_event_id,evidence,request_fingerprint)values($1,$2,$3,$4,$5,$6,$7,$7,$8,'whatnot',$9,'{}',$10)",[id,x.org,stream,segment,seq,kind,at,`edge-${id}`,corrects,`fp-${id}`]);return id};
 try{
  await c.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.user,`${x.user}@x.invalid`]);
  await c.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7c edges')",[x.org,`x7ce-${x.org.slice(0,8)}`]);
  await c.query("insert into public.e10_break_sessions(id,organization_id,streamer_uid,name,status,visibility,created_at,ended_at)values($1,$2,$3,'Edges','ended','private','2026-01-01','2026-01-31')",[x.session,x.org,x.user]);
  await c.query("insert into public.e10_presence_collection_policies(organization_id,policy_version,source_class,provider_key,enabled,notice_version,heartbeat_expiry_seconds,min_event_interval_ms,max_events_per_minute,retention_interval,coverage_label,effective_from)values($1,1,'authorized_platform','whatnot',true,'n1',300,0,60,interval '30 days','fixture','2026-01-01')",[x.org]);
  await c.query("insert into public.e10_provider_presence_normalization_policy_decisions(id,organization_id,provider_key,revision,action,effective_from,effective_through,heartbeat_expiry,maximum_late_arrival,collection_policy_version,reason,evidence,idempotency_key,request_fingerprint)values($1,$2,'whatnot',1,'enable','2026-01-01','2027-01-01',interval '5 minutes',interval '1 day',1,'fixture','{}','policy','policy-fp')",[x.policy,x.org]);
  await c.query("insert into public.e10_presence_policy_state_history(organization_id,source_class,provider_key,policy_version,enabled,state_from)values($1,'authorized_platform','whatnot',1,true,'2026-01-01')",[x.org]);
  await c.query("insert into public.e10_attendance_coverage_assertions(id,organization_id,coverage_key,revision,action,source_class,provider_key,covered_from,covered_to,coverage_status,policy_version,review_basis,evidence,idempotency_key,request_fingerprint)values($1,$2,$1,1,'assert','authorized_platform','whatnot','2026-01-01','2026-02-01','complete',1,'fixture','{}','coverage','coverage-fp')",[x.coverage,x.org]);
  for(let i=0;i<streams.length;i++){await c.query("insert into public.e10_session_presence_streams(id,organization_id,session_id,source_class,provider_key,subject_key,connection_id,platform_attendee_key,identity_status,collection_policy_version,notice_version,coverage_label,retention_expires_at)values($1,$2,$3,'authorized_platform','whatnot',$4,$5,$4,'unresolved',1,'n1','fixture','2027-01-01')",[streams[i],x.org,x.session,`subject-${i}`,`connection-${i}`]);await c.query("insert into public.e10_session_presence_segments(id,organization_id,stream_id,segment_sequence,heartbeat_expiry_seconds,retention_expires_at,collection_policy_version,notice_version,coverage_label)values($1,$2,$3,1,300,$4,1,'n1','fixture')",[segments[i],x.org,streams[i],i===5?'2026-01-02 15:03Z':'2027-01-01'])}
  await addEvent(streams[0],segments[0],1,'join','2026-01-02 10:00Z');await addEvent(streams[0],segments[0],2,'heartbeat','2026-01-02 10:10Z');
  await addEvent(streams[1],segments[1],1,'join','2026-01-02 11:00Z');await addEvent(streams[1],segments[1],2,'join','2026-01-02 11:00Z');
  await addEvent(streams[2],segments[2],1,'join','2026-01-02 12:00Z');await addEvent(streams[2],segments[2],2,'leave','2026-01-02 12:00Z');
  const original=await addEvent(streams[3],segments[3],1,'join','2026-01-02 13:00Z');await addEvent(streams[3],segments[3],2,'join','2026-01-02 13:01Z',original);await addEvent(streams[3],segments[3],3,'leave','2026-01-02 13:02Z');
  const target=await addEvent(streams[4],segments[4],1,'join','2026-01-02 14:00Z');await addEvent(streams[4],segments[4],2,'leave','2026-01-02 14:02Z');await addEvent(streams[5],segments[5],1,'join','2026-01-02 14:01Z',target);
  await addEvent(streams[5],segments[5],2,'join','2026-01-02 15:00Z');await addEvent(streams[5],segments[5],3,'leave','2026-01-02 15:04Z');
  const cycleA=randomUUID(),cycleB=randomUUID();await c.query("set session_replication_role=replica");
  await c.query("insert into public.e10_session_presence_events(id,organization_id,stream_id,segment_id,event_sequence,event_kind,provider_occurred_at,server_received_at,provider_event_id,provider_key,corrects_event_id,evidence,request_fingerprint)values($1,$3,$4,$5,1,'join','2026-01-02 16:00Z','2026-01-02 16:00Z','cycle-a','whatnot',$2,'{}','cycle-a'),($2,$3,$4,$5,2,'leave','2026-01-02 16:01Z','2026-01-02 16:01Z','cycle-b','whatnot',$1,'{}','cycle-b')",[cycleA,cycleB,x.org,streams[6],segments[6]]);await c.query("set session_replication_role=origin");
  await c.query("insert into public.e10_session_presence_events(id,organization_id,stream_id,segment_id,event_sequence,event_kind,provider_occurred_at,server_received_at,provider_event_id,provider_key,evidence,request_fingerprint)select gen_random_uuid(),$1,$2,$3,1000+g,'heartbeat','2026-02-15'::timestamptz+g*interval '1 second','2026-02-15'::timestamptz+g*interval '1 second','excluded-'||g,'whatnot','{}','excluded-'||g from generate_series(1,101)g",[x.org,streams[7],segments[7]]);
  const sql="select public.e10_service_run_provider_presence_normalization($1,'whatnot',$2,'2026-01-01T00:00:00Z','2026-02-01T00:00:00Z','2026-03-01T00:00:00Z',100,'edge-run') result";
  const result=(await c.query(sql,[x.org,x.policy])).rows[0].result;if(result.interval_count!==4||result.quarantine_count!==9)throw Error(`edge counts ${JSON.stringify(result)}`);
  const intervals=(await c.query("select extract(epoch from ended_at-started_at)::int seconds,expiry_reason from public.e10_provider_presence_normalized_intervals where run_id=$1 order by started_at",[result.run_id])).rows;if(JSON.stringify(intervals)!==JSON.stringify([{seconds:300,expiry_reason:'join_expiry'},{seconds:60,expiry_reason:'provider_leave'},{seconds:120,expiry_reason:'provider_leave'},{seconds:180,expiry_reason:'retention_end'}]))throw Error(`edge intervals ${JSON.stringify(intervals)}`);
  const reasons=(await c.query("select reason,count(*)::int n from public.e10_provider_presence_quarantine_rows where run_id=$1 group by reason order by reason",[result.run_id])).rows;const expected=[{reason:'correction_cycle',n:2},{reason:'cross_stream_correction',n:1},{reason:'duplicate_semantic_event',n:2},{reason:'missing_join',n:1},{reason:'retention_expired',n:1},{reason:'same_time_conflict',n:2}];if(JSON.stringify(reasons)!==JSON.stringify(expected))throw Error(`edge quarantine ${JSON.stringify(reasons)}`);
  const correction=(await c.query("select cardinality(source_event_ids)n from public.e10_provider_presence_normalized_intervals where run_id=$1 and started_at='2026-01-02 13:01Z'",[result.run_id])).rows[0];if(!correction||correction.n!==3)throw Error("correction replacement lineage missing");
  const longStream=randomUUID(),longSegment=randomUUID();await c.query("insert into public.e10_session_presence_streams(id,organization_id,session_id,source_class,provider_key,subject_key,connection_id,platform_attendee_key,identity_status,collection_policy_version,notice_version,coverage_label,retention_expires_at)values($1,$2,$3,'authorized_platform','whatnot','long-cycle','long-cycle','long-cycle','unresolved',1,'n1','fixture','2027-01-01')",[longStream,x.org,x.session]);await c.query("insert into public.e10_session_presence_segments(id,organization_id,stream_id,segment_sequence,heartbeat_expiry_seconds,retention_expires_at,collection_policy_version,notice_version,coverage_label)values($1,$2,$3,1,300,'2027-01-01',1,'n1','fixture')",[longSegment,x.org,longStream]);
  const longIds=Array.from({length:34},()=>randomUUID());await c.query("set session_replication_role=replica");for(let i=0;i<longIds.length;i++)await c.query("insert into public.e10_session_presence_events(id,organization_id,stream_id,segment_id,event_sequence,event_kind,provider_occurred_at,server_received_at,provider_event_id,provider_key,corrects_event_id,evidence,request_fingerprint)values($1,$2,$3,$4,$5,'heartbeat',$6,$6,$7,'whatnot',$8,'{}',$7)",[longIds[i],x.org,longStream,longSegment,i+1,`2026-01-03 10:${String(i).padStart(2,'0')}:00Z`,`long-${i}`,longIds[(i+1)%longIds.length]]);await c.query("set session_replication_role=origin");
  if(!await rejected(c.query(sql.replace("'edge-run'","'long-cycle-run'"),[x.org,x.policy]),'54000','provider_normalization_lineage_bound_exceeded'))throw Error("long no-leaf correction component was silently lost");
  const revoke=randomUUID();await c.query("insert into public.e10_provider_presence_normalization_policy_decisions(id,organization_id,provider_key,revision,action,effective_from,effective_through,heartbeat_expiry,maximum_late_arrival,collection_policy_version,reason,evidence,supersedes_decision_id,idempotency_key,request_fingerprint)values($1,$2,'whatnot',2,'revoke','2026-01-15','2026-01-16',null,null,1,'mid-window revoke','{}',$3,'revoke','revoke-fp')",[revoke,x.org,x.policy]);
  if(!await rejected(c.query(sql.replace("'edge-run'","'edge-run-2'"),[x.org,x.policy]),'22023','provider_normalization_policy_unavailable'))throw Error("mid-window policy change silently accepted");ok=true;
 }finally{await c.query("reset role").catch(()=>{});await c.query("set session_replication_role=replica");for(const t of['e10_provider_presence_normalized_intervals','e10_provider_presence_quarantine_rows','e10_provider_presence_normalization_runs','e10_attendance_coverage_assertions','e10_session_presence_events','e10_session_presence_segments','e10_session_presence_streams','e10_provider_presence_normalization_policy_decisions','e10_presence_policy_state_history','e10_presence_collection_policies','e10_break_sessions','e10_reporting_dataset_revisions'])await c.query(`delete from public.${t} where organization_id=$1`,[x.org]);await c.query("delete from public.e10_organizations where id=$1",[x.org]);await c.query("set session_replication_role=origin");await c.query("delete from auth.users where id=$1",[x.user]);const n=Number((await c.query("select count(*)n from public.e10_organizations where id=$1",[x.org])).rows[0].n);await c.end();if(n)throw Error('cleanup failed')}
 if(ok)console.log('TA-X7c provider normalization edges: PASS')}
main().catch(e=>{console.error(e.stack);process.exit(1)});
