const {Client}=require('pg');
const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres',org='e1000000-0000-4000-8000-0000000000a6';
const q={run:randomUUID(),user:randomUUID(),role:randomUUID(),a:randomUUID(),b:randomUUID(),c:randomUUID(),d:randomUUID(),fo:randomUUID(),fu:randomUUID(),fr:randomUUID(),fc:randomUUID()};
const rpc='select public.e10_org_decide_customer_transaction_attribution($1,$2,$3,$4,$5,$6::jsonb,$7) r';
const res='select * from public.e10_org_resolve_customer_transactions($1,$2::uuid[])';
const merge='select public.e10_org_decide_customer_resolution($1,$2,$3,$4,$5,$6,$7,$8,$9::uuid[],$10,$11::jsonb,$12)';
const bounded=(p)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('X6f timeout')),8000))]);
async function main(){
 const s=new Client({connectionString:db}),a=new Client({connectionString:db}),b=new Client({connectionString:db});await Promise.all([s.connect(),a.connect(),b.connect()]);
 const drafts=[],txs=[];
 try{
  if(Number((await s.query("select count(*) n from public.e10_organization_role_permissions where capability='act.correct_customer_attribution'")).rows[0].n)!==0)throw Error('capability granted by default');
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now()),($3,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$4,now(),now())",[q.user,q.run+'@x.invalid',q.fu,q.fu+'@x.invalid']);
  await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values($1,$2,$3,'X6f',false)",[q.role,org,q.run]);
  await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.manage_customers',true),($1,$2,'act.merge_customers',true),($1,$2,'act.prepare_customer_transactions',true),($1,$2,'act.approve_customer_transactions',true),($1,$2,'act.post_customer_transactions',true),($1,$2,'act.correct_customer_attribution',true)",[org,q.role]);
  await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active')",[org,q.user,q.role]);
  await s.query("insert into public.e10_customers(id,organization_id,display_name) values($1,$5,'A'),($2,$5,'B'),($3,$5,'C'),($4,$5,'D')",[q.a,q.b,q.c,q.d,org]);
  await s.query("insert into public.e10_organizations(id,name,slug) values($1,'X6f foreign',$2)",[q.fo,'x6f-'+q.run]);
  await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values($1,$2,$3,'foreign',false)",[q.fr,q.fo,q.run]);
  await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.prepare_customer_transactions',true),($1,$2,'act.approve_customer_transactions',true),($1,$2,'act.post_customer_transactions',true)",[q.fo,q.fr]);
  await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active')",[q.fo,q.fu,q.fr]);
  await s.query("insert into public.e10_customers(id,organization_id,display_name) values($1,$2,'Foreign')",[q.fc,q.fo]);
  for(const c of [a,b]){await c.query('select set_config($1,$2,false)',['request.jwt.claims',JSON.stringify({sub:q.user,role:'authenticated'})]);await c.query('set role authenticated');}
  async function post(c,o,customer,suffix,two=false){const lines=[{purchase_kind:'retail',capture_source:'manual',source_line_id:q.run+'-'+suffix+'-1',quantity:1,merchandise_gross:30,merchandise_discount:0,shipping_amount:5,tax_amount:3}];if(two)lines.push({purchase_kind:'retail',capture_source:'manual',source_line_id:q.run+'-'+suffix+'-2',quantity:2,merchandise_gross:20,merchandise_discount:0,shipping_amount:0,tax_amount:2});const d=(await c.query("select public.e10_org_create_customer_transaction_draft($1,$2,'CAD',now(),'exact',$3,$4,$5) r",[o,customer,'X6f',JSON.stringify(lines),q.run+'-'+suffix+'-draft'])).rows[0].r.draft_id;drafts.push(d);await c.query('select public.e10_org_approve_customer_transaction_draft($1,$2,1,$3)',[o,d,q.run+'-'+suffix+'-approve']);const t=(await c.query('select public.e10_org_post_customer_transaction_draft($1,$2,1,$3) r',[o,d,q.run+'-'+suffix+'-post'])).rows[0].r.transaction_id;txs.push(t);return t;}
  const t1=await post(a,org,q.a,'one',true),t2=await post(a,org,q.a,'two');
  await b.query('reset role');await b.query('select set_config($1,$2,false)',['request.jwt.claims',JSON.stringify({sub:q.fu,role:'authenticated'})]);await b.query('set role authenticated');const ft=await post(b,q.fo,q.fc,'foreign');await b.query('reset role');await b.query('select set_config($1,$2,false)',['request.jwt.claims',JSON.stringify({sub:q.user,role:'authenticated'})]);await b.query('set role authenticated');
  const line=(await s.query('select id from public.e10_customer_transaction_lines where transaction_id=$1 order by line_no limit 1',[t1])).rows[0].id,adj=randomUUID(),ev=randomUUID();
  await s.query('begin');
  await s.query("insert into public.e10_customer_transaction_adjustments(id,organization_id,transaction_id,transaction_line_id,adjustment_kind,currency,merchandise_amount,occurred_at,occurred_at_precision,reason,source_reference,commercial_event_id,created_by,effect,source_kind,source_event_id,source_component_id,evidence,idempotency_key,request_fingerprint) values($1,$2,$3,$4,'refund','CAD',5,now(),'exact','reviewed',$5,$6,$7,'decrease','manual',$5,'merchandise','{}',$5,$5)",[adj,org,t1,line,q.run+'-refund',ev,q.user]);
  await s.query("insert into public.e10_commercial_events(id,organization_id,event_type,event_schema_version,subject_type,subject_id,occurred_at,occurred_at_precision,idempotency_key,source_kind,source_event_id,correlation_id,evidence_quality,payload,created_by,request_fingerprint,customer_transaction_id,customer_transaction_adjustment_id) values($1,$2,'refund',1,'customer_transaction',$3::text,now(),'exact',$5::text,'manual',$5::text,$3::text,'operator_asserted',jsonb_build_object('refund_id',$4::uuid,'currency','CAD','amount',5,'effect','decrease','external_source_event_id',$5::text,'external_source_component_id','merchandise'),$6,$5::text,$3::uuid,$4::uuid)",[ev,org,t1,adj,q.run+'-refund',q.user]);
  await s.query('commit');
  const hash=async()=>JSON.stringify((await s.query("select (select md5(row_to_json(t)::text) from public.e10_customer_transactions t where id=$1) t,(select md5(string_agg(row_to_json(l)::text,'' order by l.id)) from public.e10_customer_transaction_lines l where transaction_id=$1) l,(select md5(string_agg(row_to_json(a)::text,'' order by a.id)) from public.e10_customer_transaction_adjustments a where transaction_id=$1) a,(select md5(string_agg(row_to_json(e)::text,'' order by e.id)) from public.e10_commercial_events e where customer_transaction_id=$1) e,(select count(*)::int from public.e10_customer_transaction_lines where transaction_id=$1) lc,(select count(*)::int from public.e10_customer_transaction_adjustments where transaction_id=$1) ac",[t1])).rows[0]);const before=await hash();
  await a.query(merge,[org,q.a,q.b,0,0,0,'merge','operator_review',[],'duplicate','{}',q.run+'-merge']);
  let rows=(await a.query(res,[org,[t1,t2]])).rows;if(rows.some(r=>r.effective_customer_id!==q.b||r.attribution_decision_id!==null))throw Error('merge fallback failed');
  await a.query(merge,[org,q.a,null,0,null,1,'split','operator_review',[],'distinct','{}',q.run+'-split']);
  const first=(await a.query(rpc,[org,t1,0,q.b,'reviewed','{}',q.run+'-attr-b'])).rows[0].r;rows=(await a.query(res,[org,[t1,t2]])).rows;if(rows.find(r=>r.transaction_id===t1).effective_customer_id!==q.b||rows.find(r=>r.transaction_id===t2).effective_customer_id!==q.a)throw Error('selective resolution failed');
  const un=(await a.query(rpc,[org,t1,1,null,'anonymous','{}',q.run+'-unattr'])).rows[0].r;rows=(await a.query(res,[org,[t1]])).rows;if(rows[0].attribution_action!=='unattribute'||rows[0].effective_customer_id!==null||rows[0].original_customer_id!==q.a||rows[0].attribution_decision_id!==un.decision_id)throw Error('explicit unattribute failed');
  await a.query("select public.e10_org_update_customer($1,$2,0,'archived','archived',$3)",[org,q.b,q.run+'-archive']);
  const replay=(await a.query(rpc,[org,t1,0,q.b,'reviewed','{}',q.run+'-attr-b'])).rows[0].r;if(!replay.replay||replay.decision_id!==first.decision_id)throw Error('archived target retry failed');
  await a.query(rpc,[org,t1,2,q.c,'correct','{}',q.run+'-attr-c']);if(before!==await hash())throw Error('posted facts changed');
  const inherited=(await s.query("select r.effective_customer_id,(select count(*)::int from public.e10_customer_transaction_lines l where l.transaction_id=t.id) lines,(select sum(coalesce(l.merchandise_gross,0)-coalesce(l.merchandise_discount,0)+coalesce(l.shipping_amount,0)+coalesce(l.tax_amount,0)) from public.e10_customer_transaction_lines l where l.transaction_id=t.id) posted_total,(select count(*)::int from public.e10_customer_transaction_adjustments a where a.transaction_id=t.id) adjustments,(select sum(case a.effect when 'increase' then 1 else -1 end*coalesce(a.merchandise_amount,0)) from public.e10_customer_transaction_adjustments a where a.transaction_id=t.id) adjustment_total from public.e10_customer_transactions t cross join lateral e10.customer_transaction_effective_attribution(t.organization_id,t.id) r where t.id=$1",[t1])).rows[0];if(inherited.effective_customer_id!==q.c||inherited.lines!==2||Number(inherited.posted_total)!==60||inherited.adjustments!==1||Number(inherited.adjustment_total)!==-5)throw Error('refund/contribution grain failed '+JSON.stringify(inherited));
  let denied=false;try{await a.query(rpc,[org,t1,0,q.c,'stale','{}',q.run+'-stale']);}catch(e){denied=e.code==='40001';}if(!denied)throw Error('stale revision accepted');
  const race=await bounded(Promise.allSettled([a.query(rpc,[org,t2,0,q.c,'race','{}',q.run+'-race-c']),b.query(rpc,[org,t2,0,q.d,'race','{}',q.run+'-race-d'])]));if(race.filter(v=>v.status==='fulfilled').length!==1||race.filter(v=>v.status==='rejected'&&v.reason.code==='40001').length!==1)throw Error('CAS race failed');
  denied=false;try{await a.query(rpc,[org,ft,0,q.c,'foreign','{}',q.run+'-foreign']);}catch(e){denied=e.code==='42501';}if(!denied)throw Error('foreign transaction accepted');
  denied=false;try{await a.query(rpc,[org,t1,3,q.fc,'foreign customer','{}',q.run+'-fc']);}catch(e){denied=e.code==='42501';}if(!denied)throw Error('foreign customer accepted');
  denied=false;try{await a.query(rpc,[org,t1,3,q.b,'archived customer','{}',q.run+'-archived-target']);}catch(e){denied=e.code==='42501';}if(!denied)throw Error('archived target accepted');
  denied=false;try{await a.query(rpc,[org,t1,3,randomUUID(),'missing customer','{}',q.run+'-missing-target']);}catch(e){denied=e.code==='42501';}if(!denied)throw Error('missing target accepted');
  denied=false;try{await a.query(rpc,[org,t1,3,q.c,'collision','{}',q.run+'-archive']);}catch(e){denied=e.code==='22023'&&e.message==='idempotency_key_mismatch';}if(!denied)throw Error('cross-operation key accepted');
  denied=false;try{await a.query(res,[org,[t1,t1]]);}catch(e){denied=e.code==='22023';}if(!denied)throw Error('duplicate resolver input accepted');
  denied=false;try{await a.query(res,[org,[]]);}catch(e){denied=e.code==='22023';}if(!denied)throw Error('empty resolver input accepted');
  denied=false;try{await a.query(res,[org,Array.from({length:101},()=>randomUUID())]);}catch(e){denied=e.code==='22023';}if(!denied)throw Error('overlimit resolver input accepted');
  denied=false;try{await a.query(res,[q.fo,[ft]]);}catch(e){denied=e.code==='42501';}if(!denied)throw Error('foreign resolver allowed');
  denied=false;try{await a.query('select * from public.e10_customer_transaction_attribution_decisions');}catch(e){denied=e.code==='42501';}if(!denied)throw Error('direct read allowed');
  const hist=(await a.query('select * from public.e10_org_list_customer_transaction_attribution_history($1,$2,10,null)',[org,t1])).rows;if(hist.map(r=>r.revision).join(',')!=='3,2,1')throw Error('history failed');
  denied=false;try{await a.query('select * from public.e10_org_list_customer_transaction_attribution_history($1,$2,null,null)',[org,t1]);}catch(e){denied=e.code==='22023';}if(!denied)throw Error('null history bound accepted');
  denied=false;try{await a.query('select * from public.e10_org_list_customer_transaction_attribution_history($1,$2,101,null)',[org,t1]);}catch(e){denied=e.code==='22023';}if(!denied)throw Error('overlimit history accepted');
  denied=false;try{await a.query('select * from public.e10_org_list_customer_transaction_attribution_history($1,$2,10,null)',[q.fo,ft]);}catch(e){denied=e.code==='42501';}if(!denied)throw Error('foreign history allowed');
  // Hold the shared topology lock while making C nonterminal. The attribution must
  // wait, then re-read topology and reject C rather than committing stale validity.
  await a.query('begin');await a.query(merge,[org,q.c,q.d,0,0,0,'merge','operator_review',[],'topology overlap','{}',q.run+'-topology-merge']);
  const bpid=Number((await b.query('select pg_backend_pid() pid')).rows[0].pid);
  const blocked=bounded(b.query(rpc,[org,t1,3,q.c,'stale topology','{}',q.run+'-topology-attr']));
  let waited=false;for(let i=0;i<40&&!waited;i++){waited=Number((await s.query("select count(*) n from pg_locks where pid=$1 and locktype='advisory' and not granted",[bpid])).rows[0].n)>0;if(!waited)await new Promise(r=>setTimeout(r,50));}
  if(!waited){await a.query('rollback');throw Error('topology overlap did not establish exact backend wait');}
  await a.query('commit');const topology=await Promise.allSettled([blocked]);if(topology[0].status!=='rejected'||topology[0].reason.code!=='22023'||topology[0].reason.message!=='transaction_customer_attribution_requires_effective_customer')throw Error('topology recheck failed');
  await s.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.correct_customer_attribution'",[org,q.role]);denied=false;try{await a.query(rpc,[org,t1,3,q.d,'missing','{}',q.run+'-missing']);}catch(e){denied=e.code==='42501';}if(!denied)throw Error('missing cap allowed');
  const acl=(await s.query("select has_function_privilege('anon','public.e10_org_decide_customer_transaction_attribution(uuid,uuid,integer,uuid,text,jsonb,text)','execute') anon,has_function_privilege('authenticated','public.e10_org_decide_customer_transaction_attribution(uuid,uuid,integer,uuid,text,jsonb,text)','execute') auth,(select relrowsecurity from pg_class where oid='public.e10_customer_transaction_attribution_decisions'::regclass) rls")).rows[0];if(acl.anon||!acl.auth||!acl.rls)throw Error('ACL/RLS failed');
  console.log('TA-X6f posted customer attribution: PASS');
 }finally{
  const cleanupErrors=[];const clean=async(sql,args=[])=>{try{await s.query(sql,args);}catch(e){cleanupErrors.push(e.message);}};
  await Promise.all([a.query('reset role').catch(e=>cleanupErrors.push(e.message)),b.query('reset role').catch(e=>cleanupErrors.push(e.message))]);await clean('set session_replication_role=replica');
  await clean("delete from public.e10_customer_transaction_source_claims where source_line_id like $1",[q.run+'%']);await clean("delete from public.e10_commercial_events where source_event_id like $1 or idempotency_key like $1 or idempotency_key like $2",[q.run+'%','transaction-post:'+q.run+'%']);
  for(const table of ['e10_customer_transaction_attribution_decisions','e10_customer_transaction_adjustments','e10_customer_transaction_lines'])await clean('delete from public.'+table+' where transaction_id=any($1::uuid[])',[txs]);
  await clean('delete from public.e10_customer_transactions where id=any($1::uuid[])',[txs]);
  for(const table of ['e10_customer_transaction_draft_decisions','e10_customer_transaction_draft_lines','e10_customer_transaction_draft_revisions'])await clean('delete from public.'+table+' where draft_id=any($1::uuid[])',[drafts]);await clean('delete from public.e10_customer_transaction_drafts where id=any($1::uuid[])',[drafts]);
  for(const table of ['e10_customer_commercial_receipts','e10_customer_resolution_decisions','e10_customer_mutation_receipts'])await clean('delete from public.'+table+' where idempotency_key like $1',[q.run+'%']);
  await clean('delete from public.e10_customers where id=any($1::uuid[])',[[q.a,q.b,q.c,q.d,q.fc]]);await clean('delete from public.e10_organization_status_transitions where organization_id=$1',[q.fo]);await clean('set session_replication_role=origin');
  await clean('delete from public.e10_organization_memberships where user_id=any($1::uuid[])',[[q.user,q.fu]]);await clean('delete from public.e10_organization_role_permissions where role_id=any($1::uuid[])',[[q.role,q.fr]]);await clean('delete from public.e10_organization_roles where id=any($1::uuid[])',[[q.role,q.fr]]);await clean('delete from public.e10_organizations where id=$1',[q.fo]);await clean('delete from auth.users where id=any($1::uuid[])',[[q.user,q.fu]]);
  const residue=Number((await s.query("select (select count(*) from public.e10_customer_transaction_attribution_decisions where idempotency_key like $1)+(select count(*) from public.e10_customer_mutation_receipts where idempotency_key like $1)+(select count(*) from public.e10_customer_resolution_decisions where idempotency_key like $1)+(select count(*) from public.e10_customer_transactions where id=any($2::uuid[]))+(select count(*) from public.e10_customer_transaction_lines where transaction_id=any($2::uuid[]))+(select count(*) from public.e10_customer_transaction_adjustments where transaction_id=any($2::uuid[]))+(select count(*) from public.e10_commercial_events where source_event_id like $1 or idempotency_key like $1)+(select count(*) from public.e10_customer_transaction_source_claims where source_line_id like $1)+(select count(*) from public.e10_customer_transaction_drafts where id=any($3::uuid[]))+(select count(*) from public.e10_customers where id=any($4::uuid[]))+(select count(*) from auth.users where id=any($5::uuid[]))+(select count(*) from public.e10_organization_roles where id=any($6::uuid[]))+(select count(*) from public.e10_organization_memberships where user_id=any($5::uuid[]))+(select count(*) from public.e10_organizations where id=$7) n",[q.run+'%',txs,drafts,[q.a,q.b,q.c,q.d,q.fc],[q.user,q.fu],[q.role,q.fr],q.fo])).rows[0].n);await Promise.all([s.end(),a.end(),b.end()]);if(cleanupErrors.length||residue)throw Error('cleanup failed '+JSON.stringify({cleanupErrors,residue}));
 }
}
main().catch(e=>{console.error(e.stack);process.exit(1);});
