\set ON_ERROR_STOP on
begin;
do $$
declare o uuid:=gen_random_uuid();creator uuid:=gen_random_uuid();approver uuid:=gen_random_uuid();reader uuid:=gen_random_uuid();admin_user uuid:=gen_random_uuid();creator_role uuid:=gen_random_uuid();approver_role uuid:=gen_random_uuid();reader_role uuid:=gen_random_uuid();admin_role uuid:=gen_random_uuid();loc uuid:=gen_random_uuid();supplier uuid:=gen_random_uuid();product uuid:=gen_random_uuid();config uuid:=gen_random_uuid();version uuid:=gen_random_uuid();d uuid;j jsonb;vals jsonb;
begin
 insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)select id,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','x8bp-'||id||'@x.invalid',now(),now()from unnest(array[creator,approver,reader,admin_user])id;
 insert into public.e10_organizations(id,slug,name)values(o,'x8bp-'||substr(o::text,1,8),'X8b permissions');
 insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values(creator_role,o,'x8b-creator','Creator',false),(approver_role,o,'x8b-approver','Approver',false),(reader_role,o,'x8b-reader','Reader',false),(admin_role,o,'admin','Admin',true);
 insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values(o,creator,creator_role,'active'),(o,approver,approver_role,'active'),(o,reader,reader_role,'active'),(o,admin_user,admin_role,'active');
 insert into public.e10_organization_role_permissions values(o,creator_role,'act.purchasing_prepare',true),(o,approver_role,'act.purchasing_approve',true),(o,reader_role,'act.purchasing_approve',true),(o,reader_role,'financial.actual_cost.read',true),(o,reader_role,'act.manage_customers',true),(o,admin_role,'act.purchasing_prepare',true);
 insert into public.e10_locations(id,organization_id,code,name,status)values(loc,o,'X8BP','X8b','active');insert into public.e10_location_role_permissions(organization_id,location_id,role_id,can_receive)values(o,loc,creator_role,true),(o,loc,admin_role,true);
 insert into public.e10_suppliers(id,organization_id,code,name,status)values(supplier,o,'X8BP','X8b','active');insert into public.e10_product_masters(id,organization_id,name)values(product,o,'X8b');insert into public.e10_product_configurations(id,organization_id,product_master_id,name)values(config,o,product,'X8b');insert into public.e10_product_configuration_versions(id,organization_id,configuration_id,version_no,state,packaging_kind,base_unit,base_units_per_package)values(version,o,config,1,'active','unit','unit',1);
 vals:=jsonb_build_object('supplier_id',supplier,'destination_location_id',loc,'order_number','X8BP','currency','CAD','expected_at',null,'lines',jsonb_build_array(jsonb_build_object('line_no',1,'configuration_version_id',version,'ordered_quantity',1,'estimated_unit_cost',44)));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',creator,'role','authenticated')::text,true);set local role authenticated;j:=public.e10_org_create_action_draft(o,'purchase_order.create',vals,'{"supplier_id":{"source":"operator","text":"private vendor note"}}','[{"kind":"operator_note","text":"private source note","payload":{"email":"private@example.invalid"}}]','create');d:=(j->>'draft_id')::uuid;
 j:=public.e10_org_preview_action_draft(o,d,1);if j#>'{values,lines,0}'?'estimated_unit_cost'or j#>'{field_provenance,supplier_id}'?'text'then raise exception'prepare-only creator saw sensitive preview %',j;end if;
 begin perform public.e10_org_approve_action_draft(o,d,1,'creator-approve');raise exception'prepare-only creator approved';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',approver,'role','authenticated')::text,true);j:=public.e10_org_preview_action_draft(o,d,1);if j#>'{values,lines,0}'?'estimated_unit_cost'or j#>'{source_references,0}'?'text'then raise exception'approval-only reviewer saw sensitive preview %',j;end if;perform public.e10_org_approve_action_draft(o,d,1,'approve');
 begin perform public.e10_org_amend_action_draft(o,d,1,vals,'{}','[]','approver-amend');raise exception'approver amended';exception when insufficient_privilege then null;end;begin perform public.e10_org_commit_action_draft(o,d,1,'approver-commit');raise exception'approver committed';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',reader,'role','authenticated')::text,true);j:=public.e10_org_preview_action_draft(o,d,1);if(j#>>'{values,lines,0,estimated_unit_cost}')::numeric<>44 or j#>>'{field_provenance,supplier_id,text}'<>'private vendor note'or j#>>'{source_references,0,payload,email}'<>'private@example.invalid'then raise exception'read-entitled reviewer lost sensitive preview %',j;end if;
 begin perform public.e10_org_cancel_action_draft(o,d,1,'reader cancel','reader-cancel');raise exception'noncreator reviewer cancelled';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_user,'role','authenticated')::text,true);j:=public.e10_org_commit_action_draft(o,d,1,'admin-commit');if j->>'status'<>'committed'then raise exception'authorized admin commit failed %',j;end if;
end $$;
rollback;
select'TA-X8b permission/redaction matrix PASS'as result;
