const { Client }=require('pg'); const { randomUUID }=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres',org='e1000000-0000-4000-8000-0000000000a6';
const x={u:randomUUID(),role:randomUUID(),product:randomUUID(),run:randomUUID()}; const jwt=JSON.stringify({sub:x.u,role:'authenticated'});
async function cleanup(c){await c.query('reset role').catch(()=>{});await c.query('set session_replication_role=replica');
 await c.query("delete from public.e10_market_observation_supersessions where idempotency_key like $1",['corrected-commit:'+x.run+'-%']);
 await c.query('delete from public.e10_market_observations where organization_id=$1 and product_master_id=$2',[org,x.product]);
 await c.query('delete from public.e10_corrected_intake_commits where idempotency_key like $1',[x.run+'-%']);
 await c.query('delete from public.e10_market_observations where intake_commit_id in(select id from public.e10_intake_commits where idempotency_key like $1)',['%'+x.run+'%']);
 await c.query('delete from public.e10_intake_commits where idempotency_key like $1',['%'+x.run+'%']);await c.query('delete from public.e10_intake_resolver_decisions where idempotency_key like $1',[x.run+'-%']);
 await c.query('delete from public.e10_intake_rows where batch_id in(select id from public.e10_intake_batches where idempotency_key like $1)',[x.run+'-%']);await c.query('delete from public.e10_intake_stage_replays where idempotency_key like $1',[x.run+'-%']);await c.query('delete from public.e10_intake_batches where idempotency_key like $1',[x.run+'-%']);
 await c.query('set session_replication_role=origin');await c.query('delete from public.e10_product_masters where id=$1',[x.product]);await c.query('delete from public.e10_organization_memberships where user_id=$1',[x.u]);await c.query('delete from public.e10_organization_roles where id=$1',[x.role]);await c.query('delete from auth.users where id=$1',[x.u]);}
async function main(){const s=new Client({connectionString:db}),a=new Client({connectionString:db}),b=new Client({connectionString:db});await Promise.all([s.connect(),a.connect(),b.connect()]);try{await cleanup(s);
 await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.u,x.run+'@x.invalid']);await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values($1,$2,$3,'X5f',false)",[x.role,org,x.run]);await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.manage_intake',true)",[org,x.role]);await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active')",[org,x.u,x.role]);await s.query("insert into public.e10_product_masters(id,organization_id,name) values($1,$2,'X5f')",[x.product,org]);await s.query('select set_config($1,$2,false)',['request.jwt.claims',jwt]);await s.query('set role authenticated');
 const stage=async(v,n)=>(await s.query("select public.e10_org_stage_intake($1,'csv','race','same.csv',$2,$3,jsonb_build_array(jsonb_build_object('raw_payload',jsonb_build_object('v',$4::numeric),'observation_kind','asking_price','occurred_at','2025-01-01T00:00:00Z','currency','CAD','amount',$4::numeric)),$5) r",[org,'storage://'+v,'sha-'+v,n,x.run+'-stage-'+v])).rows[0].r;
 const prep=async(st,v)=>{await s.query('reset role');const row=(await s.query('select id from public.e10_intake_rows where batch_id=$1',[st.batch_id])).rows[0].id;await s.query('set role authenticated');await s.query("select public.e10_org_resolve_intake_row($1,$2,'match_product',$3,'reviewed',null,$4)",[org,row,x.product,x.run+'-resolve-'+v]);const rev=Number((await s.query('select public.e10_org_intake_review_state($1,$2) r',[org,st.batch_id])).rows[0].r.review_revision);return{row,rev};};
 const one=await stage('v1',10),p1=await prep(one,'v1');await s.query('select public.e10_org_commit_intake($1,$2,$3,$4)',[org,one.batch_id,p1.rev,x.run+'-commit-v1']);await s.query('reset role');const old=(await s.query('select id from public.e10_market_observations where intake_row_id=$1',[p1.row])).rows[0].id;await s.query('set role authenticated');
 const two=await stage('v2',12),p2=await prep(two,'v2'),classes=[{source_row_number:1,classification:'replacement',superseded_observation_id:old,reason:'corrected'}];await s.query('reset role');
 await a.query('select set_config($1,$2,false)',['request.jwt.claims',jwt]);await a.query('set role authenticated');await a.query('begin');await a.query('select public.e10_org_commit_corrected_intake($1,$2,$3,$4,$5)',[org,two.batch_id,p2.rev,JSON.stringify(classes),x.run+'-corrected']);
 let rows=(await b.query('select id from public.e10_current_market_observations where organization_id=$1 and product_master_id=$2',[org,x.product])).rows;if(rows.length!==1||rows[0].id!==old)throw new Error('uncommitted replacement leaked or old disappeared');await a.query('commit');
 const newer=(await b.query('select id from public.e10_market_observations where intake_row_id=$1',[p2.row])).rows[0].id;rows=(await b.query('select id from public.e10_current_market_observations where organization_id=$1 and product_master_id=$2',[org,x.product])).rows;if(rows.length!==1||rows[0].id!==newer)throw new Error('atomic eligibility switch failed');
 console.log('TA-X5f atomic visibility: PASS (old before commit, replacement after, never both)');
 }finally{await a.query('rollback').catch(()=>{});await cleanup(s);await Promise.all([s.end(),a.end(),b.end()]);}}
main().catch(e=>{console.error(e.stack||e);process.exit(1)});
