const{Client}=require('pg');const{randomUUID}=require('crypto');
const DB=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres',WAIT=8000;
async function c(){const x=new Client({connectionString:DB});await x.connect();await x.query("set statement_timeout='8s';set lock_timeout='7s'");return x}
const settled=p=>p.then(value=>({ok:true,value}),error=>({ok:false,error}));
async function blocked(s,pid,blocker,label){for(let i=0;i<160;i++){if((await s.query('select $1=any(pg_blocking_pids($2)) ok',[blocker,pid])).rows[0].ok){console.log(`[proof] ${label}: ${pid} waits on ${blocker}`);return}await new Promise(r=>setTimeout(r,25))}throw Error('wait proof timeout: '+label)}
async function jwt(x,u){await x.query("select set_config('request.jwt.claims',jsonb_build_object('sub',$1::uuid,'role','authenticated')::text,false)",[u])}
async function main(){const s=await c(),lock=await c(),a=await c(),b=await c();const x={o:randomUUID(),u:randomUUID(),role:randomUUID(),run:randomUUID()};let pending=[];
 try{
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.u,`x8ac-${x.run}@x.invalid`]);await s.query("insert into e10_organizations(id,slug,name)values($1,$2,'X8a concurrency')",[x.o,'x8ac-'+x.run.slice(0,8)]);await s.query("insert into e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,'x8ac','X8a',false)",[x.role,x.o]);await s.query("insert into e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active')",[x.o,x.u,x.role]);await s.query("insert into e10_organization_role_permissions(organization_id,role_id,capability,allowed)values($1,$2,'act.view_market_analytics',true)",[x.o,x.role]);for(const q of[a,b])await jwt(q,x.u);
  await s.query("insert into e10_query_contexts(organization_id,actor_id,purpose,created_at,expires_at)select $1,$2,'workspace',clock_timestamp(),clock_timestamp()+interval'1 hour'from generate_series(1,99)",[x.o,x.u]);
  await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.o+'|'+x.u+'|x8-query-context-cap']);const lp=Number((await lock.query('select pg_backend_pid() pid')).rows[0].pid),ap=Number((await a.query('select pg_backend_pid() pid')).rows[0].pid),bp=Number((await b.query('select pg_backend_pid() pid')).rows[0].pid);const pa=settled(a.query("select e10_org_create_query_context($1,'workspace',600,$2)r",[x.o,'cap-a-'+x.run])),pb=settled(b.query("select e10_org_create_query_context($1,'workspace',600,$2)r",[x.o,'cap-b-'+x.run]));pending.push(pa,pb);await blocked(s,ap,lp,'cap contender A');await blocked(s,bp,lp,'cap contender B');await lock.query('commit');const cap=await Promise.all([pa,pb]);if(cap.filter(z=>z.ok).length!==1||cap.filter(z=>!z.ok).length!==1||cap.find(z=>!z.ok).error.code!=='54000')throw Error('distinct-key live cap race failed');console.log('[proof] distinct command keys admit exactly one context at cap');
  const created=cap.find(z=>z.ok).value.rows[0].r,key=created.replay?'cap-a-'+x.run:(created.context_id?'cap-a-'+x.run:'cap-b-'+x.run);const replayKey=cap[0].ok?'cap-a-'+x.run:'cap-b-'+x.run;
  await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.o+'|'+x.u+'|x8-query-context|'+replayKey]);const pr=settled(a.query("select e10_org_create_query_context($1,'workspace',600,$2)",[x.o,replayKey]));pending.push(pr);await blocked(s,ap,lp,'create replay');await s.query("update e10_organizations set status='suspended'where id=$1",[x.o]);await lock.query('commit');const rr=await pr;if(rr.ok||rr.error.code!=='42501')throw Error('deactivated org create replay succeeded');console.log('[proof] create replay rechecks active org after wait');await s.query("update e10_organizations set status='active'where id=$1",[x.o]);
  const ctx=(await s.query("select id from e10_query_contexts where organization_id=$1 and actor_id=$2 order by created_at desc limit 1",[x.o,x.u])).rows[0].id;await lock.query('begin');await lock.query('select 1 from e10_query_contexts where id=$1 for update',[ctx]);const pv=settled(a.query("select e10_org_revoke_query_context($1,$2,$3)",[x.o,ctx,'revoke-'+x.run]));pending.push(pv);await blocked(s,ap,lp,'fresh revoke');await s.query("update e10_organizations set status='suspended'where id=$1",[x.o]);await lock.query('commit');const vr=await pv;if(vr.ok||vr.error.code!=='42501')throw Error('deactivated org revoke succeeded');console.log('[proof] fresh revoke rechecks active org after row wait');await s.query("update e10_organizations set status='active'where id=$1",[x.o]);
  const exp=(await s.query("insert into e10_query_contexts(organization_id,actor_id,purpose,created_at,expires_at)values($1,$2,'workspace',clock_timestamp(),clock_timestamp()+interval'400 milliseconds')returning id",[x.o,x.u])).rows[0].id;await s.query("insert into e10_inventory_items(id,name,qty,organization_id)values($1,'expiry',1,$2)",['x8ac-'+x.run,x.o]);await lock.query('begin');await lock.query('select 1 from e10_query_contexts where id=$1 for update',[exp]);const pd=settled(a.query("select e10_org_typed_query($1,$2,'inventory.page','{\"limit\":1,\"filters\":{}}')",[x.o,exp]));pending.push(pd);await blocked(s,ap,lp,'dispatcher context row');await new Promise(r=>setTimeout(r,500));await lock.query('commit');const dr=await pd;if(dr.ok||dr.error.code!=='42501')throw Error('expired context dispatcher succeeded');console.log('[proof] dispatcher rejects context expired during row wait');
  const nested=(await s.query("insert into e10_query_contexts(organization_id,actor_id,purpose,created_at,expires_at)values($1,$2,'workspace',clock_timestamp(),clock_timestamp()+interval'500 milliseconds')returning id",[x.o,x.u])).rows[0].id;const before=(await s.query("select(select count(*)from e10_query_contexts where organization_id=$1)c,(select count(*)from e10_query_context_commands where organization_id=$1)q,(select count(*)from e10_market_query_contexts where organization_id=$1)m,(select count(*)from e10_market_query_cursors where organization_id=$1)r",[x.o])).rows[0];await lock.query('begin');await lock.query('select revision from e10_market_catalog_revision where singleton for update');const pn=settled(a.query("select e10_org_typed_query($1,$2,'market.screener',$3)",[x.o,nested,{scope:'catalog',grouping:'entity',metric:'count',observation_kind:'completed_sale',observed_from:'2026-01-01T00:00:00Z',observed_to:'2026-02-01T00:00:00Z',as_of:'2026-02-01T00:00:00Z',source_mode:'none',filters:{},limit:50}]));pending.push(pn);await blocked(s,ap,lp,'dispatcher nested market reader');await new Promise(r=>setTimeout(r,600));await lock.query('commit');const nr=await pn;if(nr.ok||nr.error.code!=='42501')throw Error('context expiry during nested target wait succeeded');const after=(await s.query("select(select count(*)from e10_query_contexts where organization_id=$1)c,(select count(*)from e10_query_context_commands where organization_id=$1)q,(select count(*)from e10_market_query_contexts where organization_id=$1)m,(select count(*)from e10_market_query_cursors where organization_id=$1)r",[x.o])).rows[0];if(JSON.stringify(before)!==JSON.stringify(after))throw Error('denied nested dispatcher left metadata residue');console.log('[proof] dispatcher final context check rejects expiry during nested target wait with zero metadata residue');
 }finally{await lock.query('rollback').catch(()=>{});await Promise.allSettled(pending);await s.query('set session_replication_role=replica');await s.query('delete from e10_query_context_commands where organization_id=$1',[x.o]);await s.query('delete from e10_query_contexts where organization_id=$1',[x.o]);await s.query('delete from e10_inventory_items where organization_id=$1',[x.o]);await s.query('delete from e10_organization_memberships where organization_id=$1',[x.o]);await s.query('delete from e10_organization_roles where organization_id=$1',[x.o]);await s.query('delete from e10_organizations where id=$1',[x.o]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=$1',[x.u]);for(const q of[a,b,lock,s])await q.end().catch(()=>{})}
 console.log('TA-X8a context concurrency: PASS');
}
main().catch(e=>{console.error(e.stack);process.exit(1)});
