const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const x={org:randomUUID(),org2:randomUUID(),user:randomUUID(),outsider:randomUUID(),role:randomUUID(),role2:randomUUID(),customer:randomUUID(),customer2:randomUUID(),draft:randomUUID(),tx:randomUUID(),draft2:randomUUID(),tx2:randomUUID(),line2:randomUUID(),draft3:randomUUID(),tx3:randomUUID(),line3:randomUUID(),location:randomUUID(),activity:randomUUID()};
const sessions=Array.from({length:4},()=>randomUUID());const lines=Array.from({length:201},()=>randomUUID());
async function denied(p,code,msg){try{await p;return false}catch(e){return e.code===code&&(!msg||e.message===msg)}}
async function main(){const c=new Client({connectionString:db}),a=new Client({connectionString:db}),o=new Client({connectionString:db});await Promise.all([c.connect(),a.connect(),o.connect()]);let ok=false;
 try{
  for(const q of[c,a,o])await q.query("set statement_timeout='12s'");await c.query('set session_replication_role=replica');
  for(const [id,label]of[[x.user,'reader'],[x.outsider,'outsider']])await c.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[id,`${label}-${id}@x.invalid`]);
  await c.query("insert into public.e10_organizations(id,slug,name) values($1,$2,'X7b report'),($3,$4,'X7b hostile')",[x.org,'x7br-'+x.org.slice(0,8),x.org2,'x7bh-'+x.org2.slice(0,8)]);
  await c.query("insert into public.e10_reporting_dataset_revisions(organization_id) values($1),($2)",[x.org,x.org2]);
  await c.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values($1,$2,'reader','Reader',false),($3,$4,'hostile','Hostile',false)",[x.role,x.org,x.role2,x.org2]);
  await c.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active'),($4,$5,$6,'active')",[x.org,x.user,x.role,x.org2,x.outsider,x.role2]);
  await c.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_financials',true),($1,$2,'act.view_customer_engagement',true),($1,$2,'act.reconcile_customer_transactions',true),($1,$2,'act.adjust_customer_transactions',true),($1,$2,'act.record_commercial_events',true)",[x.org,x.role]);
  await c.query("insert into public.e10_customers(id,organization_id,display_name) values($1,$3,'Buyer'),($2,$3,'Other')",[x.customer,x.customer2,x.org]);
  await c.query("insert into public.e10_locations(id,organization_id,name,status) values($1,$2,'Store','active')",[x.location,x.org]);
  for(let i=0;i<4;i++)await c.query("insert into public.e10_break_sessions(id,organization_id,streamer_uid,name,status,ended_at,visibility) values($1,$2,$3,$4,'ended',$5,'private')",[sessions[i],x.org,x.user,'Session '+i,`2026-01-${String(6+i).padStart(2,'0')}T12:00:00Z`]);
  await c.query("insert into public.e10_customer_transaction_drafts(id,organization_id,status,current_revision) values($1,$2,'posted',1)",[x.draft,x.org]);
  await c.query("insert into public.e10_customer_transaction_draft_revisions(organization_id,draft_id,revision,customer_id,currency,occurred_at,occurred_at_precision,review_note) values($1,$2,1,$3,'USD','2026-01-06','exact','fixture')",[x.org,x.draft,x.customer]);
  await c.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id,posted_at) values($1,$2,$3,'USD','2026-01-06','exact',$4,1,$5,'2026-01-10')",[x.tx,x.org,x.customer,x.draft,randomUUID()]);
  for(let i=0;i<201;i++){const isBreak=i<2;await c.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,break_session_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence) values($1,$2,$3,$4,$5,$6,'manual',$7,1,$8,$9,$10,$11,'{}')",[lines[i],x.org,x.tx,i+1,isBreak?'break':'retail',isBreak?sessions[i]:null,'line-'+i,isBreak?30:(i===2?200:1),i===2?0:0,i===2?20:0,i===2?10:0]);}
  await c.query("update public.e10_customer_transaction_lines set sales_channel='web',location_id=$3 where organization_id=$1 and id=$2",[x.org,lines[0],x.location]);
  for(const [draft,tx,customer,occurred,precision,event]of[[x.draft2,x.tx2,x.customer2,'2026-01-09','exact',randomUUID()],[x.draft3,x.tx3,x.customer2,null,'unknown',randomUUID()]]){await c.query("insert into public.e10_customer_transaction_drafts(id,organization_id,status,current_revision) values($1,$2,'posted',1)",[draft,x.org]);await c.query("insert into public.e10_customer_transaction_draft_revisions(organization_id,draft_id,revision,customer_id,currency,occurred_at,occurred_at_precision,review_note) values($1,$2,1,$3,'USD',$4,$5,'fixture')",[x.org,draft,customer,occurred,precision]);await c.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id,posted_at) values($1,$2,$3,'USD',$4,$5,$6,1,$7,'2026-01-10')",[tx,x.org,customer,occurred,precision,draft,event]);}
  await c.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,raw_evidence) values($1,$2,$3,1,'break','manual','missing-session',1,40,null,'{}'),($4,$2,$5,1,'retail','manual','unknown-occurrence',1,70,0,'{}')",[x.line2,x.org,x.tx2,x.line3,x.tx3]);
  await c.query("insert into public.e10_customer_transaction_adjustments(id,organization_id,transaction_id,transaction_line_id,adjustment_kind,currency,merchandise_amount,occurred_at,occurred_at_precision,reason,commercial_event_id,effect,source_kind,source_event_id,source_component_id,evidence,idempotency_key,request_fingerprint) values($1,$2,$3,$4,'refund','USD',50,'2026-01-07','exact','fixture',$5,'decrease','manual','refund','refund','{}','refund','refund')",[randomUUID(),x.org,x.tx,lines[2],randomUUID()]);
  for(let i=0;i<201;i++)await c.query("insert into public.e10_customer_transaction_source_claims(organization_id,source_kind,source_connection_id,source_line_id,posted_line_id) values($1,'import','lineage',$2,$3)",[x.org,'child-'+i,lines[0]]);
  await c.query("insert into public.e10_customer_activity_observations(id,organization_id,activity_kind,customer_id,buyer_identity_status,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,currency,occurred_at,occurred_at_precision,source_kind,source_event_id,raw_payload,evidence_quality,idempotency_key,request_fingerprint,commercial_event_id) values($1,$2,'retail',$3,'reviewed_attributed',1,60,0,0,0,'USD','2026-01-08','exact','manual','provisional','{}','operator_asserted','provisional','provisional',$4)",[x.activity,x.org,x.customer,randomUUID()]);
  await c.query("insert into public.e10_presence_collection_policies(organization_id,policy_version,source_class,provider_key,enabled,notice_version,heartbeat_expiry_seconds,min_event_interval_ms,max_events_per_minute,retention_interval,coverage_label,effective_from,effective_through) values($1,1,'companion','companion',true,'notice-v1',300,0,600,interval '365 days','fixture','2026-01-01','2026-02-01')",[x.org]);
  await c.query("insert into public.e10_attendance_coverage_assertions(organization_id,coverage_key,revision,action,source_class,provider_key,covered_from,covered_to,coverage_status,policy_version,review_basis,evidence,idempotency_key,request_fingerprint) values($1,$2,1,'assert','companion','companion','2026-01-01','2026-02-01','complete',1,'fixture','{}','coverage','coverage')",[x.org,randomUUID()]);
  for(let i=0;i<4;i++){const stream=randomUUID(),seg=randomUUID();await c.query("insert into public.e10_session_presence_streams(id,organization_id,session_id,source_class,provider_key,subject_key,connection_id,observed_user_id,original_customer_id,identity_status,collection_policy_version,notice_version,coverage_label,retention_expires_at) values($1,$2,$3,'companion','companion',$4,$5,$7,$6,'reviewed_attributed',1,'notice-v1','fixture','2027-01-01')",[stream,x.org,sessions[i],x.user,'conn-'+i,x.customer,x.user]);await c.query("insert into public.e10_session_presence_segments(id,organization_id,stream_id,segment_sequence,heartbeat_expiry_seconds,retention_expires_at,collection_policy_version,notice_version,coverage_label) values($1,$2,$3,1,300,'2027-01-01',1,'notice-v1','fixture')",[seg,x.org,stream]);await c.query("insert into public.e10_session_presence_events(organization_id,stream_id,segment_id,event_sequence,event_kind,server_received_at,evidence,request_fingerprint) values($1,$2,$3,1,'join',$4,'{}',$6),($1,$2,$3,2,'leave',$5,'{}',$6)",[x.org,stream,seg,`2026-01-0${6+i}T10:00:00Z`,`2026-01-0${6+i}T10:10:00Z`,'presence-'+i]);}
  await c.query('set session_replication_role=origin');for(const [q,id]of[[a,x.user],[o,x.outsider]]){await q.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,role:'authenticated'})]);await q.query('set role authenticated');}
  const args=[x.org,'2026-01-01','2026-02-01','2026-02-01','USD'],detailArgs=[...args,x.customer];
  const mapped=(await a.query("select public.e10_org_bind_customer_activity_source_component($1,$2,'prov-component','reviewed mapping',$3) r",[x.org,x.activity,'map-'+x.org])).rows[0].r;const mappedReplay=(await a.query("select public.e10_org_bind_customer_activity_source_component($1,$2,'prov-component','reviewed mapping',$3) r",[x.org,x.activity,'map-'+x.org])).rows[0].r;if(mapped.replay||!mappedReplay.replay)throw Error('typed activity source mapping replay failed');
  const recordActivity="select public.e10_org_record_customer_activity($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21::jsonb,$22,$23) r";const actA=(await a.query(recordActivity,[x.org,'retail',x.customer2,null,null,null,null,1,10,0,0,0,'USD',null,'2026-01-13','exact','import','two-line','batch','evt-a','{}','reviewed_import','activity-a-'+x.org])).rows[0].r.activity_id;const actB=(await a.query(recordActivity,[x.org,'retail',x.customer2,null,null,null,null,1,20,0,0,0,'USD',null,'2026-01-13','exact','import','two-line','batch','evt-b','{}','reviewed_import','activity-b-'+x.org])).rows[0].r.activity_id;await a.query("select public.e10_org_bind_customer_activity_source_component($1,$2,'comp-a','reviewed component',$3)",[x.org,actA,'map-a-'+x.org]);let twoLine=(await a.query("select public.e10_org_customer_provisional_activity($1,$2,$3,$4,$5,$6,100,null,null,null,null) j",[...args,x.customer2])).rows[0].j;if(Number(twoLine.totals.known_provisional_merchandise_subtotal)!==30||Number(twoLine.totals.mapped_source_component_count)!==1||Number(twoLine.totals.unmapped_source_component_count)!==1)throw Error('two-line typed intake mapping state failed '+JSON.stringify(twoLine.totals));const partialCase=(await a.query("select public.e10_org_open_customer_transaction_reconciliation($1,'import','two-line','evt-a','comp-a','USD',10,null,null,'{}',$2) r",[x.org,'open-a-'+x.org])).rows[0].r;await a.query("select public.e10_org_decide_customer_transaction_reconciliation($1,$2,0,'link','reviewed_match',$3,$4,'partial component link','{}',$5)",[x.org,partialCase.case_id,x.tx,lines[5],'partial-link-'+x.org]);twoLine=(await a.query("select public.e10_org_customer_provisional_activity($1,$2,$3,$4,$5,$6,100,null,null,null,null) j",[...args,x.customer2])).rows[0].j;if(Number(twoLine.totals.known_provisional_merchandise_subtotal)!==20||twoLine.items[0].id!==actB||twoLine.items[0].posting_linkage_status!=='unmapped_source_component')throw Error('partial component link suppressed sibling or hid unresolved state');await a.query("select public.e10_org_decide_customer_transaction_reconciliation($1,$2,1,'unlink',null,null,null,'partial unlink','{}',$3)",[x.org,partialCase.case_id,'partial-unlink-'+x.org]);twoLine=(await a.query("select public.e10_org_customer_provisional_activity($1,$2,$3,$4,$5,$6,100,null,null,null,null) j",[...args,x.customer2])).rows[0].j;if(Number(twoLine.totals.known_provisional_merchandise_subtotal)!==30)throw Error('partial unlink failed');await a.query("select public.e10_org_decide_customer_transaction_reconciliation($1,$2,2,'link','reviewed_match',$3,$4,'partial relink','{}',$5)",[x.org,partialCase.case_id,x.tx,lines[5],'partial-relink-'+x.org]);
  let r=(await a.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,$6,null,null,null,null,null,null,null,null,200,null,null,null,null,null) j",detailArgs)).rows[0].j;
  if(r.items.length!==200||Number(r.totals.line_count)!==201)throw Error('detail page/full total failed '+JSON.stringify(r.totals));const last=r.items[199];
  let r2=(await a.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,$6,null,null,null,null,null,null,null,null,200,$7,$8,$9,$10,$11) j",[...detailArgs,last.occurred_at,last.transaction_id,last.transaction_line_id,r.dataset_revision,r.query_fingerprint])).rows[0].j;if(r2.items.length!==1||Number(r2.totals.line_count)!==201)throw Error('detail continuation failed');
  if(!await denied(a.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,$6,null,null,null,null,null,null,null,null,200,$7,$8,$9,$10,$11)",[...detailArgs,'1900-01-01',randomUUID(),randomUUID(),r.dataset_revision,r.query_fingerprint]),'22023','customer_spend_cursor_invalid'))throw Error('arbitrary cursor accepted');
  if(!await denied(a.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,$6,null,null,null,null,null,null,null,null,200,$7,$8,$9,$10,'bad')",[...detailArgs,last.occurred_at,last.transaction_id,last.transaction_line_id,r.dataset_revision]),'22023','customer_spend_cursor_query_mismatch'))throw Error('cursor rebound');
  let lin=(await a.query("select public.e10_org_customer_spend_lineage($1,$2,$3,200,null,null,null,null,null) j",[x.org,lines[0],'2026-02-01'])).rows[0].j;if(lin.items.length!==200||Number(lin.full_child_count)!==201)throw Error('lineage page/count failed '+JSON.stringify(lin));
  const lc=lin.items[199];const lin2=(await a.query("select public.e10_org_customer_spend_lineage($1,$2,$3,200,$4,$5,$6,$7,$8) j",[x.org,lines[0],'2026-02-01',lc.recorded_at,lc.kind,lc.id,lin.dataset_revision,lin.query_fingerprint])).rows[0].j;if(lin2.items.length!==1||Number(lin2.full_child_count)!==201)throw Error('lineage continuation/full total failed');
  let summary=(await a.query("select public.e10_org_customer_spend_summary($1,$2,$3,$4,$5,'UTC',1,$6,null,null,null,null,null,null,null,null,100,null,null,null) j",detailArgs)).rows[0].j;let row=summary.items[0];
  if(Number(row.known_break_subtotal)!==60||Number(row.purchasing_breaks)!==2||Number(row.attended_breaks)!==4||Number(row.spend_per_purchasing_break)!==30||Number(row.spend_per_attended_break)!==15||row.attended_ratio_status!=='complete')throw Error('summary denominator failed '+JSON.stringify(row));
  if(Number(row.known_shipping_subtotal)!==20||Number(row.known_tax_subtotal)!==10||Number(row.known_official_subtotal)!==408)throw Error('component separation failed '+JSON.stringify(row));
  if(Number(summary.full_cohort_totals.line_count)!==201||summary.purchase_kind_scope!=='combined'||Number(row.merchandise_gross)!==458||Number(row.signed_merchandise_adjustment_delta)!==-50)throw Error('summary measures/full cohort failed '+JSON.stringify(summary));
  if(Number(summary.authorized_data_diagnostics.unknown_occurrence_line_count)!==0||summary.authorized_data_diagnostics.unattributed_org_authorized_line_count!==null||summary.authorized_data_diagnostics.scope!=='selected_effective_customer')throw Error('customer-filtered diagnostics leaked org data '+JSON.stringify(summary.authorized_data_diagnostics));
  let provisional=(await a.query("select public.e10_org_customer_provisional_activity($1,$2,$3,$4,$5,$6,100,null,null,null,null) j",detailArgs)).rows[0].j;if(Number(provisional.totals.known_provisional_merchandise_subtotal)!==60||Number(provisional.totals.mapped_source_component_count)!==1||provisional.items[0].posting_linkage_status!=='mapped_source_component'||provisional.official_spend!==false)throw Error('provisional separation/mapping failed');
  const opened=(await a.query("select public.e10_org_open_customer_transaction_reconciliation($1,'manual',null,'provisional','prov-component','USD',60,null,null,'{}',$2) r",[x.org,'open-'+x.org])).rows[0].r;
  let decision=(await a.query("select public.e10_org_decide_customer_transaction_reconciliation($1,$2,0,'link','reviewed_match',$3,$4,'fixture link','{}',$5) r",[x.org,opened.case_id,x.tx,lines[0],'link-'+x.org])).rows[0].r;
  provisional=(await a.query("select public.e10_org_customer_provisional_activity($1,$2,$3,$4,$5,$6,100,null,null,null,null) j",detailArgs)).rows[0].j;if(Number(provisional.totals.activity_count)!==0)throw Error('reviewed linked activity remained provisional');
  decision=(await a.query("select public.e10_org_decide_customer_transaction_reconciliation($1,$2,1,'unlink',null,null,null,'fixture unlink','{}',$3) r",[x.org,opened.case_id,'unlink-'+x.org])).rows[0].r;
  provisional=(await a.query("select public.e10_org_customer_provisional_activity($1,$2,$3,$4,$5,$6,100,null,null,null,null) j",detailArgs)).rows[0].j;if(Number(provisional.totals.known_provisional_merchandise_subtotal)!==60)throw Error('unlink did not restore provisional activity');
  decision=(await a.query("select public.e10_org_decide_customer_transaction_reconciliation($1,$2,2,'link','reviewed_match',$3,$4,'fixture relink','{}',$5) r",[x.org,opened.case_id,x.tx,lines[0],'relink-'+x.org])).rows[0].r;
  provisional=(await a.query("select public.e10_org_customer_provisional_activity($1,$2,$3,$4,$5,$6,100,null,null,null,null) j",detailArgs)).rows[0].j;if(Number(provisional.totals.activity_count)!==0)throw Error('relink did not suppress provisional activity');
  let unsupported=(await a.query("select public.e10_org_customer_spend_summary($1,$2,$3,$4,$5,'UTC',1,$6,null,null,'web',null,null,null,null,null,100,null,null,null) j",detailArgs)).rows[0].j;if(unsupported.items[0].attended_ratio_status!=='unsupported_cohort'||unsupported.items[0].attended_breaks!==null)throw Error('sale-only cohort was divided');
  const multi=(await a.query("select public.e10_org_customer_spend_summary($1,$2,$3,$4,$5,'UTC',1,null,null,null,null,null,null,null,null,null,1,null,null,null) j",args)).rows[0].j;if(multi.items.length!==1||Number(multi.full_cohort_totals.customer_count)!==2)throw Error('summary full-cohort page one failed');const mc=multi.items[0].effective_customer_id;const multi2=(await a.query("select public.e10_org_customer_spend_summary($1,$2,$3,$4,$5,'UTC',1,null,null,null,null,null,null,null,null,null,1,$6,$7,$8) j",[...args,mc,multi.dataset_revision,multi.query_fingerprint])).rows[0].j;if(multi2.items.length!==1||Number(multi2.full_cohort_totals.customer_count)!==2)throw Error('summary continuation/full total failed');const unknownRow=[...multi.items,...multi2.items].find(z=>z.effective_customer_id===x.customer2);if(!unknownRow||unknownRow.purchasing_ratio_status!=='unknown_merchandise'||unknownRow.attended_ratio_status!=='unknown_merchandise')throw Error('unknown missing-session ratio did not fail closed '+JSON.stringify(unknownRow));if(Number(multi.authorized_data_diagnostics.unknown_occurrence_line_count)!==1)throw Error('authorized diagnostics missing '+JSON.stringify(multi.authorized_data_diagnostics));
  await c.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.view_customer_financials'",[x.org,x.role]);await c.query("insert into public.e10_location_role_permissions(organization_id,location_id,role_id,can_view_customer_financials) values($1,$2,$3,true)",[x.org,x.location,x.role]);const narrow=(await a.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,null,null,null,null,null,null,null,null,null,100,null,null,null,null,null) j",args)).rows[0].j;if(narrow.authorization_scope!=='authorized_locations'||narrow.items.length!==1||narrow.items[0].transaction_line_id!==lines[0]||Number(narrow.totals.line_count)!==1)throw Error('location-only scope leaked hidden rows '+JSON.stringify(narrow));const narrowSummary=(await a.query("select public.e10_org_customer_spend_summary($1,$2,$3,$4,$5,'UTC',1,null,null,null,null,null,null,null,null,null,100,null,null,null) j",args)).rows[0].j;if(narrowSummary.items[0].attended_ratio_status!=='unsupported_cohort')throw Error('location-only attendance ratio was exposed');if(!await denied(a.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,null,null,$6,null,null,null,null,null,null,100,null,null,null,null,null)",[...args,randomUUID()]),'42501','customer_spend_location_denied'))throw Error('foreign location filter accepted');await c.query("delete from public.e10_location_role_permissions where organization_id=$1 and location_id=$2 and role_id=$3",[x.org,x.location,x.role]);await c.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_financials',true)",[x.org,x.role]);
  await c.query("update public.e10_break_sessions set ended_at=clock_timestamp() where organization_id=$1 and id=$2",[x.org,sessions[0]]);if(!await denied(a.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,$6,null,null,null,null,null,null,null,null,100,null,null,null,$7,null)",[...detailArgs,r.dataset_revision]),'40001','customer_spend_revision_stale'))throw Error('stale dataset revision accepted');
  await c.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.view_customer_engagement'",[x.org,x.role]);summary=(await a.query("select public.e10_org_customer_spend_summary($1,$2,$3,$4,$5,'UTC',1,$6,null,null,null,null,null,null,null,null,100,null,null,null) j",detailArgs)).rows[0].j;if(summary.items[0].attended_ratio_status!=='engagement_not_authorized'||summary.items[0].attended_breaks!==null)throw Error('financial-only attendance leaked');
  if(!await denied(o.query("select public.e10_org_customer_spend_contributions($1,$2,$3,$4,$5,null,null,null,null,null,null,null,null,null,100,null,null,null,null,null)",args),'42501','customer_spend_denied'))throw Error('hostile org member read allowed');
  if(!await denied(a.query("select public.e10_org_customer_spend_summary($1,'2024-01-01','2026-02-01','2026-02-01','USD','UTC',1,null,null,null,null,null,null,null,null,null,100,null,null,null)",[x.org]),'22023','customer_spend_summary_bounds_invalid'))throw Error('overlong summary window accepted');if(!await denied(a.query("select public.e10_org_customer_provisional_activity($1,'2026-01-01','2026-02-01','infinity','USD',null,100,null,null,null,null)",[x.org]),'22023','customer_provisional_activity_bounds_invalid'))throw Error('infinite cutoff accepted');
  const acl=(await c.query("select has_function_privilege('anon','public.e10_org_customer_spend_contributions(uuid,timestamptz,timestamptz,timestamptz,text,uuid,text,uuid,text,uuid,uuid,uuid,uuid,text,integer,timestamptz,uuid,uuid,bigint,text)','execute') a,has_function_privilege('anon','public.e10_org_customer_spend_lineage(uuid,uuid,timestamptz,integer,timestamptz,text,uuid,bigint,text)','execute') b,has_function_privilege('anon','public.e10_org_customer_spend_summary(uuid,timestamptz,timestamptz,timestamptz,text,text,integer,uuid,text,uuid,text,uuid,uuid,uuid,uuid,text,integer,uuid,bigint,text)','execute') d,has_function_privilege('anon','public.e10_org_customer_provisional_activity(uuid,timestamptz,timestamptz,timestamptz,text,uuid,integer,timestamptz,uuid,bigint,text)','execute') e,has_function_privilege('anon','public.e10_org_bind_customer_activity_source_component(uuid,uuid,text,text,text)','execute') f,has_table_privilege('authenticated','public.e10_customer_activity_source_components','select') g,has_function_privilege('authenticated','e10.customer_attendance_denominator(uuid,uuid,timestamptz,timestamptz,timestamptz,text,integer,uuid)','execute') h")).rows[0];if(acl.a||acl.b||acl.d||acl.e||acl.f||acl.g||acl.h)throw Error('reporting ACL failed '+JSON.stringify(acl));ok=true;
 }finally{for(const q of[a,o]){await q.query('rollback').catch(()=>{});await q.query('reset role').catch(()=>{})}await c.query('set session_replication_role=replica');const tables=['e10_customer_transaction_evidence_links','e10_customer_transaction_reconciliation_decisions','e10_customer_transaction_source_claims','e10_customer_transaction_reconciliation_cases','e10_customer_commercial_receipts','e10_customer_transaction_adjustments','e10_customer_transaction_component_finalizations','e10_customer_transaction_lines','e10_customer_transactions','e10_customer_transaction_draft_revisions','e10_customer_transaction_drafts','e10_commercial_events','e10_customer_activity_source_components','e10_customer_activity_observations','e10_attendance_coverage_assertions','e10_reporting_dataset_revisions','e10_session_presence_events','e10_session_presence_segments','e10_session_presence_streams','e10_presence_policy_state_history','e10_presence_collection_policies','e10_break_sessions','e10_location_role_permissions','e10_locations','e10_customers','e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles'];for(const t of tables)await c.query(`delete from public.${t} where organization_id in($1,$2)`,[x.org,x.org2]);await c.query('delete from public.e10_organizations where id in($1,$2)',[x.org,x.org2]);await c.query('set session_replication_role=origin');await c.query('delete from auth.users where id in($1,$2)',[x.user,x.outsider]);let residue=Number((await c.query('select count(*) n from public.e10_organizations where id in($1,$2)',[x.org,x.org2])).rows[0].n);for(const t of tables)residue+=Number((await c.query(`select count(*) n from public.${t} where organization_id in($1,$2)`,[x.org,x.org2])).rows[0].n);residue+=Number((await c.query('select count(*) n from auth.users where id in($1,$2)',[x.user,x.outsider])).rows[0].n);const sentinel=Number((await c.query("select count(*) n from public.e10_organizations where id='e1000000-0000-4000-8000-0000000000a6'")).rows[0].n);await Promise.all([c.end(),a.end(),o.end()]);if(residue||sentinel!==1)throw Error('X7b report cleanup failed '+JSON.stringify({residue,sentinel}))}
 if(ok)console.log('TA-X7b spend reporting: PASS');
}main().catch(e=>{console.error(e.stack);process.exit(1)});
