const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres',WAIT=8000;
async function client(){const c=new Client({connectionString:db});await c.connect();await c.query("set statement_timeout='8s';set lock_timeout='7s'");return c}
async function waitBlocked(s,pid,blocker,label){const until=Date.now()+WAIT;while(Date.now()<until){if((await s.query('select $1=any(pg_blocking_pids($2)) ok',[blocker,pid])).rows[0].ok){console.log(`[proof] ${label}: backend ${pid} blocked by ${blocker}`);return}await new Promise(r=>setTimeout(r,25))}throw Error(`timeout waiting for ${label}`)}
const result=p=>p.then(value=>({ok:true,value}),error=>({ok:false,error}));
async function main(){const s=await client(),lock=await client(),a=await client(),b=await client();const x={org:randomUUID(),actor:randomUUID(),run:randomUUID()};let ok=false;const pending=[];
 try{
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.actor,`x7dctx-${x.run}@x.invalid`]);await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7d context race')",[x.org,'x7dctx-'+x.run.slice(0,8)]);
  for(let i=0;i<99;i++){const req={n:i},fp=(await s.query("select e10.market_query_fingerprint('v1',$1,$2,'screener',$3,'[]',1,1) fp",[x.org,x.actor,req])).rows[0].fp;await s.query("select e10.save_market_query_context('v1',$1,$2,'screener',$3,$4,'[]',1,1,'{}')",[x.org,x.actor,fp,req])}
  const lp=(await lock.query('select pg_backend_pid() pid')).rows[0].pid,ap=(await a.query('select pg_backend_pid() pid')).rows[0].pid,bp=(await b.query('select pg_backend_pid() pid')).rows[0].pid;
  await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.org+'|'+x.actor+'|market-query-state']);
  const reqA={race:'a'},reqB={race:'b'};const fpA=(await s.query("select e10.market_query_fingerprint('v1',$1,$2,'screener',$3,'[]',1,1) fp",[x.org,x.actor,reqA])).rows[0].fp,fpB=(await s.query("select e10.market_query_fingerprint('v1',$1,$2,'screener',$3,'[]',1,1) fp",[x.org,x.actor,reqB])).rows[0].fp;
  const ca=result(a.query("select e10.save_market_query_context('v1',$1,$2,'screener',$3,$4,'[]',1,1,'{}')",[x.org,x.actor,fpA,reqA])),cb=result(b.query("select e10.save_market_query_context('v1',$1,$2,'screener',$3,$4,'[]',1,1,'{}')",[x.org,x.actor,fpB,reqB]));pending.push(ca,cb);await waitBlocked(s,ap,lp,'context cap contender A');await waitBlocked(s,bp,lp,'context cap contender B');await lock.query('commit');const cr=await Promise.all([ca,cb]);if(cr.filter(v=>v.ok).length!==1||cr.filter(v=>!v.ok||false).length!==1||cr.find(v=>!v.ok).error.code!=='54000')throw Error('context cap race did not admit exactly one');console.log('[proof] context cap serialized at 100');
  const context=(await s.query("select id,query_fingerprint from public.e10_market_query_contexts where organization_id=$1 and actor_id=$2 order by created_at limit 1",[x.org,x.actor])).rows[0];for(let i=0;i<999;i++)await s.query("select e10.save_market_query_cursor($1,$2,$3,'screener',$4,jsonb_build_object('n',$5::integer),null,1,1)",[context.id,x.org,x.actor,context.query_fingerprint,i]);
  await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.org+'|'+x.actor+'|market-query-state']);const ua=result(a.query("select e10.save_market_query_cursor($1,$2,$3,'screener',$4,'{\"race\":\"a\"}',null,1,1)",[context.id,x.org,x.actor,context.query_fingerprint])),ub=result(b.query("select e10.save_market_query_cursor($1,$2,$3,'screener',$4,'{\"race\":\"b\"}',null,1,1)",[context.id,x.org,x.actor,context.query_fingerprint]));pending.push(ua,ub);await waitBlocked(s,ap,lp,'cursor cap contender A');await waitBlocked(s,bp,lp,'cursor cap contender B');await lock.query('commit');const ur=await Promise.all([ua,ub]);if(ur.filter(v=>v.ok).length!==1||ur.filter(v=>!v.ok).length!==1||ur.find(v=>!v.ok).error.code!=='54000')throw Error('cursor cap race did not admit exactly one');console.log('[proof] cursor cap serialized at 1000');
  await s.query('delete from public.e10_market_query_cursors where organization_id=$1',[x.org]);const exp=(await s.query("insert into public.e10_market_query_contexts(organization_id,actor_id,endpoint,api_version,query_fingerprint,normalized_request,resolved_source_universe,organization_revision,catalog_revision,cohort_keys,total_row_count,created_at,expires_at)values($1,$2,'screener','v1',$3,'{}','[]',1,1,'{}',0,clock_timestamp(),clock_timestamp()+interval'300 milliseconds')returning id",[x.org,x.actor,'2'.repeat(64)])).rows[0].id;await lock.query('begin');await lock.query('select 1 from public.e10_market_query_contexts where id=$1 for update',[exp]);const ep=result(a.query("select e10.save_market_query_cursor($1,$2,$3,'screener',$4,'{}',null,1,1)",[exp,x.org,x.actor,'2'.repeat(64)]));pending.push(ep);await waitBlocked(s,ap,lp,'cursor waits across context expiry');await new Promise(r=>setTimeout(r,400));await lock.query('commit');const er=await ep;if(er.ok||er.error.code!=='22023')throw Error('post-wait expired context accepted');if(Number((await s.query('select count(*) n from public.e10_market_query_cursors where context_id=$1',[exp])).rows[0].n)!==0)throw Error('expired cursor persisted');console.log('[proof] post-row-lock context expiry rejected');ok=true;
 }finally{await lock.query('rollback').catch(()=>{});await Promise.allSettled(pending);await s.query('set session_replication_role=replica');await s.query('delete from public.e10_market_query_cursors where organization_id=$1',[x.org]);await s.query('delete from public.e10_market_query_contexts where organization_id=$1',[x.org]);await s.query('delete from public.e10_market_org_revisions where organization_id=$1',[x.org]);await s.query('delete from public.e10_organizations where id=$1',[x.org]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=$1',[x.actor]);const residue=Number((await s.query('select(select count(*)from public.e10_market_query_contexts where organization_id=$1)+(select count(*)from public.e10_market_query_cursors where organization_id=$1)+(select count(*)from public.e10_organizations where id=$1)+(select count(*)from auth.users where id=$2)n',[x.org,x.actor])).rows[0].n);for(const c of[a,b,lock,s])await c.end().catch(()=>{});if(residue)throw Error('query context concurrency cleanup residue')}
 if(ok)console.log('TA-X7d.2 query context concurrency: PASS');
}
main().catch(e=>{console.error(e.stack);process.exit(1)});
