const { Client } = require('pg'); const { randomUUID } = require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres'; const org='e1000000-0000-4000-8000-0000000000a6'; const x={u:randomUUID(),role:randomUUID(),p:randomUUID(),run:randomUUID()};
async function main(){const s=new Client({connectionString:db}),a=new Client({connectionString:db}),b=new Client({connectionString:db});await Promise.all([s.connect(),a.connect(),b.connect()]);try{
 await s.query('begin'); await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.u,x.run+'@x.invalid']);
 await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values($1,$2,$3,'X5e Race',false)",[x.role,org,x.run]); await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.manage_intake',true)",[org,x.role]); await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active')",[org,x.u,x.role]); await s.query("insert into public.e10_product_masters(id,organization_id,name) values($1,$2,'X5e Race')",[x.p,org]);
 const old=(await s.query("insert into public.e10_market_observations(organization_id,observation_kind,product_master_id,occurred_at,currency,amount,source_kind,raw_payload_snapshot) values($1,'asking_price',$2,now(),'CAD',1,'manual','{}') returning id",[org,x.p])).rows[0].id; await s.query('commit');
 for(const c of [a,b]){await c.query('select set_config($1,$2,false)',['request.jwt.claims',JSON.stringify({sub:x.u,role:'authenticated'})]);await c.query('set role authenticated');}
 const q="select public.e10_org_correct_market_observation($1,$2,'estimated_value','product',$3,'2025-01-01T00:00:00Z','CAD',2,1,'race','{}','race',$4) r"; const [ra,rb]=await Promise.all([a.query(q,[org,old,x.p,x.run]),b.query(q,[org,old,x.p,x.run])]); const rs=[ra.rows[0].r,rb.rows[0].r]; if(rs.filter(v=>!v.replay).length!==1||rs[0].observation_id!==rs[1].observation_id)throw new Error(JSON.stringify(rs)); console.log('TA-X5e concurrent correction: PASS');
}finally{await s.query('set session_replication_role=replica').catch(()=>{});await s.query('delete from public.e10_market_observation_supersessions where idempotency_key=$1',[x.run]).catch(()=>{});await s.query('delete from public.e10_market_observations where organization_id=$1 and product_master_id=$2',[org,x.p]).catch(()=>{});await s.query('set session_replication_role=origin').catch(()=>{});await s.query('delete from public.e10_product_masters where id=$1',[x.p]).catch(()=>{});await s.query('delete from public.e10_organization_memberships where user_id=$1',[x.u]).catch(()=>{});await s.query('delete from public.e10_organization_roles where id=$1',[x.role]).catch(()=>{});await s.query('delete from auth.users where id=$1',[x.u]).catch(()=>{});await Promise.all([s.end(),a.end(),b.end()]);}} main().catch(e=>{console.error(e.stack);process.exit(1)});
