const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
async function main(){const s=new Client({connectionString:db}),lock=new Client({connectionString:db}),reader=new Client({connectionString:db}),admin=new Client({connectionString:db});await Promise.all([s.connect(),lock.connect(),reader.connect(),admin.connect()]);const org=randomUUID(),user=randomUUID(),role=randomUUID();let ok=false,pending;
 try{
  await s.query('set session_replication_role=replica');await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[user,`x7fc-${user}@x.invalid`]);await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7f concurrent')",[org,'x7fc-'+org.slice(0,8)]);await s.query('insert into public.e10_reporting_dataset_revisions(organization_id)values($1)on conflict do nothing',[org]);await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,'reader','Reader',false)",[role,org]);await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active')",[org,user,role]);await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_financials',true)",[org,role]);
  await reader.query("select set_config('request.jwt.claims',jsonb_build_object('sub',$1::text,'role','authenticated')::text,false)",[user]);await reader.query('set role authenticated');await lock.query('begin');await lock.query('select revision from public.e10_reporting_dataset_revisions where organization_id=$1 for update',[org]);const pid=Number((await reader.query('select pg_backend_pid()pid')).rows[0].pid);
  pending=reader.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'bounded',p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1,p_limit=>1)",[org]).then(()=>({ok:true}),e=>({ok:false,e}));
  let blocked=false;for(let i=0;i<40;i++){const r=(await s.query("select wait_event_type from pg_stat_activity where pid=$1",[pid])).rows[0];if(r&&r.wait_event_type==='Lock'){blocked=true;break}await new Promise(r=>setTimeout(r,50))}if(!blocked)throw Error('reader did not establish revision-lock wait');
  await admin.query('set session_replication_role=replica');await admin.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.view_customer_financials'",[org,role]);await lock.query('commit');const result=await pending;if(result.ok||result.e.code!=='42501'||result.e.message!=='customer_spend_denied')throw Error('post-lock capability revocation was not enforced');ok=true;
 }finally{await lock.query('rollback').catch(()=>{});await reader.query('reset role').catch(()=>{});await s.query('set session_replication_role=replica');for(const t of['e10_reporting_dataset_revisions','e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles'])await s.query(`delete from public.${t} where organization_id=$1`,[org]);await s.query('delete from public.e10_organizations where id=$1',[org]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=$1',[user]);await Promise.all([s.end(),lock.end(),reader.end(),admin.end()])}
 if(ok)console.log('TA-X7f post-lock authorization: PASS');
}main().catch(e=>{console.error(e);process.exit(1)});
