const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const x={org:randomUUID(),org2:randomUUID(),user:randomUUID(),role:randomUUID(),role2:randomUUID(),customer:randomUUID(),active:randomUUID(),archived:randomUUID(),foreignLocation:randomUUID(),t1:randomUUID(),t2:randomUUID(),l1:randomUUID(),l2:randomUUID(),d1:randomUUID(),d2:randomUUID(),e1:randomUUID(),e2:randomUUID(),adj:randomUUID(),fin1:randomUUID(),fin2:randomUUID()};
async function denied(p,code,msg){try{await p;return false}catch(e){return e.code===code&&(!msg||e.message===msg)}}
async function main(){const c=new Client({connectionString:db});await c.connect();let ok=false;
 try{
  await c.query("set statement_timeout='8s'");await c.query('set session_replication_role=replica');
  await c.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.user,x.user+'@x.invalid']);
  await c.query("insert into public.e10_organizations(id,slug,name) values($1,$2,'X7b fixture')",[x.org,'x7b-'+x.org]);
  await c.query("insert into public.e10_organizations(id,slug,name) values($1,$2,'X7b foreign fixture')",[x.org2,'x7f-'+x.org2]);
  await c.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values($1,$2,'admin','X7b',false)",[x.role,x.org]);
  await c.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values($1,$2,$3,'X7b foreign',false)",[x.role2,x.org2,x.role2]);
  await c.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active')",[x.org,x.user,x.role]);
  await c.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active')",[x.org2,x.user,x.role2]);
  await c.query("insert into public.e10_customers(id,organization_id,display_name) values($1,$2,'Customer')",[x.customer,x.org]);
  await c.query("insert into public.e10_locations(id,organization_id,name,status) values($1,$3,'Active','active'),($2,$3,'Archived','archived')",[x.active,x.archived,x.org]);
  await c.query("insert into public.e10_locations(id,organization_id,name,status) values($1,$2,'Foreign','active')",[x.foreignLocation,x.org2]);
  for(const [d,t,e]of[[x.d1,x.t1,x.e1],[x.d2,x.t2,x.e2]]){
   await c.query("insert into public.e10_customer_transaction_drafts(id,organization_id,status,current_revision) values($1,$2,'posted',1)",[d,x.org]);
   await c.query("insert into public.e10_customer_transaction_draft_revisions(organization_id,draft_id,revision,customer_id,currency,occurred_at,occurred_at_precision,review_note) values($1,$2,1,$3,'USD','2026-01-06','exact','fixture')",[x.org,d,x.customer]);
   await c.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id,posted_at) values($1,$2,$3,'USD','2026-01-06','exact',$4,1,$5,'2026-02-01')",[t,x.org,x.customer,d,e]);
  }
  await c.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,location_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence) values($1,$3,$4,1,'retail',$5,'manual','line-1',1,200,0,20,10,'{}'),($2,$3,$6,1,'break',$7,'manual','line-2',1,100,null,null,null,'{}')",[x.l1,x.l2,x.org,x.t1,x.active,x.t2,x.archived]);
  await c.query("insert into public.e10_customer_transaction_adjustments(id,organization_id,transaction_id,transaction_line_id,adjustment_kind,currency,merchandise_amount,occurred_at,occurred_at_precision,reason,commercial_event_id,effect,source_kind,source_event_id,source_component_id,evidence,idempotency_key,request_fingerprint) values($1,$2,$3,$4,'refund','USD',50,'2026-03-01','exact','fixture',$5,'decrease','manual','refund-event','refund-component','{}','refund-idem','refund-fp')",[x.adj,x.org,x.t1,x.l1,randomUUID()]);
  await c.query("insert into public.e10_customer_transaction_component_finalizations(id,organization_id,transaction_id,transaction_line_id,component,final_amount,currency,reason,evidence,source_kind,source_event_id,source_component_id,idempotency_key,request_fingerprint,commercial_event_id) values($1,$3,$4,$5,'merchandise',80,'USD','fixture','{}','manual','fin-event-1','fin-component-1','fin-idem-1','fin-fp-1',$6),($2,$3,$4,$5,'shipping',0,'USD','fixture','{}','manual','fin-event-2','fin-component-2','fin-idem-2','fin-fp-2',$7)",[x.fin1,x.fin2,x.org,x.t2,x.l2,randomUUID(),randomUUID()]);
  await c.query('set session_replication_role=origin');
  await c.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:x.user,role:'authenticated'})]);
  await c.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed) values($1,$2,'act.view_customer_financials',true),($1,$2,'act.permissions_config',true)",[x.org,x.role]);
  let p=(await c.query("select e10.can_view_customer_financials_at($1,null) n,e10.can_view_customer_financials_at($1,$2) a,e10.can_view_customer_financials_at($1,$3) z",[x.org,x.active,x.archived])).rows[0];
  if(!p.n||!p.a||!p.z)throw Error('orgwide financial authority failed '+JSON.stringify(p));
  let rows=(await c.query("select * from e10.official_customer_spend_contributions($1,'2026-01-01','2026-02-01','2026-02-01','USD') order by transaction_line_id",[x.org])).rows;
  const known=rows.find(r=>r.transaction_line_id===x.l1),finalized=rows.find(r=>r.transaction_line_id===x.l2);
  if(rows.length!==2||Number(known.official_net_merchandise)!==150||Number(known.official_shipping)!==20||Number(known.official_tax)!==10||Number(known.adjustment_count)!==1)throw Error('known official arithmetic failed '+JSON.stringify(known));
  if(Number(finalized.official_net_merchandise)!==80||Number(finalized.official_shipping)!==0||finalized.official_tax!==null||!finalized.merchandise_known||!finalized.shipping_known||finalized.tax_known)throw Error('finalization/unknown failed '+JSON.stringify(finalized));
  await c.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.view_customer_financials'",[x.org,x.role]);
  if((await c.query("select e10.can_view_any_customer_financials($1) ok",[x.org])).rows[0].ok)throw Error('missing financial cap allowed');
  if((await c.query("select e10.can_view_customer_financials_at($1,$2) ok",[x.org,x.foreignLocation])).rows[0].ok)throw Error('foreign location allowed');
  const acl=(await c.query("select has_function_privilege('authenticated','e10.can_view_customer_financials_at(uuid,uuid)','execute') auth_pred,has_function_privilege('anon','e10.can_view_any_customer_financials(uuid)','execute') anon_pred,has_function_privilege('authenticated','e10.official_customer_spend_contributions(uuid,timestamptz,timestamptz,timestamptz,text,uuid,text,uuid,text,uuid,uuid,uuid,uuid,text)','execute') auth_projection,has_function_privilege('anon','e10.official_customer_spend_contributions(uuid,timestamptz,timestamptz,timestamptz,text,uuid,text,uuid,text,uuid,uuid,uuid,uuid,text)','execute') anon_projection,has_table_privilege('authenticated','public.e10_location_financial_permission_decisions','select') auth_audit,has_function_privilege('anon','public.e10_org_set_location_financial_access(uuid,uuid,uuid,timestamptz,boolean,text,jsonb,text)','execute') anon_writer,has_function_privilege('authenticated','public.e10_org_set_location_financial_access(uuid,uuid,uuid,timestamptz,boolean,text,jsonb,text)','execute') auth_writer")).rows[0];
  if(acl.auth_pred||acl.anon_pred||acl.auth_projection||acl.anon_projection||acl.auth_audit||acl.anon_writer||!acl.auth_writer)throw Error('financial helper/writer ACL failed '+JSON.stringify(acl));
  const grant=(await c.query("select public.e10_org_set_location_financial_access($1,$2,$3,null,true,'fixture grant','{}',$4) r",[x.org,x.active,x.role,'grant-'+x.org])).rows[0].r;
  const replay=(await c.query("select public.e10_org_set_location_financial_access($1,$2,$3,null,true,'fixture grant','{}',$4) r",[x.org,x.active,x.role,'grant-'+x.org])).rows[0].r;
  if(grant.replay||!grant.updated_at||!replay.replay||grant.decision_id!==replay.decision_id||grant.updated_at!==replay.updated_at)throw Error('audited grant replay failed');
  if(!await denied(c.query("select public.e10_org_set_location_financial_access($1,$2,$3,null,false,'mismatch','{}',$4)",[x.org,x.active,x.role,'grant-'+x.org]),'22023','idempotency_key_mismatch'))throw Error('grant idempotency mismatch accepted');
  const disabled=(await c.query("select public.e10_org_set_location_financial_access($1,$2,$3,$4,false,'fixture disable','{}',$5) r",[x.org,x.active,x.role,grant.updated_at,'disable-'+x.org])).rows[0].r;
  if(disabled.allowed||disabled.previous_allowed!==true||!disabled.updated_at)throw Error('grant disable CAS failed '+JSON.stringify(disabled));
  if(!await denied(c.query("select public.e10_org_set_location_financial_access($1,$2,$3,$4,true,'stale','{}',$5)",[x.org,x.active,x.role,grant.updated_at,'stale-'+x.org]),'40001','location_financial_permission_revision_conflict'))throw Error('stale grant CAS accepted');
  const enabled=(await c.query("select public.e10_org_set_location_financial_access($1,$2,$3,$4,true,'fixture re-enable','{}',$5) r",[x.org,x.active,x.role,disabled.updated_at,'enable-'+x.org])).rows[0].r;
  if(!enabled.allowed||enabled.previous_allowed!==false)throw Error('grant re-enable CAS failed '+JSON.stringify(enabled));
  p=(await c.query("select e10.can_view_customer_financials_at($1,null) n,e10.can_view_customer_financials_at($1,$2) a,e10.can_view_customer_financials_at($1,$3) z",[x.org,x.active,x.archived])).rows[0];
  if(p.n||!p.a||p.z)throw Error('location-only authority failed '+JSON.stringify(p));
  rows=(await c.query("select * from e10.official_customer_spend_contributions($1,'2026-01-01','2026-02-01','2026-02-01','USD')",[x.org])).rows;
  if(rows.length!==1||rows[0].transaction_line_id!==x.l1)throw Error('location-only projection leaked '+JSON.stringify(rows));
  await c.query("update public.e10_locations set status='archived' where organization_id=$1 and id=$2",[x.org,x.active]);
  if((await c.query("select e10.can_view_customer_financials_at($1,$2) ok",[x.org,x.active])).rows[0].ok)throw Error('archived location-only grant remained active');
  const before=Number((await c.query("select revision from public.e10_reporting_dataset_revisions where organization_id=$1",[x.org])).rows[0].revision);
  await c.query("update public.e10_organization_memberships set status='suspended' where organization_id=$1 and user_id=$2",[x.org,x.user]);
  const after=Number((await c.query("select revision from public.e10_reporting_dataset_revisions where organization_id=$1",[x.org])).rows[0].revision);
  if(after<=before)throw Error('membership authority change did not invalidate reporting revision');
  ok=true;
 }finally{
  await c.query('reset role');await c.query('set session_replication_role=replica');
  for(const q of['delete from public.e10_location_financial_permission_decisions where organization_id in($1,$2)','delete from public.e10_customer_transaction_adjustments where organization_id in($1,$2)','delete from public.e10_customer_transaction_component_finalizations where organization_id in($1,$2)','delete from public.e10_customer_transaction_lines where organization_id in($1,$2)','delete from public.e10_customer_transactions where organization_id in($1,$2)','delete from public.e10_customer_transaction_draft_revisions where organization_id in($1,$2)','delete from public.e10_customer_transaction_drafts where organization_id in($1,$2)','delete from public.e10_location_role_permissions where organization_id in($1,$2)','delete from public.e10_locations where organization_id in($1,$2)','delete from public.e10_customers where organization_id in($1,$2)','delete from public.e10_organization_role_permissions where organization_id in($1,$2)','delete from public.e10_organization_memberships where organization_id in($1,$2)','delete from public.e10_organization_roles where organization_id in($1,$2)','delete from public.e10_reporting_dataset_revisions where organization_id in($1,$2)','delete from public.e10_organizations where id in($1,$2)'])await c.query(q,[x.org,x.org2]);
  await c.query('set session_replication_role=origin');await c.query('delete from auth.users where id=$1',[x.user]);
  const residue=Number((await c.query("select (select count(*) from public.e10_organizations where id in($1,$2))+(select count(*) from public.e10_location_financial_permission_decisions where organization_id in($1,$2))+(select count(*) from public.e10_customer_transaction_adjustments where organization_id in($1,$2))+(select count(*) from public.e10_customer_transaction_component_finalizations where organization_id in($1,$2))+(select count(*) from public.e10_customer_transaction_lines where organization_id in($1,$2))+(select count(*) from public.e10_customer_transactions where organization_id in($1,$2))+(select count(*) from public.e10_customer_transaction_draft_revisions where organization_id in($1,$2))+(select count(*) from public.e10_customer_transaction_drafts where organization_id in($1,$2))+(select count(*) from public.e10_location_role_permissions where organization_id in($1,$2))+(select count(*) from public.e10_locations where organization_id in($1,$2))+(select count(*) from public.e10_customers where organization_id in($1,$2))+(select count(*) from public.e10_organization_role_permissions where organization_id in($1,$2))+(select count(*) from public.e10_organization_memberships where organization_id in($1,$2))+(select count(*) from public.e10_organization_roles where organization_id in($1,$2))+(select count(*) from public.e10_reporting_dataset_revisions where organization_id in($1,$2))+(select count(*) from auth.users where id=$3) n",[x.org,x.org2,x.user])).rows[0].n);
  const sentinel=Number((await c.query("select count(*) n from public.e10_organizations where id='e1000000-0000-4000-8000-0000000000a6'")).rows[0].n);
  await c.end();if(residue||sentinel!==1)throw Error('X7b control cleanup '+JSON.stringify({residue,sentinel}));
 }
 if(ok)console.log('TA-X7b spend control: PASS');
}
main().catch(e=>{console.error(e.stack);process.exit(1)});
