const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const result=p=>p.then(value=>({ok:true,value}),error=>({ok:false,error}));
async function bounded(p,ms=8000){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(`TIMEOUT ${ms}ms`)),ms)})])}finally{clearTimeout(timer)}}
async function waitBlocked(obs,pid,blocker,label){const end=Date.now()+5000;while(Date.now()<end){const q=(await obs.query('select wait_event_type,$2=any(pg_blocking_pids($1)) exact from pg_stat_activity where pid=$1',[pid,blocker])).rows[0];if(q?.wait_event_type==='Lock'&&q.exact)return;await new Promise(r=>setTimeout(r,25))}throw Error(`${label}: backend ${pid} not blocked by ${blocker}`)}
async function actor(id){const c=new Client({connectionString:db});await c.connect();await c.query("set statement_timeout='8s';set lock_timeout='7s'");await c.query('select set_config($1,$2,false)',['request.jwt.claims',JSON.stringify({sub:id,role:'authenticated'})]);await c.query('set role authenticated');return c}
async function main(){const s=new Client({connectionString:db}),locker=new Client({connectionString:db}),obs=new Client({connectionString:db});await Promise.all([s.connect(),locker.connect(),obs.connect()]);for(const c of[s,locker,obs])await c.query("set statement_timeout='8s';set lock_timeout='7s'");const x={admin:randomUUID(),player:randomUUID(),team:randomUUID(),release:randomUUID(),variant:randomUUID(),run:randomUUID()};let a,b,pending=[];
 const affSql="select public.e10_platform_review_player_affiliation(null,$1,$2,'soccer','league-a','2020-01-01',null,0,'assert','official_source','official:race','race proof','{}',$3) r";
 const ctxSql="select public.e10_platform_review_variant_subject_context(null,$1,$2,0,'assert','known',$3,'documentary_source','image:race','race proof','{}',$4) r";
 try{
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.admin,x.admin+'@x.invalid']);await s.query('insert into public.e10_platform_admins(user_id)values($1)',[x.admin]);await s.query("insert into public.e10_players(id,name,sport)values($1,$2,'soccer')",[x.player,'X1b '+x.player]);await s.query("insert into public.e10_teams(id,name,sport,league)values($1,$2,'soccer','league-a')",[x.team,'X1b '+x.team]);await s.query("insert into public.e10_catalog_releases(id,release_name)values($1,'X1b race')",[x.release]);await s.query('insert into public.e10_catalog_variants(id,release_id)values($1,$2)',[x.variant,x.release]);await s.query('insert into public.e10_catalog_variant_subjects(variant_id,player_id)values($1,$2)',[x.variant,x.player]);[a,b]=await Promise.all([actor(x.admin),actor(x.admin)]);const ap=Number((await a.query('select pg_backend_pid() pid')).rows[0].pid),bp=Number((await b.query('select pg_backend_pid() pid')).rows[0].pid),lp=Number((await locker.query('select pg_backend_pid() pid')).rows[0].pid);
  const affKey=x.run+'-aff';await locker.query('begin');await locker.query("select pg_advisory_xact_lock(hashtextextended('player-affiliation-idempotency|'||$1,0))",[affKey]);const pa=result(a.query(affSql,[x.player,x.team,affKey])),pb=result(b.query(affSql,[x.player,x.team,affKey]));pending=[pa,pb];await Promise.all([waitBlocked(obs,ap,lp,'affiliation A'),waitBlocked(obs,bp,lp,'affiliation B')]);await locker.query('commit');const ar=await bounded(Promise.all([pa,pb]));pending=[];if(ar.some(z=>!z.ok))throw ar.find(z=>!z.ok).error;const areplay=ar.map(z=>z.value.rows[0].r.replay).sort();if(areplay[0]!==false||areplay[1]!==true)throw Error('affiliation expected one insert/one replay');console.log(`[proof] affiliation backends ${ap},${bp} queued on exact idempotency lock; one insert + one replay`);let mismatch=false;try{await a.query(affSql.replace("'race proof'","'changed'"),[x.player,x.team,affKey])}catch(e){mismatch=e.code==='22023'&&e.message==='idempotency_key_mismatch'}if(!mismatch)throw Error('affiliation changed-payload replay accepted');
  const ctxKey=x.run+'-ctx';await locker.query('begin');await locker.query("select pg_advisory_xact_lock(hashtextextended('variant-subject-context-idempotency|'||$1,0))",[ctxKey]);const pc=result(a.query(ctxSql,[x.variant,x.player,x.team,ctxKey])),pd=result(b.query(ctxSql,[x.variant,x.player,x.team,ctxKey]));pending=[pc,pd];await Promise.all([waitBlocked(obs,ap,lp,'context A'),waitBlocked(obs,bp,lp,'context B')]);await locker.query('commit');const cr=await bounded(Promise.all([pc,pd]));pending=[];if(cr.some(z=>!z.ok))throw cr.find(z=>!z.ok).error;const creplay=cr.map(z=>z.value.rows[0].r.replay).sort();if(creplay[0]!==false||creplay[1]!==true)throw Error('context expected one insert/one replay');console.log(`[proof] context backends ${ap},${bp} queued on exact idempotency lock; one insert + one replay`);mismatch=false;try{await a.query(ctxSql.replace("'race proof'","'changed'"),[x.variant,x.player,x.team,ctxKey])}catch(e){mismatch=e.code==='22023'&&e.message==='idempotency_key_mismatch'}if(!mismatch)throw Error('context changed-payload replay accepted');
  const deniedAff=x.run+'-denied-aff',affLock='player-affiliation|'+x.player+'|'+x.team+'|2025-01-01';await locker.query('begin');await locker.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[affLock]);const pe=result(a.query("select public.e10_platform_review_player_affiliation(null,$1,$2,'soccer','league-a','2025-01-01',null,0,'assert','manual_review','test','blocked','{}',$3)",[x.player,x.team,deniedAff]));pending=[pe];await waitBlocked(obs,ap,lp,'affiliation authority');await s.query('delete from public.e10_platform_admins where user_id=$1',[x.admin]);await locker.query('commit');const er=await bounded(pe);pending=[];if(er.ok||er.error.code!=='42501')throw Error('affiliation post-lock admin revocation not denied');if(Number((await s.query('select count(*) n from public.e10_player_affiliation_decisions where idempotency_key=$1',[deniedAff])).rows[0].n))throw Error('denied affiliation persisted');console.log('[proof] affiliation writer reread removed platform-admin after exact logical lock wait');
  await s.query('insert into public.e10_platform_admins(user_id)values($1)',[x.admin]);const current=(await s.query('select decision_key,revision from public.e10_catalog_variant_subject_context_decisions where idempotency_key=$1',[ctxKey])).rows[0],deniedCtx=x.run+'-denied-ctx',ctxLock='variant-subject-context|'+x.variant+'|'+x.player;await locker.query('begin');await locker.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[ctxLock]);const pf=result(a.query("select public.e10_platform_review_variant_subject_context($1,$2,$3,$4,'assert','known',$5,'documentary_source','image:race-2','blocked','{}',$6)",[current.decision_key,x.variant,x.player,current.revision,x.team,deniedCtx]));pending=[pf];await waitBlocked(obs,ap,lp,'context authority');await s.query('delete from public.e10_platform_admins where user_id=$1',[x.admin]);await locker.query('commit');const fr=await bounded(pf);pending=[];if(fr.ok||fr.error.code!=='42501')throw Error('context post-lock admin revocation not denied');if(Number((await s.query('select count(*) n from public.e10_catalog_variant_subject_context_decisions where idempotency_key=$1',[deniedCtx])).rows[0].n))throw Error('denied context persisted');console.log('[proof] context writer reread removed platform-admin after exact logical lock wait');
 }finally{
  await locker.query('rollback').catch(()=>{});if(pending.length)await Promise.allSettled(pending.map(p=>bounded(p).catch(()=>{})));for(const c of[a,b])if(c){await c.query('reset role').catch(()=>{});await c.end().catch(()=>{})}await s.query('set session_replication_role=replica');await s.query("delete from public.e10_catalog_variant_subject_context_decisions where idempotency_key like $1",[x.run+'%']);await s.query("delete from public.e10_player_affiliation_decisions where idempotency_key like $1",[x.run+'%']);await s.query('delete from public.e10_catalog_variant_subjects where variant_id=$1',[x.variant]);await s.query('delete from public.e10_catalog_variants where id=$1',[x.variant]);await s.query('delete from public.e10_catalog_releases where id=$1',[x.release]);await s.query('delete from public.e10_platform_admins where user_id=$1',[x.admin]);await s.query('delete from public.e10_players where id=$1',[x.player]);await s.query('delete from public.e10_teams where id=$1',[x.team]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=$1',[x.admin]);const residue=Number((await s.query("select (select count(*)from public.e10_player_affiliation_decisions where idempotency_key like $1)+(select count(*)from public.e10_catalog_variant_subject_context_decisions where idempotency_key like $1)+(select count(*)from auth.users where id=$2)n",[x.run+'%',x.admin])).rows[0].n);await Promise.all([s.end(),locker.end(),obs.end()]);if(residue)throw Error('cleanup residue '+residue);console.log('TA-X1b concurrent writers: PASS (fixture-free)')
 }}
main().catch(e=>{console.error(e.stack);process.exit(1)});
