const {Client}=require('pg');const {randomUUID,createHash}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const x={run:randomUUID(),org:randomUUID(),user:randomUUID(),role:randomUUID(),location:randomUUID(),supplier:randomUUID(),product:randomUUID(),config:randomUUID(),version:randomUUID()};
const values=()=>({supplier_id:x.supplier,destination_location_id:x.location,order_number:'X8B-'+x.run,currency:'CAD',expected_at:null,lines:[{line_no:1,configuration_version_id:x.version,ordered_quantity:2,estimated_unit_cost:10}]});
async function jwt(c){await c.query('select set_config($1,$2,false)',['request.jwt.claims',JSON.stringify({sub:x.user,role:'authenticated'})]);await c.query('set role authenticated')}
async function settled(p){try{return{ok:true,value:await p}}catch(error){return{ok:false,error}}}
async function blocked(observer,pid,label){for(let n=0;n<120;n++){const r=await observer.query("select count(*)::int n from pg_locks where pid=$1 and locktype='advisory'and not granted",[pid]);if(r.rows[0].n>0){console.log(`[proof] ${label}: backend ${pid} owns an ungranted advisory wait`);return}await new Promise(r=>setTimeout(r,25))}throw Error(`${label} did not establish advisory wait`)}
async function makeDraft(c,key){const d=(await c.query("select e10_org_create_action_draft($1,'purchase_order.create',$2,'{}','[]',$3)j",[x.org,values(),key])).rows[0].j.draft_id;await c.query('select e10_org_approve_action_draft($1,$2,1,$3)',[x.org,d,key+'-approve']);return d}
async function main(){const s=new Client({connectionString:db}),a=new Client({connectionString:db}),b=new Client({connectionString:db}),lock=new Client({connectionString:db}),observer=new Client({connectionString:db});await Promise.all([s.connect(),a.connect(),b.connect(),lock.connect(),observer.connect()]);let pending=[];
 try{
  for(const c of[s,a,b,lock,observer])await c.query("set statement_timeout='10s'");
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.user,`x8bc-${x.run}@x.invalid`]);
  await s.query("insert into e10_organizations(id,slug,name)values($1,$2,'X8b concurrency')",[x.org,'x8bc-'+x.run.slice(0,8)]);await s.query("insert into e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,'x8bc','X8b',false)",[x.role,x.org]);await s.query("insert into e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active')",[x.org,x.user,x.role]);await s.query("insert into e10_organization_role_permissions values($1,$2,'act.purchasing_prepare',true),($1,$2,'act.purchasing_approve',true)",[x.org,x.role]);
  await s.query("insert into e10_locations(id,organization_id,code,name,status)values($1,$2,'X8BC','X8b','active')",[x.location,x.org]);await s.query("insert into e10_location_role_permissions(organization_id,location_id,role_id,can_receive)values($1,$2,$3,true)",[x.org,x.location,x.role]);await s.query("insert into e10_suppliers(id,organization_id,code,name,status)values($1,$2,'X8BC','X8b','active')",[x.supplier,x.org]);await s.query("insert into e10_product_masters(id,organization_id,name)values($1,$2,'X8b')",[x.product,x.org]);await s.query("insert into e10_product_configurations(id,organization_id,product_master_id,name)values($1,$2,$3,'X8b')",[x.config,x.org,x.product]);await s.query("insert into e10_product_configuration_versions(id,organization_id,configuration_id,version_no,state,packaging_kind,base_unit,base_units_per_package)values($1,$2,$3,1,'active','unit','unit',1)",[x.version,x.org,x.config]);
  for(const c of[a,b])await jwt(c);

  const staleDraft=await makeDraft(a,'stale-'+x.run),commitKey='stale-commit-'+x.run,hash=createHash('sha256').update(commitKey).digest('hex'),down=`x8:purchase_order.create:${staleDraft}:1:${hash}`;
  await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[`${x.org}|purchase-order-command|${down}`]);
  const apid=(await a.query('select pg_backend_pid()pid')).rows[0].pid;const stale=settled(a.query('select e10_org_commit_action_draft($1,$2,1,$3)',[x.org,staleDraft,commitKey]));pending.push(stale);await blocked(observer,apid,'reference-change commit');
  await s.query("update e10_suppliers set status='inactive'where organization_id=$1 and id=$2",[x.org,x.supplier]);await lock.query('commit');const sr=await stale;if(sr.ok||sr.error.code!=='40001'||sr.error.message!=='action_references_stale')throw Error('post-wait reference change did not fail closed');
  const residue=(await s.query("select(select count(*)from e10_purchase_orders where organization_id=$1 and order_number=$2)po,(select count(*)from e10_action_draft_commands where organization_id=$1 and draft_id=$3 and command_type='commit')cmd,(select status from e10_action_drafts where organization_id=$1 and id=$3)status",[x.org,'X8B-'+x.run,staleDraft])).rows[0];if(Number(residue.po)||Number(residue.cmd)||residue.status!=='approved')throw Error('failed commit left partial state '+JSON.stringify(residue));console.log('[proof] post-wait reference change rejected with zero ordinary row, command, or X8 transition');await s.query("update e10_suppliers set status='active'where organization_id=$1 and id=$2",[x.org,x.supplier]);

  const raceDraft=await makeDraft(a,'race-'+x.run),raceKey='race-commit-'+x.run;const [ra,rb]=await Promise.all([a.query('select e10_org_commit_action_draft($1,$2,1,$3)j',[x.org,raceDraft,raceKey]),b.query('select e10_org_commit_action_draft($1,$2,1,$3)j',[x.org,raceDraft,raceKey])]);const results=[ra.rows[0].j,rb.rows[0].j];if(results.filter(r=>r.replay===false).length!==1||results.filter(r=>r.replay===true).length!==1)throw Error('competing commits did not yield one winner and replay');const counts=(await s.query("select(select count(*)from e10_purchase_orders where organization_id=$1 and order_number=$2)po,(select count(*)from e10_action_draft_commands where organization_id=$1 and draft_id=$3 and command_type='commit')cmd",[x.org,'X8B-'+x.run,raceDraft])).rows[0];if(Number(counts.po)!==1||Number(counts.cmd)!==1)throw Error('competing commits duplicated effect '+JSON.stringify(counts));console.log('[proof] competing exact commits produced one ordinary PO and one X8 command');
 }finally{
  await Promise.allSettled(pending);await lock.query('rollback').catch(()=>{});await s.query('reset role');await s.query('set session_replication_role=replica');for(const table of['e10_commercial_events','e10_purchase_order_commands','e10_purchase_order_revisions','e10_purchase_order_lines','e10_purchase_orders','e10_action_draft_commands','e10_action_draft_decisions','e10_action_draft_revisions','e10_action_drafts','e10_product_configuration_versions','e10_product_configurations','e10_product_masters','e10_suppliers','e10_location_role_permissions','e10_locations','e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles','e10_organizations'])await s.query(`delete from ${table} where organization_id=$1`,[x.org]).catch(async()=>{if(table==='e10_organizations')await s.query('delete from e10_organizations where id=$1',[x.org])});await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=$1',[x.user]);for(const c of[s,a,b,lock,observer])await c.end().catch(()=>{});
 }
 console.log('TA-X8b concurrency: PASS');
}
main().catch(e=>{console.error(e.stack);process.exit(1)});
