const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
async function denied(p,code,msg){try{await p;return false}catch(e){return e.code===code&&(!msg||e.message===msg)}}
async function main(){const s=new Client({connectionString:db}),a=new Client({connectionString:db}),h=new Client({connectionString:db});await Promise.all([s.connect(),a.connect(),h.connect()]);
 const org=randomUUID(),org2=randomUUID(),user=randomUUID(),hostile=randomUUID(),role=randomUUID(),role2=randomUUID(),loc=randomUUID(),loc2=randomUUID();let ok=false;
 try{
  await s.query("set statement_timeout='30s';set session_replication_role=replica");
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now()),($3,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$4,now(),now())",[user,`x7f-${user}@x.invalid`,hostile,`x7fh-${hostile}@x.invalid`]);
  await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7f'),($3,$4,'X7f hostile')",[org,'x7f-'+org.slice(0,8),org2,'x7fh-'+org2.slice(0,8)]);
  await s.query('insert into public.e10_reporting_dataset_revisions(organization_id)values($1),($2) on conflict do nothing',[org,org2]);
  await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,'reader','Reader',false),($3,$4,'hostile','Hostile',false)",[role,org,role2,org2]);
  await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active'),($4,$5,$6,'active')",[org,user,role,org2,hostile,role2]);
  await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_financials',true)",[org,role]);
  await s.query("insert into public.e10_locations(id,organization_id,name,status)values($1,$2,'X7f Store','active')",[loc,org]);
  await s.query("insert into public.e10_customers(id,organization_id,display_name)select gen_random_uuid(),$1,case when i=205 then null else 'Buyer '||lpad(i::text,3,'0')end from generate_series(1,205)i",[org]);
  await s.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id)select gen_random_uuid(),organization_id,id,'USD','2026-01-15','exact',gen_random_uuid(),1,gen_random_uuid()from public.e10_customers where organization_id=$1",[org]);
  await s.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,sales_channel,location_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence)select gen_random_uuid(),$1,t.id,1,'retail',case when row_number()over(order by t.customer_id)%2=0 then'web'else'store'end,$2,'manual',t.id::text,1,10,0,0,0,'{}'from public.e10_customer_transactions t where t.organization_id=$1",[org,loc]);
  const target=(await s.query("select customer_id from public.e10_customer_transactions where organization_id=$1 order by customer_id offset 150 limit 1",[org])).rows[0].customer_id;
  const targetTx=(await s.query('select id from public.e10_customer_transactions where organization_id=$1 and customer_id=$2',[org,target])).rows[0].id;
  await s.query("update public.e10_customer_transaction_lines l set merchandise_gross=999,merchandise_discount=0,sales_channel='web' where l.organization_id=$1 and l.transaction_id=(select id from public.e10_customer_transactions where organization_id=$1 and customer_id=$2)",[org,target]);
  await s.query("update public.e10_customer_transactions set occurred_at='2024-01-15' where organization_id=$1 and customer_id=(select customer_id from public.e10_customer_transactions where organization_id=$1 and customer_id<>$2 order by customer_id limit 1)",[org,target]);
  const unknown=(await s.query("select customer_id from public.e10_customer_transactions where organization_id=$1 and customer_id<>$2 order by customer_id desc limit 1",[org,target])).rows[0].customer_id;await s.query("update public.e10_customer_transaction_lines l set merchandise_discount=null where l.organization_id=$1 and l.transaction_id=(select id from public.e10_customer_transactions where organization_id=$1 and customer_id=$2)",[org,unknown]);
  const colliding=(await s.query("select id from public.e10_customers where organization_id=$1 and id<>all($2::uuid[]) order by id offset 98 limit 3",[org,[target,unknown]])).rows.map(r=>r.id);await s.query("update public.e10_customers set display_name=case id when $2 then 'Case Name' when $3 then 'case name' when $4 then 'Case Name' end where organization_id=$1 and id=any($5::uuid[])",[org,...colliding,colliding]);await s.query("update public.e10_customers set display_name='Restored eligible name'where organization_id=$1 and display_name is null",[org]);const nullCustomer=(await s.query("select t.customer_id from public.e10_customer_transactions t where t.organization_id=$1 and t.occurred_at>='2026-01-01'and t.customer_id<>all($2::uuid[])order by t.customer_id limit 1",[org,[target,unknown,...colliding]])).rows[0].customer_id;await s.query('update public.e10_customers set display_name=null where organization_id=$1 and id=$2',[org,nullCustomer]);
  const targetLine=(await s.query('select id from public.e10_customer_transaction_lines where organization_id=$1 and transaction_id=$2',[org,targetTx])).rows[0].id;await s.query("insert into public.e10_customer_transaction_adjustments(id,organization_id,transaction_id,transaction_line_id,adjustment_kind,effect,currency,merchandise_amount,commercial_event_id,occurred_at,occurred_at_precision,reason,source_event_id,source_component_id,idempotency_key,request_fingerprint)values(gen_random_uuid(),$1,$2,$3,'refund','decrease','USD',50,gen_random_uuid(),'2026-01-20','exact','X7f refund','x7f-refund','merchandise','x7f-refund-key','x7f-refund-fp')",[org,targetTx,targetLine]);await s.query("insert into public.e10_customer_transaction_source_claims(organization_id,source_kind,source_connection_id,source_line_id,posted_line_id)values($1,'manual','x7f-a','same-sale',$2),($1,'import','x7f-b','same-sale',$2)",[org,targetLine]);
  const crossing=(await s.query("select t.id,l.id line_id from public.e10_customer_transactions t join public.e10_customer_transaction_lines l on(l.organization_id,l.transaction_id)=(t.organization_id,t.id) where t.organization_id=$1 and t.customer_id<>all($2::uuid[]) and t.occurred_at>='2026-01-01' order by t.customer_id limit 1",[org,[target,unknown]])).rows[0];await s.query("insert into public.e10_customer_transaction_adjustments(id,organization_id,transaction_id,transaction_line_id,adjustment_kind,effect,currency,merchandise_amount,commercial_event_id,occurred_at,occurred_at_precision,reason,source_event_id,source_component_id,idempotency_key,request_fingerprint)values(gen_random_uuid(),$1,$2,$3,'refund','decrease','USD',6,gen_random_uuid(),'2026-01-20','exact','X7f crossing refund','x7f-cross-refund','merchandise','x7f-cross-refund-key','x7f-cross-refund-fp')",[org,crossing.id,crossing.line_id]);
  const cadTx=randomUUID();await s.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id)values($1,$2,$3,'CAD','2026-01-16','exact',gen_random_uuid(),1,gen_random_uuid())",[cadTx,org,target]);await s.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,sales_channel,location_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence)values(gen_random_uuid(),$1,$2,1,'retail','web',$3,'manual','cad-line',1,77,0,0,0,'{}')",[org,cadTx,loc]);
  const unknownTimeTx=randomUUID();await s.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id)values($1,$2,$3,'USD',null,'unknown',gen_random_uuid(),1,gen_random_uuid())",[unknownTimeTx,org,target]);await s.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,sales_channel,location_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence)values(gen_random_uuid(),$1,$2,1,'retail','web',$3,'manual','unknown-time',1,5,0,0,0,'{}')",[org,unknownTimeTx,loc]);
  for(const [q,id]of[[a,user],[h,hostile]]){await q.query("select set_config('request.jwt.claims',jsonb_build_object('sub',$1::text,'role','authenticated')::text,false)",[id]);await q.query('set role authenticated')}
  const x8ctx=(await a.query("select public.e10_org_create_query_context($1,'workspace',600,$2)r",[org,'x7f-'+org])).rows[0].r.context_id;
  const call=(extra={})=>a.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>$2,p_from=>$3,p_to=>'2026-02-01',p_observation_cutoff=>$12,p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1,p_channel=>$4,p_min_known_official_subtotal=>$5,p_max_known_official_subtotal=>$6,p_sort=>$7,p_limit=>$8,p_cursor=>$9,p_expected_dataset_revision=>$10,p_expected_query_fingerprint=>$11)j",[org,extra.mode||'bounded',extra.mode==='known_history'?null:'2026-01-01',extra.channel??null,extra.min??null,extra.max??null,extra.sort||'customer_id_asc',extra.limit||100,extra.cursor||null,extra.rev||null,extra.fp||null,extra.cutoff||'2026-02-01']);
  let first=(await call()).rows[0].j;if(first.items.length!==100||Number(first.full_cohort_totals.customer_count)!==204||!first.has_more)throw Error('full cohort page one failed '+JSON.stringify(first.full_cohort_totals));const baselineTotals=first.full_cohort_totals;
  let ids=[...first.items.map(x=>x.effective_customer_id)],p=first;while(p.has_more){p=(await call({cursor:p.next_cursor,rev:p.dataset_revision,fp:p.query_fingerprint})).rows[0].j;if(JSON.stringify(p.full_cohort_totals)!==JSON.stringify(baselineTotals))throw Error('page totals drifted');ids.push(...p.items.map(x=>x.effective_customer_id))}if(ids.length!==204||new Set(ids).size!==204||ids.slice(0,100).includes(target))throw Error('cursor traversal failed');
  for(const sort of['display_name_asc','known_official_subtotal_asc','known_official_subtotal_desc']){const pageLimit=sort==='display_name_asc'?1:37;let q=(await call({sort,limit:pageLimit})).rows[0].j,seen=[];for(;;){if(JSON.stringify(q.full_cohort_totals)!==JSON.stringify(baselineTotals))throw Error(sort+' page totals drifted');seen.push(...q.items.map(v=>v.effective_customer_id));if(!q.has_more)break;q=(await call({sort,limit:pageLimit,cursor:q.next_cursor,rev:q.dataset_revision,fp:q.query_fingerprint})).rows[0].j}if(seen.length!==204||new Set(seen).size!==204||sort==='display_name_asc'&&seen.at(-1)!==nullCustomer)throw Error(sort+' traversal failed');const adjusted="coalesce(l.merchandise_net,0)+coalesce((select sum(case a.effect when 'increase' then a.merchandise_amount else -a.merchandise_amount end)from public.e10_customer_transaction_adjustments a where(a.organization_id,a.transaction_line_id)=(l.organization_id,l.id)),0)";const order=sort==='display_name_asc'?'lower(c.display_name)collate"C",c.display_name collate"C",c.id':sort==='known_official_subtotal_asc'?adjusted+',c.id':adjusted+' desc,c.id';const expected=(await s.query(`select c.id from public.e10_customers c join public.e10_customer_transactions t on(t.organization_id,t.customer_id)=(c.organization_id,c.id)join public.e10_customer_transaction_lines l on(l.organization_id,l.transaction_id)=(t.organization_id,t.id)where c.organization_id=$1 and t.currency='USD'and t.occurred_at>='2026-01-01'order by ${order}`,[org])).rows.map(r=>r.id);if(JSON.stringify(seen)!==JSON.stringify(expected))throw Error(sort+' ordering mismatch')}
  const nameFirst=(await call({sort:'display_name_asc',limit:1})).rows[0].j;const forged={...nameFirst.next_cursor,display_name:'zzzz',normalized_display_name:'zzzz',known_official_subtotal:'-999'};const forgedPage=(await call({sort:'display_name_asc',limit:1,cursor:forged,rev:nameFirst.dataset_revision,fp:nameFirst.query_fingerprint})).rows[0].j;const honestPage=(await call({sort:'display_name_asc',limit:1,cursor:nameFirst.next_cursor,rev:nameFirst.dataset_revision,fp:nameFirst.query_fingerprint})).rows[0].j;if(JSON.stringify(forgedPage.items)!==JSON.stringify(honestPage.items))throw Error('forged name cursor tuple steered page');
  const filtered=(await call({channel:'web',min:900,max:1000,sort:'known_official_subtotal_desc'})).rows[0].j;if(filtered.items.length!==1||filtered.items[0].effective_customer_id!==target||Number(filtered.full_cohort_totals.known_official_subtotal)!==949||Number(filtered.items[0].line_count)!==1)throw Error('filter/refund/dedup failed '+JSON.stringify(filtered));const cad=(await a.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'bounded',p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'CAD',p_timezone=>'UTC',p_week_start=>1,p_customer=>$2,p_limit=>1)j",[org,target])).rows[0].j;if(Number(cad.full_cohort_totals.known_official_subtotal)!==77||Number(cad.full_cohort_totals.line_count)!==1)throw Error('currency isolation failed '+JSON.stringify(cad));
  const unknownGrid=(await call({min:0,max:0})).rows[0].j;const unknownRow=unknownGrid.items.find(v=>v.effective_customer_id===unknown);if(!unknownRow||Number(unknownRow.known_official_subtotal)!==0||unknownRow.complete_official_total!==null||Number(unknownRow.unknown_merchandise_count)!==1)throw Error('unknown-only customer was coerced '+JSON.stringify(unknownGrid));const empty=(await call({min:10000})).rows[0].j;if(empty.items.length||Number(empty.full_cohort_totals.customer_count)!==0||Number(empty.full_cohort_totals.known_official_subtotal)!==0)throw Error('empty cohort totals failed '+JSON.stringify(empty));
  if(!await denied(call({cursor:first.next_cursor,rev:first.dataset_revision,fp:first.query_fingerprint,channel:'web'}),'22023','customer_spend_grid_cursor_query_mismatch')||!await denied(call({cursor:first.next_cursor,rev:first.dataset_revision,fp:first.query_fingerprint,sort:'display_name_asc'}),'22023','customer_spend_grid_cursor_query_mismatch')||!await denied(call({cursor:first.next_cursor,rev:first.dataset_revision,fp:first.query_fingerprint,cutoff:'2026-02-02'}),'22023','customer_spend_grid_cursor_query_mismatch'))throw Error('cursor rebound to filter/sort/cutoff');if(!await denied(call({cursor:{bad:true},rev:first.dataset_revision,fp:first.query_fingerprint}),'22023','customer_spend_grid_cursor_invalid'))throw Error('malformed cursor accepted');
  if(!await denied(a.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>null,p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1)",[org]),'22023','customer_spend_grid_bounds_invalid'))throw Error('null window mode accepted');
  const selected=(await a.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'bounded',p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1,p_customer=>$2,p_location=>$3,p_limit=>10)j",[org,target,loc])).rows[0].j;if(selected.authorized_data_diagnostics.scope!=='selected_effective_customer'||Number(selected.authorized_data_diagnostics.unknown_occurrence_line_count)!==1)throw Error('selected diagnostics scope failed '+JSON.stringify(selected.authorized_data_diagnostics));
  await s.query("insert into public.e10_locations(id,organization_id,name,status)values($1,$2,'X7f Unauthorized Store','active')",[loc2,org]);const hiddenKnownTx=randomUUID(),hiddenUnknownTx=randomUUID();await s.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id)values($1,$2,$3,'USD','2026-01-22','exact',gen_random_uuid(),1,gen_random_uuid()),($4,$2,$3,'USD',null,'unknown',gen_random_uuid(),1,gen_random_uuid())",[hiddenKnownTx,org,target,hiddenUnknownTx]);await s.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,sales_channel,location_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence)values(gen_random_uuid(),$1,$2,1,'retail','web',$4,'manual','hidden-known',1,123,0,0,0,'{}'),(gen_random_uuid(),$1,$3,1,'retail','web',$4,'manual','hidden-unknown',1,7,0,0,0,'{}')",[org,hiddenKnownTx,hiddenUnknownTx,loc2]);
  await s.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.view_customer_financials'",[org,role]);await s.query("insert into public.e10_location_role_permissions(organization_id,location_id,role_id,can_view_customer_financials)values($1,$2,$3,true)",[org,loc,role]);const locationOnly=(await call()).rows[0].j;if(locationOnly.authorization_scope!=='authorized_locations'||JSON.stringify(locationOnly.full_cohort_totals)!==JSON.stringify(baselineTotals))throw Error('unauthorized location changed totals '+JSON.stringify(locationOnly));const locationSelected=(await a.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'bounded',p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1,p_customer=>$2,p_limit=>10)j",[org,target])).rows[0].j;if(Number(locationSelected.authorized_data_diagnostics.unknown_occurrence_line_count)!==1||Number(locationSelected.items[0].known_official_subtotal)!==949||Number(locationSelected.items[0].line_count)!==1)throw Error('unauthorized location leaked into customer diagnostics '+JSON.stringify(locationSelected));if(!await denied(a.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'bounded',p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1,p_location=>$2,p_limit=>10)",[org,loc2]),'42501','customer_spend_location_denied'))throw Error('unauthorized location accepted');if(!await denied(call({cursor:first.next_cursor,rev:first.dataset_revision,fp:first.query_fingerprint}),'22023','customer_spend_grid_cursor_query_mismatch'))throw Error('authorization scope cursor rebound');await s.query('delete from public.e10_location_role_permissions where organization_id=$1 and location_id=$2 and role_id=$3',[org,loc,role]);await s.query('delete from public.e10_customer_transaction_lines where organization_id=$1 and transaction_id=any($2::uuid[])',[org,[hiddenKnownTx,hiddenUnknownTx]]);await s.query('delete from public.e10_customer_transactions where organization_id=$1 and id=any($2::uuid[])',[org,[hiddenKnownTx,hiddenUnknownTx]]);await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_financials',true)",[org,role]);
  await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_engagement',true)",[org,role]);
  const life=(await call({mode:'known_history',min:900,max:1000})).rows[0].j;if(life.items[0].effective_customer_id!==target||life.items[0].attended_ratio_status!=='unsupported_known_history_window'||life.coverage.source_history_completeness!=='unknown')throw Error('known history failed '+JSON.stringify(life));
  const lifeAll=(await call({mode:'known_history'})).rows[0].j;if(Number(lifeAll.full_cohort_totals.customer_count)!==205)throw Error('known history omitted old row '+JSON.stringify(lifeAll.full_cohort_totals));
  const x8=(await a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)j",[org,x8ctx,{window_mode:'known_history',from:null,to:'2026-02-01T00:00:00Z',observation_cutoff:'2026-02-01T00:00:00Z',currency:'USD',timezone:'UTC',week_start:1,min_known_official_subtotal:'900',max_known_official_subtotal:'1000',sort:'display_name_asc',limit:1}])).rows[0].j;if(x8.result.items.length!==1||'display_name'in x8.result.items[0]||x8.result.next_cursor&&('display_name'in x8.result.next_cursor||'normalized_display_name'in x8.result.next_cursor))throw Error('X8 v2 projection leaked name '+JSON.stringify(x8));
  const x8page=(await a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)j",[org,x8ctx,{window_mode:'bounded',from:'2026-01-01T00:00:00Z',to:'2026-02-01T00:00:00Z',observation_cutoff:'2026-02-01T00:00:00Z',currency:'USD',timezone:'UTC',week_start:1,sort:'display_name_asc',limit:1,cursor:null}])).rows[0].j;if(!x8page.result.next_cursor||'display_name'in x8page.result.next_cursor)throw Error('X8 redacted cursor missing');const x8next=(await a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)j",[org,x8ctx,{window_mode:'bounded',from:'2026-01-01T00:00:00Z',to:'2026-02-01T00:00:00Z',observation_cutoff:'2026-02-01T00:00:00Z',currency:'USD',timezone:'UTC',week_start:1,sort:'display_name_asc',limit:1,cursor:x8page.result.next_cursor,expected_dataset_revision:x8page.result.dataset_revision,expected_query_fingerprint:x8page.result.query_fingerprint}])).rows[0].j;if(!x8next.result.items.length||'display_name'in x8next.result.items[0])throw Error('X8 redacted cursor continuation failed');
  if(!await denied(a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)",[org,x8ctx,{window_mode:'known_history',from:null,to:'2026-02-01',observation_cutoff:'2026-02-01',currency:'USD',timezone:'UTC',week_start:1,limit:1,after_customer_id:target}]),'22023','x8_query_args_invalid'))throw Error('mixed v1/v2 cursor accepted');
  await s.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,sales_channel,location_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence)select gen_random_uuid(),$1,$2,i,'retail','web',$3,'manual','bulk-'||i,1,1,0,0,0,'{}'from generate_series(2,100001)i",[org,targetTx,loc]);
  const resourceSql="select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'known_history',p_from=>null,p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1,p_customer=>$2,p_limit=>1)j";
  if(!await denied(a.query(resourceSql,[org,target]),'54000','customer_spend_known_history_resource_limit'))throw Error('100001 resource ceiling did not fail closed');
  await s.query('delete from public.e10_customer_transaction_lines where organization_id=$1 and transaction_id=$2 and line_no=100001',[org,targetTx]);const atCap=(await a.query(resourceSql,[org,target])).rows[0].j;if(Number(atCap.full_cohort_totals.line_count)!==100000)throw Error('100000 resource ceiling success failed '+JSON.stringify(atCap.full_cohort_totals));
  const renamePage=(await call({sort:'display_name_asc',limit:1})).rows[0].j;await s.query('set session_replication_role=origin');await s.query("update public.e10_customers set display_name='Renamed customer'where organization_id=$1 and id=$2",[org,target]);await s.query('set session_replication_role=replica');if(!await denied(call({sort:'display_name_asc',limit:1,cursor:renamePage.next_cursor,rev:renamePage.dataset_revision,fp:renamePage.query_fingerprint}),'40001','customer_spend_revision_stale'))throw Error('rename did not invalidate cursor');
  if(!await denied(h.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'bounded',p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1)",[org]),'42501','customer_spend_denied'))throw Error('hostile member allowed');
  ok=true;
 }finally{for(const q of[a,h]){await q.query('reset role').catch(()=>{})}await s.query('set session_replication_role=replica');for(const t of['e10_query_context_commands','e10_query_contexts','e10_customer_transaction_source_claims','e10_customer_transaction_adjustments','e10_customer_transaction_lines','e10_location_role_permissions','e10_customer_transactions','e10_reporting_dataset_revisions','e10_locations','e10_customers','e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles'])await s.query(`delete from public.${t} where organization_id in($1,$2)`,[org,org2]);await s.query('delete from public.e10_organizations where id in($1,$2)',[org,org2]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id in($1,$2)',[user,hostile]);await Promise.all([s.end(),a.end(),h.end()])}
 if(ok)console.log('TA-X7f customer spend grid: PASS');
}main().catch(e=>{console.error(e);process.exit(1)});
