\set ON_ERROR_STOP on
do $$declare n int;begin
 select count(*)into n from pg_class c join pg_namespace s on s.oid=c.relnamespace where s.nspname='public'and c.relname in('e10_catalog_facet_term_keys','e10_catalog_facet_taxonomy_terms','e10_catalog_facet_taxonomy_aliases','e10_catalog_variant_facet_decisions','e10_org_catalog_variant_facet_overrides')and c.relrowsecurity;if n<>5 then raise exception'RLS count %',n;end if;
 if exists(select 1 from information_schema.role_table_grants where table_schema='public'and table_name in('e10_catalog_facet_term_keys','e10_catalog_facet_taxonomy_terms','e10_catalog_facet_taxonomy_aliases','e10_catalog_variant_facet_decisions','e10_org_catalog_variant_facet_overrides')and grantee in('anon','authenticated'))then raise exception'client grant leak';end if;
end $$;
begin;
do $$declare o uuid;r uuid;v uuid;k uuid;k2 uuid;t1 uuid;t2 uuid;p uuid;p2 uuid;dk uuid:=gen_random_uuid();d1 uuid;d2 uuid;sid uuid;ok uuid:=gen_random_uuid();ov1 uuid;begin
 insert into public.e10_organizations(name,slug)values('X7d','x7d-'||substr(gen_random_uuid()::text,1,8))returning id into o;
 insert into public.e10_catalog_releases(release_name)values('X7d')returning id into r;insert into public.e10_catalog_variants(release_id)values(r)returning id into v;
 insert into public.e10_players(name)values('X7d subject')returning id into p;insert into public.e10_players(name)values('Other subject')returning id into p2;insert into public.e10_catalog_variant_subjects(variant_id,player_id)values(v,p);
 insert into public.e10_catalog_facet_term_keys(namespace)values('color_family')returning id into k;
 insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(k,'color_family','Blue',1,'assert','fixture','{}','term1','fp')returning id into t1;
 insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,supersedes_term_id,reason,evidence,idempotency_key,request_fingerprint)values(k,'color_family','Blue',2,'revoke',t1,'fixture','{}','term2','fp')returning id into t2;
 if exists(select 1 from public.e10_current_catalog_facet_taxonomy_terms where term_key=k and action='assert')then raise exception'revoked term current';end if;
 begin insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(k,'finish_family','bad',3,'assert','x','{}','bad-ns','fp');raise exception'namespace accepted';exception when check_violation then null;end;
 begin insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,subject_id,facet_key,revision,action,integer_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,p,'rookie_season',1,'assert',null,'x','{}','bad-null','fp');raise exception'null season accepted';exception when check_violation then null;end;
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,subject_id,facet_key,revision,action,integer_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,p,'rookie_season',1,'assert',2025,'x','{}','season-ok','fp');
 begin insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,subject_id,facet_key,revision,action,integer_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,p2,'rookie_season',1,'assert',2025,'x','{}','foreign-subject','fp');raise exception'foreign subject accepted';exception when check_violation then null;end;
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,boolean_value,reason,evidence,idempotency_key,request_fingerprint)values(dk,v,'rookie_designation',1,'assert',true,'x','{}','d1','fp')returning id into d1;
 begin insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,boolean_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,'rookie_designation',1,'assert',false,'x','{}','duplicate-root','fp');raise exception'duplicate logical root accepted';exception when unique_violation then null;end;
 sid:=gen_random_uuid();begin insert into public.e10_catalog_variant_facet_decisions(id,decision_key,variant_id,facet_key,revision,action,boolean_value,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(sid,gen_random_uuid(),v,'rookie_designation',99,'assert',false,sid,'x','{}','self','fp');raise exception'self successor accepted';exception when check_violation then null;end;
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(dk,v,'rookie_designation',2,'revoke',d1,'x','{}','d2','fp')returning id into d2;
 if(select count(*)from public.e10_current_catalog_variant_facets where decision_key=dk)<>1 then raise exception'global terminal count';end if;
 begin insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,boolean_value,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,'rookie_designation',3,'assert',false,d2,'x','{}','bad-key','fp');raise exception'foreign chain accepted';exception when check_violation then null;end;
 insert into public.e10_catalog_facet_term_keys(namespace)values('finish_family')returning id into k2;insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(k2,'finish_family','Refractor',1,'assert','x','{}','finish','fp');
 begin insert into public.e10_catalog_facet_taxonomy_aliases(alias_key,namespace,alias,term_key,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),'color_family','blueish',k2,1,'assert','x','{}','alias-wrong-ns','fp');raise exception'wrong namespace alias accepted';exception when check_violation then null;end;
 insert into public.e10_catalog_facet_taxonomy_aliases(alias_key,namespace,alias,term_key,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),'finish_family','Chrome',k2,1,'assert','x','{}','alias-ok','fp');
 begin insert into public.e10_catalog_facet_taxonomy_aliases(alias_key,namespace,alias,term_key,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),'finish_family',' chrome ',k2,1,'assert','x','{}','alias-dup','fp');raise exception'duplicate alias accepted';exception when unique_violation then null;end;
 sid:=gen_random_uuid();begin insert into public.e10_catalog_facet_taxonomy_aliases(id,alias_key,namespace,alias,term_key,revision,action,supersedes_alias_id,reason,evidence,idempotency_key,request_fingerprint)values(sid,gen_random_uuid(),'finish_family','self',k2,99,'assert',sid,'x','{}','alias-self','fp');raise exception'alias self accepted';exception when check_violation then null;end;
 begin insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,term_key,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,'color_family',1,'assert',k,'x','{}','revoked-term','fp');raise exception'revoked term accepted';exception when check_violation then null;end;
 insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,facet_key,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(o,ok,v,'rookie_designation',1,'mask','x','{}','ov1','fp')returning id into ov1;
 insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,facet_key,revision,action,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,ok,v,'rookie_designation',2,'clear',ov1,'x','{}','ov2','fp');
 if not exists(select 1 from public.e10_current_org_catalog_variant_facet_overrides where organization_id=o and decision_key=ok and action='clear')then raise exception'clear missing';end if;
 begin delete from public.e10_catalog_variant_facet_decisions where id=d2;raise exception'delete accepted';exception when sqlstate'55000'then null;end;
end $$;
rollback;
select'TA-X7d.0 facet governance PASS'as result;
