\set ON_ERROR_STOP on
begin;
do $$
declare o uuid:='e1000000-0000-4000-8000-0000000000a6'; u uuid:=gen_random_uuid(); role_id uuid:=gen_random_uuid(); product uuid:=gen_random_uuid(); b1 uuid; b2 uuid; b3 uuid; other_batch uuid; row1 uuid; row2 uuid; row3 uuid; old_obs uuid; result jsonb; revision bigint; stale_revision bigint; classes jsonb;
begin
 insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at) values(u,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','x5g@x.invalid',now(),now());
 insert into public.e10_organization_roles(id,organization_id,key,name,is_system) values(role_id,o,'x5g','X5g',false); insert into public.e10_organization_role_permissions values(o,role_id,'act.manage_intake',true); insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values(o,u,role_id,'active'); insert into public.e10_product_masters(id,organization_id,name) values(product,o,'X5g Product'); perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 result:=public.e10_org_stage_intake(o,'manual',null,'manual sheet',null,'manual-v1',jsonb_build_array(jsonb_build_object('raw_payload','{"v":10}'::jsonb,'observation_kind','estimated_value','occurred_at','2025-01-01T00:00:00Z','currency','CAD','amount',10)),'x5g-stage-1'); b1:=(result->>'batch_id')::uuid; select id into row1 from public.e10_intake_rows where batch_id=b1; perform public.e10_org_resolve_intake_row(o,row1,'match_product',product,'reviewed',null,'x5g-resolve-1'); perform public.e10_org_commit_intake(o,b1,(public.e10_org_intake_review_state(o,b1)->>'review_revision')::bigint,'x5g-commit-1'); select id into old_obs from public.e10_market_observations where intake_row_id=row1;
 begin perform public.e10_org_stage_corrected_intake(o,gen_random_uuid(),'manual',null,'manual sheet',null,'manual-v2','[]','x5g-cross'); raise exception 'foreign predecessor accepted'; exception when insufficient_privilege then null; end;
 result:=public.e10_org_stage_corrected_intake(o,b1,'manual',null,'manual sheet corrected',null,'manual-v2',jsonb_build_array(jsonb_build_object('raw_payload','{"v":12}'::jsonb,'observation_kind','estimated_value','occurred_at','2025-01-02T00:00:00Z','currency','CAD','amount',12)),'x5g-stage-2'); b2:=(result->>'batch_id')::uuid; if (result->>'supersedes_batch_id')::uuid<>b1 then raise exception 'explicit predecessor missing'; end if;
 select id into row2 from public.e10_intake_rows where batch_id=b2; perform public.e10_org_resolve_intake_row(o,row2,'match_product',product,'reviewed source-less correction',null,'x5g-resolve-2'); revision:=(public.e10_org_intake_review_state(o,b2)->>'review_revision')::bigint; classes:=jsonb_build_array(jsonb_build_object('source_row_number',1,'classification','replacement','superseded_observation_id',old_obs,'reason','manual corrected sheet'));
 result:=public.e10_org_commit_corrected_intake(o,b2,revision,classes,'x5g-corrected'); if not (result->>'corrected')::boolean then raise exception 'corrected commit marker missing'; end if;
 if (select count(*) from public.e10_current_market_observations where product_master_id=product)<>1 or (select amount from public.e10_current_market_observations where product_master_id=product)<>12 then raise exception 'source-less eligible interpretation wrong'; end if;
 result:=public.e10_org_stage_corrected_intake(o,b1,'manual',null,'manual sheet corrected',null,'manual-v2',jsonb_build_array(jsonb_build_object('raw_payload','{"v":12}'::jsonb,'observation_kind','estimated_value','occurred_at','2025-01-02T00:00:00Z','currency','CAD','amount',12)),'x5g-stage-2'); if not (result->>'replay')::boolean or (result->>'supersedes_batch_id')::uuid<>b1 then raise exception 'committed corrected-stage replay failed'; end if;
 result:=public.e10_org_stage_intake(o,'manual',null,'other predecessor',null,'other-v1',jsonb_build_array(jsonb_build_object('raw_payload','{"v":20}'::jsonb,'observation_kind','estimated_value','occurred_at','2025-02-01T00:00:00Z','currency','CAD','amount',20)),'x5g-other-stage'); other_batch:=(result->>'batch_id')::uuid; select id into row3 from public.e10_intake_rows where batch_id=other_batch; perform public.e10_org_resolve_intake_row(o,row3,'match_product',product,'other',null,'x5g-other-resolve'); perform public.e10_org_commit_intake(o,other_batch,(public.e10_org_intake_review_state(o,other_batch)->>'review_revision')::bigint,'x5g-other-commit');
 begin perform public.e10_org_stage_corrected_intake(o,other_batch,'manual',null,'manual sheet',null,'manual-v1',jsonb_build_array(jsonb_build_object('raw_payload','{"v":10}'::jsonb,'observation_kind','estimated_value','occurred_at','2025-01-01T00:00:00Z','currency','CAD','amount',10)),'x5g-stage-1'); raise exception 'committed ordinary batch relabeled'; exception when sqlstate '55000' then null; end;
 if (select supersedes_intake_batch_id from public.e10_intake_batches where id=b1) is not null then raise exception 'committed ordinary lineage mutated'; end if;
 result:=public.e10_org_stage_intake(o,'manual',null,'convert staged',null,'convert-v1',jsonb_build_array(jsonb_build_object('raw_payload','{"v":30}'::jsonb,'observation_kind','estimated_value','occurred_at','2025-03-01T00:00:00Z','currency','CAD','amount',30)),'x5g-convert-stage'); b3:=(result->>'batch_id')::uuid; select id into row3 from public.e10_intake_rows where batch_id=b3; perform public.e10_org_resolve_intake_row(o,row3,'match_product',product,'previewed ordinary',null,'x5g-convert-resolve'); stale_revision:=(public.e10_org_intake_review_state(o,b3)->>'review_revision')::bigint;
 perform public.e10_org_stage_corrected_intake(o,b1,'manual',null,'convert staged',null,'convert-v1',jsonb_build_array(jsonb_build_object('raw_payload','{"v":30}'::jsonb,'observation_kind','estimated_value','occurred_at','2025-03-01T00:00:00Z','currency','CAD','amount',30)),'x5g-convert-stage');
 if (public.e10_org_intake_review_state(o,b3)->>'review_revision')::bigint<>stale_revision+1 then raise exception 'correction intent did not invalidate preview'; end if;
 begin perform public.e10_org_commit_corrected_intake(o,b3,stale_revision,jsonb_build_array(jsonb_build_object('source_row_number',1,'classification','new','reason','reviewed','duplicate_reviewed',true)),'x5g-stale'); raise exception 'stale preview committed'; exception when sqlstate '40001' then null; end;
 raise notice 'TA-X5g explicit source-less correction: PASS';
end $$;
rollback;
