const {Client}=require('pg');const{randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const x={org:randomUUID(),org2:randomUUID(),u:randomUUID(),u2:randomUUID(),role:randomUUID(),role2:randomUUID(),customer:randomUUID(),session:randomUUID(),stream:randomUUID(),segment:randomUUID(),policy:randomUUID(),coverage:randomUUID(),join:randomUUID(),leave:randomUUID()};
const bounded=p=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(Error('TA-X7c concurrency timeout')),8000))]);
const guarded=p=>{p.catch(()=>{});return p};
async function waitLock(s,pid,blocker,kind){for(let i=0;i<80;i++){const q=await s.query("select a.wait_event_type,a.wait_event,a.query,$2=any(pg_blocking_pids(a.pid)) intended_blocker,exists(select 1 from pg_locks l where l.pid=a.pid and not l.granted and l.locktype='advisory') advisory_wait,exists(select 1 from pg_locks l where l.pid=$2 and l.relation='public.e10_reporting_dataset_revisions'::regclass) blocker_revision_relation from pg_stat_activity a where a.pid=$1",[pid,blocker]);const v=q.rows[0];if(v?.wait_event_type==='Lock'&&v.intended_blocker&&((kind==='advisory'&&v.advisory_wait)||(kind==='revision'&&v.blocker_revision_relation)))return v;await new Promise(r=>setTimeout(r,50));}throw Error(`backend ${pid} did not establish intended ${kind} lock wait behind ${blocker}`)}
async function denied(p,code){try{await p;return false}catch(e){return e.code===code}}
async function jwt(c,u){await c.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:u,role:'authenticated'})]);await c.query('set role authenticated')}
async function main(){const s=new Client({connectionString:db}),a=new Client({connectionString:db}),b=new Client({connectionString:db}),c=new Client({connectionString:db}),r=new Client({connectionString:db}),h=new Client({connectionString:db});await Promise.all([s.connect(),a.connect(),b.connect(),c.connect(),r.connect(),h.connect()]);let ok=false,pb=null,pc=null,pendingRead=null,correctionRun=null,bp=null,cp=null,rp=null,bpid=null;const apid=(await a.query('select pg_backend_pid() pid')).rows[0].pid;
try{
 await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now()),($3,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$4,now(),now())",[x.u,`${x.u}@x.invalid`,x.u2,`${x.u2}@x.invalid`]);
 await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7c race'),($3,$4,'X7c hostile')",[x.org,`x7cr-${x.org.slice(0,8)}`,x.org2,`x7ch-${x.org2.slice(0,8)}`]);
 await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,'reader','Reader',false),($3,$4,'hostile','Hostile',false)",[x.role,x.org,x.role2,x.org2]);
 await s.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability)values($1,$2,'act.view_customer_engagement'),($3,$4,'act.view_customer_engagement')",[x.org,x.role,x.org2,x.role2]);
 await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active'),($4,$5,$6,'active')",[x.org,x.u,x.role,x.org2,x.u2,x.role2]);
 await s.query("insert into public.e10_customers(id,organization_id,display_name)values($1,$2,'Race customer')",[x.customer,x.org]);
 await s.query("insert into public.e10_break_sessions(id,organization_id,streamer_uid,name,status,visibility,created_at,ended_at)values($1,$2,$3,'Race','ended','private','2026-01-01','2026-01-31')",[x.session,x.org,x.u]);
 await s.query("insert into public.e10_presence_collection_policies(organization_id,policy_version,source_class,provider_key,enabled,notice_version,heartbeat_expiry_seconds,min_event_interval_ms,max_events_per_minute,retention_interval,coverage_label,effective_from)values($1,1,'authorized_platform','whatnot',true,'n1',300,0,60,interval '365 days','fixture','2026-01-01')",[x.org]);
 await s.query("insert into public.e10_provider_presence_normalization_policy_decisions(id,organization_id,provider_key,revision,action,effective_from,effective_through,heartbeat_expiry,maximum_late_arrival,collection_policy_version,reason,evidence,idempotency_key,request_fingerprint)values($1,$2,'whatnot',1,'enable','2026-01-01','2027-01-01',interval '5 minutes',interval '1 day',1,'fixture','{}','race-policy','race-policy-fp')",[x.policy,x.org]);
 await s.query("insert into public.e10_attendance_coverage_assertions(id,organization_id,coverage_key,revision,action,source_class,provider_key,covered_from,covered_to,coverage_status,policy_version,review_basis,evidence,idempotency_key,request_fingerprint)values($1,$2,$1,1,'assert','authorized_platform','whatnot','2026-01-01','2026-02-03','complete',1,'fixture','{}','race-coverage','race-coverage-fp')",[x.coverage,x.org]);
 await s.query("insert into public.e10_presence_policy_state_history(organization_id,source_class,provider_key,policy_version,enabled,state_from)values($1,'authorized_platform','whatnot',1,true,'2026-01-01')",[x.org]);
 await s.query("insert into public.e10_session_presence_streams(id,organization_id,session_id,source_class,provider_key,subject_key,connection_id,platform_attendee_key,original_customer_id,identity_status,collection_policy_version,notice_version,coverage_label,retention_expires_at)values($1,$2,$3,'authorized_platform','whatnot','race-attendee','race-connection','race-attendee',$4,'reviewed_attributed',1,'n1','fixture','2027-01-01')",[x.stream,x.org,x.session,x.customer]);
 await s.query("insert into public.e10_session_presence_segments(id,organization_id,stream_id,segment_sequence,heartbeat_expiry_seconds,retention_expires_at,collection_policy_version,notice_version,coverage_label)values($1,$2,$3,1,300,'2027-01-01',1,'n1','fixture')",[x.segment,x.org,x.stream]);
 await s.query("insert into public.e10_session_presence_events(id,organization_id,stream_id,segment_id,event_sequence,event_kind,provider_occurred_at,server_received_at,provider_event_id,provider_key,evidence,request_fingerprint)values($1,$2,$3,$4,1,'join','2026-01-02 10:00Z','2026-01-02 10:00:01Z','race-join','whatnot','{}','race-join-fp'),($5,$2,$3,$4,2,'leave','2026-01-02 10:01Z','2026-01-02 10:01:01Z','race-leave','whatnot','{}','race-leave-fp')",[x.join,x.org,x.stream,x.segment,x.leave]);
 const call="select public.e10_service_run_provider_presence_normalization($1,'whatnot',$2,'2026-01-01','2026-02-01','2026-02-01',100,'race-identical') r";
 await a.query('begin');await a.query("select pg_advisory_xact_lock(hashtextextended($1::text||'|provider-normalization-idem|'||'race-identical',0))",[x.org]);
 bp=(await b.query('select pg_backend_pid() pid')).rows[0].pid;cp=(await c.query('select pg_backend_pid() pid')).rows[0].pid;pb=guarded(b.query(call,[x.org,x.policy]));pc=guarded(c.query(call,[x.org,x.policy]));await Promise.all([waitLock(s,bp,apid,'advisory'),waitLock(s,cp,apid,'advisory')]);await a.query('commit');const both=await bounded(Promise.all([pb,pc]));pb=pc=null;
 const results=both.map(v=>v.rows[0].r);if(results.filter(v=>v.replay===false).length!==1||results.filter(v=>v.replay===true).length!==1||results[0].run_id!==results[1].run_id)throw Error('identical concurrent runners did not converge');
 await jwt(r,x.u);await jwt(h,x.u2);const detail="select * from public.e10_org_provider_attendance_intervals($1,'whatnot',$2,$3,'2026-01-01','2026-02-01','2026-02-01',10,null,null,null,null)";
 if(!await denied(h.query(detail,[x.org,x.session,x.customer]),'42501')||!await denied(h.query("select * from public.e10_org_provider_attendance_quarantine($1,'whatnot','2026-01-01','2026-02-01','2026-02-01',null,10,null,null,null)",[x.org]),'42501')||!await denied(h.query("select * from public.e10_org_source_attendance_summary($1,'whatnot',$2,$3,'2026-01-01','2026-02-01','2026-02-01')",[x.org,x.session,x.customer]),'42501'))throw Error('foreign-org member RPC allowed');
 await a.query('begin');await a.query('select revision from public.e10_reporting_dataset_revisions where organization_id=$1 for update',[x.org]);rp=(await r.query('select pg_backend_pid() pid')).rows[0].pid;pendingRead=guarded(r.query(detail,[x.org,x.session,x.customer]));await waitLock(s,rp,apid,'revision');await s.query('set session_replication_role=replica');await s.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.view_customer_engagement'",[x.org,x.role]);await s.query('set session_replication_role=origin');await a.query('commit');if(!await bounded(denied(pendingRead,'42501')))throw Error('reader authority revocation lost while blocked');pendingRead=null;
 await s.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability)values($1,$2,'act.view_customer_engagement')",[x.org,x.role]);
 await a.query('begin');await a.query('select revision from public.e10_reporting_dataset_revisions where organization_id=$1 for update',[x.org]);bpid=(await b.query('select pg_backend_pid() pid')).rows[0].pid;correctionRun=guarded(b.query("select public.e10_service_run_provider_presence_normalization($1,'whatnot',$2,'2026-01-01','2026-02-01','2026-02-02',100,'race-correction') r",[x.org,x.policy]));await waitLock(s,bpid,apid,'revision');
 await s.query('set session_replication_role=replica');await s.query("insert into public.e10_session_presence_events(id,organization_id,stream_id,segment_id,event_sequence,event_kind,provider_occurred_at,server_received_at,provider_event_id,provider_key,corrects_event_id,evidence,request_fingerprint)values($1,$2,$3,$4,3,'join','2026-01-02 10:00Z','2026-01-03','race-join-correction','whatnot',$5,'{}','race-correction-fp')",[randomUUID(),x.org,x.stream,x.segment,x.join]);await s.query('set session_replication_role=origin');await a.query('commit');if(!await bounded(denied(correctionRun,'40001')))throw Error('runner accepted dependency mutation while blocked');correctionRun=null;ok=true;
}finally{await a.query('rollback').catch(()=>{});for(const [pid,p]of[[bp,pb],[cp,pc],[rp,pendingRead],[bpid,correctionRun]])if(pid&&p)await s.query('select pg_cancel_backend($1)',[pid]).catch(()=>{});await bounded(Promise.allSettled([pb,pc,pendingRead,correctionRun].filter(Boolean)));for(const q of[a,b,c,r,h])await q.query('reset role').catch(()=>{});await s.query('set session_replication_role=replica');for(const org of[x.org,x.org2])for(const t of['e10_provider_presence_normalized_intervals','e10_provider_presence_quarantine_rows','e10_provider_presence_normalization_runs','e10_attendance_coverage_assertions','e10_session_presence_events','e10_session_presence_segments','e10_session_presence_streams','e10_provider_presence_normalization_policy_decisions','e10_presence_policy_state_history','e10_presence_collection_policies','e10_break_sessions','e10_customers','e10_reporting_dataset_revisions','e10_organization_memberships','e10_organization_role_permissions','e10_organization_roles'])await s.query(`delete from public.${t} where organization_id=$1`,[org]);await s.query('delete from public.e10_organizations where id=any($1)',[[x.org,x.org2]]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=any($1)',[[x.u,x.u2]]);const residue=Number((await s.query("select (select count(*)from public.e10_organizations where id=any($1))+(select count(*)from auth.users where id=any($2))+(select count(*)from public.e10_provider_presence_normalization_runs where organization_id=any($1))+(select count(*)from public.e10_session_presence_events where organization_id=any($1)) n",[[x.org,x.org2],[x.u,x.u2]])).rows[0].n),sentinel=Number((await s.query("select count(*)n from public.e10_organizations where id='e1000000-0000-4000-8000-0000000000a6'")).rows[0].n);await Promise.all([s.end(),a.end(),b.end(),c.end(),r.end(),h.end()]);if(residue||sentinel!==1)throw Error(`cleanup/sentinel failed ${JSON.stringify({residue,sentinel})}`);}
 if(ok)console.log('TA-X7c provider normalization concurrency: PASS');}
main().catch(e=>{console.error(e.stack);process.exit(1)});
