\set ON_ERROR_STOP on

do $$declare n integer;begin
 select count(*)into n from pg_class c join pg_namespace s on s.oid=c.relnamespace
 where s.nspname='public'and c.relname in('e10_unique_item_grade_assessments','e10_catalog_population_snapshots','e10_valuation_evidence','e10_inventory_disposition_links','e10_inventory_reporting_revisions')and c.relrowsecurity;
 if n<>5 then raise exception'X7e evidence RLS count %',n;end if;
 if exists(select 1 from information_schema.role_table_grants where table_schema='public'and table_name in('e10_unique_item_grade_assessments','e10_catalog_population_snapshots','e10_valuation_evidence','e10_inventory_disposition_links','e10_inventory_reporting_revisions')and grantee in('anon','authenticated'))then raise exception'X7e evidence client table grant';end if;
 if has_function_privilege('anon','public.e10_org_review_inventory_evidence(uuid,text,uuid,bigint,text,jsonb,text,text)','execute')then raise exception'X7e writer anon executable';end if;
 select count(distinct c.relname)into n from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace s on s.oid=c.relnamespace
 where not t.tgisinternal and s.nspname='public'and t.tgfoid='e10.bump_inventory_reporting_revision()'::regprocedure
  and c.relname=any(array['e10_commercial_events','e10_unique_items','e10_inventory_items','e10_inventory_lots','e10_lot_cost_evidence','e10_stock_receipts','e10_stock_receipt_lines','e10_stock_receipt_reversals','e10_customer_transactions','e10_customer_transaction_lines','e10_customer_transaction_adjustments','e10_customer_transaction_component_finalizations','e10_customer_transaction_attribution_decisions','e10_market_observations','e10_market_observation_supersessions','e10_market_observation_fact_decisions','e10_market_observation_equivalence_decisions','e10_unique_item_grade_assessments','e10_catalog_population_snapshots','e10_valuation_evidence','e10_inventory_disposition_links']);
 if n<>21 then raise exception'X7e invalidator trigger census %',n;end if;
end $$;

begin;
do $$
declare o uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();u uuid:=gen_random_uuid();user_id uuid:=gen_random_uuid();role_id uuid:=gen_random_uuid();release_id uuid:=gen_random_uuid();variant_id uuid:=gen_random_uuid();item_id uuid:=gen_random_uuid();origin_id uuid:=gen_random_uuid();sale_obs uuid:=gen_random_uuid();r jsonb;k uuid;rev0 bigint;rev1 bigint;
begin
 insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values(user_id,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','x7e-'||user_id||'@x.invalid',now(),now());
 insert into public.e10_organizations(id,slug,name)values(o,'x7e-'||substr(o::text,1,8),'X7e'),(o2,'x7f-'||substr(o2::text,1,8),'X7e hostile');
 insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values(role_id,o,'x7e','X7e',false);
 insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values(o,user_id,role_id,'active');
 insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed)values(o,role_id,'act.curate_market_analytics',true),(o,role_id,'act.view_market_analytics',true);
 insert into public.e10_catalog_releases(id,release_name)values(release_id,'X7e release');
 insert into public.e10_catalog_variants(id,release_id,card_number)values(variant_id,release_id,'1');
 insert into public.e10_unique_items(id,organization_id,catalog_variant_id,item_kind)values(item_id,o,variant_id,'card');
 insert into public.e10_commercial_events(id,organization_id,event_type,event_schema_version,subject_type,subject_id,occurred_at,occurred_at_precision,idempotency_key,source_kind,evidence_quality,payload,created_by)
 values(origin_id,o,'acquisition',1,'unique_item',item_id::text,'2026-01-01 00:00Z','exact','x7e-origin','manual','operator_asserted',jsonb_build_object('acquisition_id','x7e-origin'),user_id);
 set local session_replication_role=replica;
 insert into public.e10_market_observations(id,organization_id,observation_kind,unique_item_id,occurred_at,currency,amount,quantity,source_kind,source_reference,raw_payload_snapshot)
 values(sale_obs,o,'completed_sale',item_id,'2026-01-09 00:00Z','USD',150,1,'manual','shop-sale','{}');
 set local session_replication_role=origin;
 select revision into rev0 from public.e10_inventory_reporting_revisions where organization_id=o;

 perform set_config('request.jwt.claims',jsonb_build_object('sub',user_id,'role','authenticated')::text,true);set local role authenticated;
 r:=public.e10_org_review_inventory_evidence(o,'grade_assessment',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','grade_label','9','assessed_at','2026-01-02T00:00:00Z','assessed_at_precision','exact','source_kind','manual','method','certificate','method_version','1','review_status','reviewed','evidence',jsonb_build_object('certificate','x7e')),'initial grade',' grade-key ');
 if r->>'replay'<>'false'or r->>'revision'<>'1'then raise exception'grade write result %',r;end if;k:=(r->>'evidence_key')::uuid;
 r:=public.e10_org_review_inventory_evidence(o,'grade_assessment',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','grade_label','9','assessed_at','2026-01-02T00:00:00Z','assessed_at_precision','exact','source_kind','manual','method','certificate','method_version','1','review_status','reviewed','evidence',jsonb_build_object('certificate','x7e')),'initial grade',' grade-key ');
 if r->>'replay'<>'true'or(r->>'evidence_key')::uuid<>k then raise exception'grade replay unstable %',r;end if;
 perform public.e10_org_review_inventory_evidence(o,'grade_assessment',k,1,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','grade_label','10','assessed_at','2026-01-03T00:00:00Z','assessed_at_precision','exact','source_kind','manual','method','certificate','method_version','1','review_status','reviewed','evidence',jsonb_build_object('certificate','x7e-regrade')),'regrade','grade-key-successor');
 perform public.e10_org_review_inventory_evidence(o,'population_snapshot',null,0,'assert',jsonb_build_object('catalog_variant_id',variant_id,'condition_state','graded','grader_code','PSA','grade_label','9','population_count',23,'population_scope','grader_total','observed_at','2026-01-03T00:00:00Z','observed_at_precision','exact','source_kind','manual','method','provider-snapshot','method_version','1','review_status','reviewed','evidence','{}'::jsonb),'population','population-key');
 perform public.e10_org_review_inventory_evidence(o,'valuation_evidence',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','grade_label','9','method','manual-index','method_version','1','currency','USD','amount',125,'observed_at','2026-01-04T00:00:00Z','observed_at_precision','exact','source_kind','manual','review_status','reviewed','input_evidence',jsonb_build_object('basis','local')),'estimate','valuation-key');
 perform public.e10_org_review_inventory_evidence(o,'disposition_link',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'origin_event_id',origin_id,'disposition_kind','sale','disposed_at','2026-01-09T00:00:00Z','disposed_at_precision','exact','market_observation_id',sale_obs,'evidence',jsonb_build_object('local_shop_sale',true)),'reviewed local sale','disposition-key');
 r:=public.e10_org_unique_item_evidence(o,item_id,'2026-01-10',100,null);
 if not exists(select 1 from jsonb_array_elements(r->'items')x where x->>'kind'='grade'and x#>>'{data,grade_label}'='9'and x#>>'{data,current}'='false'and x#>>'{data,applicability_status}'='superseded_or_ineligible')or not exists(select 1 from jsonb_array_elements(r->'items')x where x->>'kind'='grade'and x#>>'{data,grade_label}'='10'and x#>>'{data,applicability_status}'='applicable')then raise exception'evidence applicability history invalid %',r;end if;
 begin perform public.e10_org_review_inventory_evidence(o,null,null,0,'assert','{}','invalid','missing-kind');raise exception'null kind accepted';exception when invalid_parameter_value then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'grade_assessment',null,0,null,'{}','invalid','missing-action');raise exception'null action accepted';exception when invalid_parameter_value then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'grade_assessment',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'assessed_at','2026-01-02T00:00:00Z','assessed_at_precision','exact','source_kind','manual','method','certificate','method_version','1','review_status','reviewed'),'invalid','grade-missing-condition');raise exception'missing grade condition accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'grade_assessment',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grade_label','9','assessed_at','2026-01-02T00:00:00Z','assessed_at_precision','exact','source_kind','manual','method','certificate','method_version','1','review_status','reviewed'),'invalid','grade-missing-grader');raise exception'missing grade grader accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'grade_assessment',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','assessed_at','2026-01-02T00:00:00Z','assessed_at_precision','exact','source_kind','manual','method','certificate','method_version','1','review_status','reviewed'),'invalid','grade-missing-label');raise exception'missing grade label accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'population_snapshot',null,0,'assert',jsonb_build_object('catalog_variant_id',variant_id,'condition_state','graded','grader_code','PSA','grade_label','9','population_scope','grader_total','observed_at','2026-01-03T00:00:00Z','observed_at_precision','exact','source_kind','manual','method','provider-snapshot','method_version','1','review_status','reviewed'),'invalid','population-missing-count');raise exception'missing population count accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'population_snapshot',null,0,'assert',jsonb_build_object('catalog_variant_id',variant_id,'condition_state','graded','grader_code','PSA','grade_label','9','population_count',1,'observed_at','2026-01-03T00:00:00Z','observed_at_precision','exact','source_kind','manual','method','provider-snapshot','method_version','1','review_status','reviewed'),'invalid','population-missing-scope');raise exception'missing population scope accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'population_snapshot',null,0,'assert',jsonb_build_object('catalog_variant_id',variant_id,'condition_state','graded','grade_label','9','population_count',1,'population_scope','grader_total','observed_at','2026-01-03T00:00:00Z','observed_at_precision','exact','source_kind','manual','method','provider-snapshot','method_version','1','review_status','reviewed'),'invalid','population-missing-grader');raise exception'missing population grader accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'population_snapshot',null,0,'assert',jsonb_build_object('catalog_variant_id',variant_id,'condition_state','graded','grader_code','PSA','population_count',1,'population_scope','grader_total','observed_at','2026-01-03T00:00:00Z','observed_at_precision','exact','source_kind','manual','method','provider-snapshot','method_version','1','review_status','reviewed'),'invalid','population-missing-label');raise exception'missing population label accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'valuation_evidence',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','grade_label','9','method','manual-index','method_version','1','amount',1,'observed_at','2026-01-04T00:00:00Z','observed_at_precision','exact','source_kind','manual','review_status','reviewed'),'invalid','valuation-missing-currency');raise exception'missing valuation currency accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'valuation_evidence',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','grade_label','9','method','manual-index','method_version','1','currency','USD','observed_at','2026-01-04T00:00:00Z','observed_at_precision','exact','source_kind','manual','review_status','reviewed'),'invalid','valuation-missing-amount');raise exception'missing valuation amount accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'valuation_evidence',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grade_label','9','method','manual-index','method_version','1','currency','USD','amount',1,'observed_at','2026-01-04T00:00:00Z','observed_at_precision','exact','source_kind','manual','review_status','reviewed'),'invalid','valuation-missing-grader');raise exception'missing valuation grader accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'valuation_evidence',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'condition_state','graded','grader_code','PSA','method','manual-index','method_version','1','currency','USD','amount',1,'observed_at','2026-01-04T00:00:00Z','observed_at_precision','exact','source_kind','manual','review_status','reviewed'),'invalid','valuation-missing-label');raise exception'missing valuation label accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'disposition_link',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'origin_event_id',origin_id,'disposed_at','2026-01-09T00:00:00Z','disposed_at_precision','exact','market_observation_id',sale_obs),'invalid','disposition-missing-kind');raise exception'missing disposition kind accepted';exception when check_violation then null;end;
 begin perform public.e10_org_review_inventory_evidence(o,'disposition_link',null,0,'assert',jsonb_build_object('unique_item_id',item_id,'origin_event_id',origin_id,'disposition_kind','sale','disposed_at','2026-01-09T00:00:00Z','disposed_at_precision','exact','market_observation_id',sale_obs),'duplicate root','disposition-second-root');raise exception'second disposition root accepted';exception when unique_violation then null;end;
 reset role;

 if(select count(*)from public.e10_current_unique_item_grade_assessments where organization_id=o)<>1 or(select count(*)from public.e10_current_catalog_population_snapshots where organization_id=o)<>1 or(select count(*)from public.e10_current_valuation_evidence where organization_id=o)<>1 or(select count(*)from public.e10_current_inventory_disposition_links where organization_id=o)<>1 then raise exception'X7e current evidence projection wrong';end if;
 select revision into rev1 from public.e10_inventory_reporting_revisions where organization_id=o;if rev1<=rev0 then raise exception'X7e revision did not advance';end if;
 begin update public.e10_valuation_evidence set amount=999 where organization_id=o;raise exception'append-only update accepted';exception when object_not_in_prerequisite_state then null;end;
 set local role authenticated;
 begin perform public.e10_org_review_inventory_evidence(o2,'valuation_evidence',null,0,'assert','{}','cross org','foreign');raise exception'hostile org accepted';exception when insufficient_privilege then null;end;
 reset role;
end $$;
rollback;
select'TA-X7e.0 governed inventory evidence PASS'as result;
