const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
async function bounded(p,ms=8000){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(`TIMEOUT ${ms}ms`)),ms)})])}finally{clearTimeout(timer)}}
const result=p=>p.then(value=>({ok:true,value}),error=>({ok:false,error}));
async function waitBlocked(obs,pid,blocker){const end=Date.now()+5000;while(Date.now()<end){const q=(await obs.query("select wait_event_type,$2=any(pg_blocking_pids($1)) exact from pg_stat_activity where pid=$1",[pid,blocker])).rows[0];if(q?.wait_event_type==='Lock'&&q.exact)return;await new Promise(r=>setTimeout(r,25))}throw Error(`backend ${pid} not blocked by ${blocker}`)}
async function actor(id){const c=new Client({connectionString:db});await c.connect();await c.query("set statement_timeout='8s';set lock_timeout='7s'");await c.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,role:'authenticated'})]);await c.query('set role authenticated');return c}
async function main(){const s=new Client({connectionString:db}),locker=new Client({connectionString:db}),obs=new Client({connectionString:db});await Promise.all([s.connect(),locker.connect(),obs.connect()]);for(const c of[s,locker,obs])await c.query("set statement_timeout='8s';set lock_timeout='7s'");const x={org:randomUUID(),pa:randomUUID(),u:randomUUID(),role:randomUUID(),release:randomUUID(),variant:randomUUID(),run:randomUUID()};let p,a,pending,ok=false;
 const expectDenied=async(r,msg)=>{const z=await bounded(r);if(z.ok||z.error?.code!=='42501'||z.error.message!==msg)throw Error(`expected ${msg}, got ${z.ok?'success':z.error?.code+':'+z.error?.message}`)};
 try{
  if(await (async()=>{const z=await result(Promise.resolve('success'));return !z.ok})())throw Error('result wrapper false positive');
  for(const id of[x.pa,x.u])await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[id,id+'@x.invalid']);
  await s.query('insert into public.e10_platform_admins(user_id)values($1)',[x.pa]);await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7d race')",[x.org,'x7dr-'+x.run.slice(0,8)]);await s.query("insert into public.e10_organization_roles(organization_id,id,key,name)values($1,$2,$3,'r')",[x.org,x.role,x.run]);await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active')",[x.org,x.u,x.role]);await s.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed)values($1,$2,'act.curate_market_analytics',true)",[x.org,x.role]);await s.query("insert into public.e10_catalog_releases(id,release_name)values($1,'X7d')",[x.release]);await s.query('insert into public.e10_catalog_variants(id,release_id)values($1,$2)',[x.variant,x.release]);[p,a]=await Promise.all([actor(x.pa),actor(x.u)]);
  const ppid=Number((await p.query('select pg_backend_pid() pid')).rows[0].pid),apid=Number((await a.query('select pg_backend_pid() pid')).rows[0].pid),lpid=Number((await locker.query('select pg_backend_pid() pid')).rows[0].pid);

  let g0=Number((await s.query('select revision from public.e10_market_catalog_revision where singleton')).rows[0].revision);await locker.query('begin');await locker.query('select revision from public.e10_market_catalog_revision where singleton for update');pending=result(p.query("select public.e10_platform_review_catalog_facet_term(null,0,'color_family','Blue','assert','race','{}',$1)",[x.run+'-platform-revision']));await waitBlocked(obs,ppid,lpid);await s.query('delete from public.e10_platform_admins where user_id=$1',[x.pa]);await locker.query('commit');await expectDenied(pending,'platform_catalog_curation_denied');pending=null;if(Number((await s.query('select revision from public.e10_market_catalog_revision where singleton')).rows[0].revision)!==g0)throw Error('denied platform writer advanced revision');if(Number((await s.query("select count(*) n from public.e10_catalog_facet_taxonomy_terms where idempotency_key=$1",[x.run+'-platform-revision'])).rows[0].n))throw Error('denied platform writer inserted');console.log(`[proof] platform backend ${ppid} waited on revision lock held by ${lpid}, reread revoked authority`);

  let o0=Number((await s.query('select revision from public.e10_market_org_revisions where organization_id=$1',[x.org])).rows[0].revision);const lockText=x.org+'|market-facet|'+x.variant+'||rookie_designation';await locker.query('begin');await locker.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[lockText]);pending=result(a.query("select public.e10_org_review_catalog_variant_facet_override($1,null,$2,null,'rookie_designation',0,'mask',null,null,null,'race','{}',$3)",[x.org,x.variant,x.run+'-org-advisory']));await waitBlocked(obs,apid,lpid);await s.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.curate_market_analytics'",[x.org,x.role]);await locker.query('commit');await expectDenied(pending,'market_facet_curation_denied');pending=null;if(Number((await s.query('select revision from public.e10_market_org_revisions where organization_id=$1',[x.org])).rows[0].revision)!==o0)throw Error('advisory-denied writer advanced revision');console.log(`[proof] org backend ${apid} waited on exact advisory lock held by ${lpid}, reread revoked capability`);

  await s.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed)values($1,$2,'act.curate_market_analytics',true)",[x.org,x.role]);o0=Number((await s.query('select revision from public.e10_market_org_revisions where organization_id=$1',[x.org])).rows[0].revision);await locker.query('begin');await locker.query('select revision from public.e10_market_org_revisions where organization_id=$1 for update',[x.org]);pending=result(a.query("select public.e10_org_review_catalog_variant_facet_override($1,null,$2,null,'rookie_designation',0,'mask',null,null,null,'race','{}',$3)",[x.org,x.variant,x.run+'-org-revision']));await waitBlocked(obs,apid,lpid);await s.query("update public.e10_organization_memberships set status='suspended' where organization_id=$1 and user_id=$2",[x.org,x.u]);await locker.query('commit');await expectDenied(pending,'market_facet_curation_denied');pending=null;if(Number((await s.query('select revision from public.e10_market_org_revisions where organization_id=$1',[x.org])).rows[0].revision)!==o0)throw Error('revision-denied writer advanced revision');if(Number((await s.query('select count(*) n from public.e10_org_catalog_variant_facet_overrides where organization_id=$1',[x.org])).rows[0].n))throw Error('denied org writer inserted');console.log(`[proof] org backend ${apid} waited on org revision lock held by ${lpid}, reread suspended membership`);ok=true;
 }finally{
  await locker.query('rollback').catch(()=>{});if(pending)await Promise.allSettled([bounded(pending).catch(()=>{})]);for(const c of[p,a])if(c){await c.query('rollback').catch(()=>{});await c.query('reset role').catch(()=>{});await c.end().catch(()=>{})}
  await s.query('set session_replication_role=replica');await s.query("delete from public.e10_org_catalog_variant_facet_overrides where organization_id=$1 or idempotency_key like $2",[x.org,x.run+'%']);await s.query("delete from public.e10_catalog_facet_taxonomy_aliases where idempotency_key like $1",[x.run+'%']);await s.query("delete from public.e10_catalog_variant_facet_decisions where idempotency_key like $1",[x.run+'%']);const keys=(await s.query("select distinct term_key from public.e10_catalog_facet_taxonomy_terms where idempotency_key like $1",[x.run+'%'])).rows.map(r=>r.term_key);await s.query("delete from public.e10_catalog_facet_taxonomy_terms where idempotency_key like $1",[x.run+'%']);for(const k of keys)await s.query('delete from public.e10_catalog_facet_term_keys where id=$1',[k]);for(const t of['e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles','e10_market_org_revisions'])await s.query(`delete from public.${t} where organization_id=$1`,[x.org]);await s.query('delete from public.e10_catalog_variants where id=$1',[x.variant]);await s.query('delete from public.e10_catalog_releases where id=$1',[x.release]);await s.query('delete from public.e10_platform_admins where user_id=$1',[x.pa]);await s.query('delete from public.e10_organizations where id=$1',[x.org]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=any($1)',[[x.pa,x.u]]);const residue=Number((await s.query("select (select count(*)from public.e10_organizations where id=$1)+(select count(*)from public.e10_catalog_facet_taxonomy_terms where idempotency_key like $2)n",[x.org,x.run+'%'])).rows[0].n);await Promise.all([s.end(),locker.end(),obs.end()]);if(residue)throw Error('concurrency cleanup residue')
 }
 if(ok)console.log('TA-X7d.0 post-wait authority: PASS')
}
main().catch(e=>{console.error(e.stack);process.exit(1)});
