\set ON_ERROR_STOP on
begin;
do $$
declare o uuid:=gen_random_uuid();creator uuid:=gen_random_uuid();purchasing uuid:=gen_random_uuid();global_reader uuid:=gen_random_uuid();location_reader uuid:=gen_random_uuid();contact_reader uuid:=gen_random_uuid();creator_role uuid:=gen_random_uuid();purchasing_role uuid:=gen_random_uuid();global_role uuid:=gen_random_uuid();location_role uuid:=gen_random_uuid();contact_role uuid:=gen_random_uuid();loc_a uuid:=gen_random_uuid();loc_b uuid:=gen_random_uuid();customer uuid:=gen_random_uuid();product uuid:=gen_random_uuid();config uuid:=gen_random_uuid();version uuid:=gen_random_uuid();d uuid;d_absent uuid;d_null uuid;d_empty uuid;j jsonb;vals jsonb;
begin
 insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)select id,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','x8bcp-'||id||'@x.invalid',now(),now()from unnest(array[creator,purchasing,global_reader,location_reader,contact_reader])id;
 insert into public.e10_organizations(id,slug,name)values(o,'x8bcp-'||substr(o::text,1,8),'X8b customer preview');
 insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values(creator_role,o,'creator','Creator',false),(purchasing_role,o,'purchasing','Purchasing',false),(global_role,o,'global-reader','Global reader',false),(location_role,o,'location-reader','Location reader',false),(contact_role,o,'contact-reader','Contact reader',false);
 insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values(o,creator,creator_role,'active'),(o,purchasing,purchasing_role,'active'),(o,global_reader,global_role,'active'),(o,location_reader,location_role,'active'),(o,contact_reader,contact_role,'active');
 insert into public.e10_organization_role_permissions values
  (o,creator_role,'act.prepare_customer_transactions',true),(o,creator_role,'act.approve_customer_transactions',true),(o,creator_role,'act.view_customer_financials',true),(o,creator_role,'act.manage_customers',true),
  (o,purchasing_role,'act.approve_customer_transactions',true),(o,purchasing_role,'financial.actual_cost.read',true),
  (o,global_role,'act.approve_customer_transactions',true),(o,global_role,'act.view_customer_financials',true),
  (o,location_role,'act.approve_customer_transactions',true),(o,contact_role,'act.approve_customer_transactions',true),(o,contact_role,'act.manage_customers',true);
 insert into public.e10_locations(id,organization_id,code,name,status)values(loc_a,o,'X8B-A','Location A','active'),(loc_b,o,'X8B-B','Location B','active');
 insert into public.e10_location_role_permissions(organization_id,location_id,role_id,can_view_customer_financials)values(o,loc_a,location_role,true);
 insert into public.e10_customers(id,organization_id,display_name,status)values(customer,o,'X8b customer','active');
 insert into public.e10_product_masters(id,organization_id,name)values(product,o,'X8b product');insert into public.e10_product_configurations(id,organization_id,product_master_id,name)values(config,o,product,'X8b configuration');insert into public.e10_product_configuration_versions(id,organization_id,configuration_id,version_no,state,packaging_kind,base_unit,base_units_per_package)values(version,o,config,1,'active','unit','unit',1);
 vals:=jsonb_build_object('customer_id',customer,'currency','CAD','occurred_at',null,'precision','unknown','note','private customer note','lines',jsonb_build_array(
  jsonb_build_object('purchase_kind','retail','capture_source','manual','source_line_id','a','location_id',loc_a,'product_master_id',product,'configuration_version_id',version,'quantity',1,'merchandise_gross',11,'raw_evidence',jsonb_build_object('nested',jsonb_build_object('email','a@example.invalid','invoice_total',99))),
  jsonb_build_object('purchase_kind','retail','capture_source','manual','source_line_id','b','location_id',loc_b,'product_master_id',product,'configuration_version_id',version,'quantity',1,'merchandise_gross',22),
  jsonb_build_object('purchase_kind','retail','capture_source','manual','source_line_id','none','product_master_id',product,'configuration_version_id',version,'quantity',1,'merchandise_gross',33)));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',creator,'role','authenticated')::text,true);set local role authenticated;j:=public.e10_org_create_action_draft(o,'customer_transaction.create_draft',vals,'{"note":{"source":"phone 555-0101","text":"unit cost 44 CAD"}}','[{"kind":"operator_note","source_reference":"buyer@example.invalid","payload":{"vendor_total":44}}]','create');d:=(j->>'draft_id')::uuid;
 d_absent:=(public.e10_org_create_action_draft(o,'customer_transaction.create_draft','{"note":"absent sensitive 99 CAD","precision":"unknown"}','{"note":{"text":"absent private"}}','[{"kind":"operator_note","text":"absent source"}]','absent')->>'draft_id')::uuid;
 d_null:=(public.e10_org_create_action_draft(o,'customer_transaction.create_draft','{"note":"null sensitive 99 CAD","precision":"unknown","lines":null}','{"note":{"text":"null private"}}','[{"kind":"operator_note","text":"null source"}]','null')->>'draft_id')::uuid;
 d_empty:=(public.e10_org_create_action_draft(o,'customer_transaction.create_draft','{"note":"empty sensitive 99 CAD","precision":"unknown","lines":[]}','{"note":{"text":"empty private"}}','[{"kind":"operator_note","text":"empty source"}]','empty')->>'draft_id')::uuid;
 j:=public.e10_org_preview_action_draft(o,d,1);if(j#>>'{values,lines,0,merchandise_gross}')::numeric<>11 or j#>>'{values,lines,0,raw_evidence,nested,email}'<>'a@example.invalid'or j#>>'{field_provenance,note,text}'<>'unit cost 44 CAD'or j#>>'{source_references,0,source_reference}'<>'buyer@example.invalid'then raise exception'fully-authorized preview lost evidence %',j;end if;
 if public.e10_org_preview_action_draft(o,d_absent,1)#>>'{values,note}'<>'absent sensitive 99 CAD'or public.e10_org_preview_action_draft(o,d_null,1)#>>'{values,note}'<>'null sensitive 99 CAD'or public.e10_org_preview_action_draft(o,d_empty,1)#>>'{values,note}'<>'empty sensitive 99 CAD'then raise exception'global plus contact lost incomplete-draft narrative';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',purchasing,'role','authenticated')::text,true);j:=public.e10_org_preview_action_draft(o,d,1);if j#>'{values,lines,0}'?'merchandise_gross'or j#>'{values,lines,0}'?'raw_evidence'or j->'values'?'note'or j->'field_provenance'<>'{}'or j->'source_references'<>'[]'then raise exception'purchasing-cost authority leaked customer financial or unstructured evidence %',j;end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',global_reader,'role','authenticated')::text,true);j:=public.e10_org_preview_action_draft(o,d,1);if(j#>>'{values,lines,0,merchandise_gross}')::numeric<>11 or(j#>>'{values,lines,1,merchandise_gross}')::numeric<>22 or(j#>>'{values,lines,2,merchandise_gross}')::numeric<>33 or j#>'{values,lines,0}'?'raw_evidence'or j->'values'?'note'or j->'field_provenance'<>'{}'then raise exception'global customer-financial projection wrong %',j;end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',location_reader,'role','authenticated')::text,true);j:=public.e10_org_preview_action_draft(o,d,1);if(j#>>'{values,lines,0,merchandise_gross}')::numeric<>11 or j#>'{values,lines,0}'?'raw_evidence'or j#>'{values,lines,1}'?'merchandise_gross'or j#>'{values,lines,2}'?'merchandise_gross'or j->'values'?'note'then raise exception'location-scoped customer-financial projection wrong %',j;end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',contact_reader,'role','authenticated')::text,true);j:=public.e10_org_preview_action_draft(o,d,1);if j#>'{values,lines,0}'?'merchandise_gross'or j#>'{values,lines,0}'?'raw_evidence'or j->'values'?'note'or j->'field_provenance'<>'{}'or j->'source_references'<>'[]'then raise exception'contact-only projection wrong %',j;end if;
 if public.e10_org_preview_action_draft(o,d_absent,1)->'values'?'note'or public.e10_org_preview_action_draft(o,d_null,1)->'values'?'note'or public.e10_org_preview_action_draft(o,d_empty,1)->'values'?'note'or public.e10_org_preview_action_draft(o,d_null,1)->'field_provenance'<>'{}'or public.e10_org_preview_action_draft(o,d_empty,1)->'source_references'<>'[]'then raise exception'contact-only incomplete draft leaked unstructured values or provenance';end if;
end $$;
rollback;
select'TA-X8b customer preview permission matrix PASS'as result;
