const {Client}=require("pg");
const {randomUUID}=require("crypto");
const db=process.env.E10_DB_URL||"postgresql://postgres:postgres@127.0.0.1:54322/postgres";
async function denied(p,code,msg){try{await p;return false}catch(e){return e.code===code&&e.message===msg}}
async function waitForLock(observer,pid){for(let n=0;n<150;n++){const r=(await observer.query("select wait_event_type from pg_stat_activity where pid=$1",[pid])).rows[0];if(r?.wait_event_type==="Lock")return true;await new Promise(resolve=>setTimeout(resolve,20))}return false}
async function main(){const s=new Client({connectionString:db}),caller=new Client({connectionString:db}),locker=new Client({connectionString:db}),obs=new Client({connectionString:db});await Promise.all([s.connect(),caller.connect(),locker.connect(),obs.connect()]);const x={org:randomUUID(),user:randomUUID(),role:randomUUID(),run:randomUUID()};let pending,ok=false;
try{for(const c of[s,caller,locker,obs])await c.query("set statement_timeout='8s'");await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.user,x.run+"@x.invalid"]);await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7c race')",[x.org,"x7cr-"+x.run.slice(0,8)]);await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,$3,'X7c race',false)",[x.role,x.org,x.run]);await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active')",[x.org,x.user,x.role]);await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.configure_attendance_normalization',true)",[x.org,x.role]);await s.query("insert into public.e10_presence_collection_policies(organization_id,policy_version,source_class,provider_key,enabled,notice_version,heartbeat_expiry_seconds,min_event_interval_ms,max_events_per_minute,retention_interval,coverage_label,effective_from,created_by)values($1,1,'authorized_platform','fixture',true,'n1',300,0,60,interval '30 days','fixture','2026-01-01',$2)",[x.org,x.user]);await caller.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:x.user,role:"authenticated"})]);await caller.query("set role authenticated");const key=x.run+"-policy";await locker.query("begin");await locker.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.org+"|provider-normalization-policy-idem|"+key]);const pid=(await caller.query("select pg_backend_pid() pid")).rows[0].pid;pending=caller.query("select public.e10_org_review_provider_presence_normalization_policy($1,'fixture',0,'enable','2026-01-01','2027-01-01',interval '5 minutes',interval '1 day',1,'race','{}',$2)",[x.org,key]);pending.catch(()=>{});if(!await waitForLock(obs,pid))throw Error("policy writer did not wait on exact backend");await s.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.configure_attendance_normalization'",[x.org,x.role]);await locker.query("commit");if(!await denied(pending,"42501","provider_normalization_policy_denied"))throw Error("blocked writer retained revoked authority");pending=null;const rows=Number((await s.query("select count(*) n from public.e10_provider_presence_normalization_policy_decisions where organization_id=$1",[x.org])).rows[0].n);if(rows!==0)throw Error("revoked writer left policy row");console.log("[proof] exact blocked policy writer reread revoked authority; zero decision residue");ok=true;
}finally{if(pending)await Promise.allSettled([pending]);await Promise.allSettled([caller.query("rollback"),locker.query("rollback")]);await caller.query("reset role").catch(()=>{});await s.query("set session_replication_role=replica");for(const t of["e10_provider_presence_normalization_policy_decisions","e10_presence_policy_state_history","e10_presence_collection_policies","e10_organization_role_permissions","e10_organization_memberships","e10_organization_roles","e10_reporting_dataset_revisions"])await s.query(`delete from public.${t} where organization_id=$1`,[x.org]);await s.query("delete from public.e10_organizations where id=$1",[x.org]);await s.query("set session_replication_role=origin");await s.query("delete from auth.users where id=$1",[x.user]);const residue=Number((await s.query("select count(*) n from public.e10_organizations where id=$1",[x.org])).rows[0].n);await Promise.all([s.end(),caller.end(),locker.end(),obs.end()]);if(residue)throw Error("X7c race cleanup failed")}
if(ok)console.log("TA-X7c provider normalization policy concurrency: PASS")}
main().catch(e=>{console.error(e.stack);process.exit(1)});
