\set ON_ERROR_STOP on
begin;
do $$
declare o uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();u uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();r1 uuid:=gen_random_uuid();r2 uuid:=gen_random_uuid();rel uuid:=gen_random_uuid();v uuid:=gen_random_uuid();p uuid:=gen_random_uuid();item uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();x uuid:=gen_random_uuid();z uuid:=gen_random_uuid();ctx uuid;parent_ctx uuid;expired uuid:=gen_random_uuid();fake uuid:=gen_random_uuid();screen jsonb;drill jsonb;drill2 jsonb;fp text;ck text;cur uuid;n integer;g text;got uuid[];
begin
 insert into auth.users(id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)values(u,'authenticated','authenticated','x7d-drill@example.invalid','',now(),'{}','{}',now(),now()),(u2,'authenticated','authenticated','x7d-drill2@example.invalid','',now(),'{}','{}',now(),now());insert into public.e10_organizations(id,slug,name)values(o,'x7d-drill-'||substr(o::text,1,8),'Drill'),(o2,'x7d-drillf-'||substr(o2::text,1,8),'Foreign');insert into public.e10_organization_roles(id,organization_id,key,name)values(r1,o,'reader','Reader'),(r2,o2,'reader','Reader');insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values(o,u,r1,'active'),(o,u2,r1,'active'),(o2,u,r2,'active');insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed)values(o,r1,'act.view_market_analytics',true),(o2,r2,'act.view_market_analytics',true);
 insert into public.e10_catalog_releases(id,release_name)values(rel,'Drill');insert into public.e10_players(id,name)values(p,'Drill subject');insert into public.e10_catalog_variants(id,release_id,card_number)values(v,rel,'1');insert into public.e10_catalog_variant_subjects(variant_id,player_id)values(v,p);set local session_replication_role=replica;insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,occurred_at,currency,amount,quantity,source_kind,source_connection_id,source_reference,raw_payload_snapshot)values(a,o,'completed_sale',v,'2026-01-10 10:00:00.000001+00','USD',10,1,'manual','one','allowed-one','{"secret":"a"}'),(x,o,'completed_sale',v,'2026-01-10 10:00:00.000001+00','USD',10,1,'manual','selected-dup','allowed-duplicate','{"secret":"x"}'),(b,o,'completed_sale',v,'2026-01-10 10:00:00.000001+00','USD',20,1,'manual','two','private-two','{"secret":"b"}'),(z,o,'completed_sale',v,'2026-01-09','USD',19,1,'manual','old','excluded-predecessor','{"secret":"z"}');insert into public.e10_market_observation_supersessions(organization_id,superseded_observation_id,replacement_observation_id,lineage_kind,correction_reason,idempotency_key,request_fingerprint)values(o,z,b,'manual_correction','x','drill-correction','fp');set local session_replication_role=origin;insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),a,1,'assert','raw',1,'unit_price',10,'x','{}','drill-a','fp'),(o,gen_random_uuid(),x,1,'assert','raw',1,'unit_price',10,'x','{}','drill-x','fp'),(o,gen_random_uuid(),b,1,'assert','raw',1,'unit_price',20,'x','{}','drill-b','fp');set local session_replication_role=replica;insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),x,a,1,'link',e10.market_observation_fingerprint(o,x),e10.market_observation_fingerprint(o,a),'x','{}','drill-eq','fp');set local session_replication_role=origin;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);screen:=public.e10_org_market_screener(o,'catalog','variant','count','completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,'{}','cohort_asc',50,null);fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';
 drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,null);cur:=(drill->>'next_cursor')::uuid;if jsonb_array_length(drill->'rows')is distinct from 1 or cur is null or drill#>>'{rows,0,provenance}'is distinct from'[]'or drill::text~'secret|allowed-one|private-two' then raise exception'first drill page/privacy failed: %',drill;end if;
 drill2:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,cur);if jsonb_array_length(drill2->'rows')is distinct from 1 or drill2->'next_cursor'is distinct from'null'::jsonb or drill2#>>'{rows,0,observation_id}'is not distinct from drill#>>'{rows,0,observation_id}'then raise exception'second drill page failed: %',drill2;end if;
 if(drill#>>'{rows,0,observation_id}')::uuid is distinct from(select q from unnest(array[a,b])q order by q desc limit 1)or(drill2#>>'{rows,0,observation_id}')::uuid is distinct from(select q from unnest(array[a,b])q order by q asc limit 1)then raise exception'microsecond tie UUID order failed';end if;
 begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,2,cur);raise exception'drill cursor input rebound accepted';exception when invalid_parameter_value then null;end;
 set local session_replication_role=replica;insert into public.e10_market_query_cursors(id,organization_id,actor_id,context_id,endpoint,query_fingerprint,sort_position,parent_cohort_key,organization_revision,catalog_revision,created_at,expires_at)select expired,organization_id,actor_id,context_id,endpoint,query_fingerprint,sort_position,parent_cohort_key,organization_revision,catalog_revision,clock_timestamp()-interval'2 minutes',clock_timestamp()-interval'1 minute'from public.e10_market_query_cursors where id=cur;insert into public.e10_market_query_cursors(id,organization_id,actor_id,context_id,endpoint,query_fingerprint,sort_position,parent_cohort_key,organization_revision,catalog_revision)select fake,organization_id,actor_id,context_id,'screener',query_fingerprint,sort_position,null,organization_revision,catalog_revision from public.e10_market_query_cursors where id=cur;set local session_replication_role=origin;begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,expired);raise exception'expired drill cursor accepted';exception when invalid_parameter_value then null;end;begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,fake);raise exception'wrong-endpoint drill cursor accepted';exception when invalid_parameter_value then null;end;
 select context_id into ctx from public.e10_market_query_cursors where id=cur;set local session_replication_role=replica;update public.e10_market_query_contexts set created_at=clock_timestamp()-interval'2 minutes',expires_at=clock_timestamp()-interval'1 minute'where id=ctx;set local session_replication_role=origin;begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,cur);raise exception'expired drill context accepted';exception when invalid_parameter_value then null;end;
 begin perform public.e10_org_market_observation_drilldown(o2,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,null);raise exception'cross-org parent accepted';exception when invalid_parameter_value then null;end;
 select id into parent_ctx from public.e10_market_query_contexts where organization_id=o and actor_id=u and endpoint='screener'and query_fingerprint=fp;set local session_replication_role=replica;update public.e10_market_query_contexts set created_at=clock_timestamp()-interval'2 minutes',expires_at=clock_timestamp()-interval'1 minute'where id=parent_ctx;set local session_replication_role=origin;begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,null);raise exception'expired parent accepted';exception when invalid_parameter_value then null;end;
 screen:=public.e10_org_market_screener(o,'catalog','variant','count','completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,'{}','cohort_asc',50,null);fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';update public.e10_organization_role_permissions set allowed=false where organization_id=o and role_id=r1 and capability='act.view_market_analytics';begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,null);raise exception'revoked-cap drill allowed';exception when insufficient_privilege then null;end;update public.e10_organization_role_permissions set allowed=true where organization_id=o and role_id=r1 and capability='act.view_market_analytics';
 begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,null,null);raise exception'NULL drill limit accepted';exception when invalid_parameter_value then null;end;
 drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,50,null);if not exists(select 1 from jsonb_array_elements(drill->'rows')q where q->>'observation_id'=b::text and q->'corrected_observation_ids'@>jsonb_build_array(z))or drill::text~'excluded-predecessor|"old"'then raise exception'correction lineage/privacy failed: %',drill;end if;
 foreach g in array array['entity','variant','variant_condition','variant_grader_grade','subject','release','color','finish']loop screen:=public.e10_org_market_screener(o,'catalog',g,'count','completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,'{}','cohort_asc',50,null);if jsonb_array_length(screen->'rows')is distinct from 1 then raise exception'grouping % parent count',g;end if;fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,50,null);select array_agg((elem->>'observation_id')::uuid order by(elem->>'observation_id')::uuid)into got from jsonb_array_elements(drill->'rows') elem;if got is distinct from array(select q from unnest(array[a,b])q order by q)then raise exception'grouping % members wrong: %',g,got;end if;end loop;
 screen:=public.e10_org_market_screener(o,'catalog','variant_condition','reviewed_unit_price','completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','none',null,null,'{"amount_min":15,"mean_min":20,"mean_max":20}','mean_desc',50,null);fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','none',null,null,50,null);if jsonb_array_length(drill->'rows')is distinct from 1 or drill#>>'{rows,0,observation_id}'is distinct from b::text then raise exception'transaction/aggregate filtered membership failed';end if;
 insert into public.e10_unique_items(id,organization_id,catalog_variant_id,item_kind)values(item,o,v,'card');set local session_replication_role=replica;insert into public.e10_market_observations(id,organization_id,observation_kind,unique_item_id,occurred_at,currency,amount,quantity,source_kind,raw_payload_snapshot)values(c,o,'completed_sale',item,'2026-01-12','USD',30,1,'manual','{}');set local session_replication_role=origin;
 screen:=public.e10_org_market_screener(o,'owned','entity','count','completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,'{}','cohort_asc',50,null);fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,50,null);if jsonb_array_length(drill->'rows')is distinct from 1 or drill#>>'{rows,0,observation_id}'is distinct from c::text then raise exception'owned scope membership failed';end if;
 screen:=public.e10_org_market_screener(o,'completed_sale_observation','entity','reviewed_unit_price','completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','none',null,null,'{"amount_min":20,"amount_max":20}','cohort_asc',50,null);fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','none',null,null,50,null);if jsonb_array_length(drill->'rows')is distinct from 1 or drill#>>'{rows,0,observation_id}'is distinct from b::text then raise exception'completed observation scope membership failed';end if;
 begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-01-31','2026-02-01','USD','none',null,null,1,null);raise exception'parent argument rebound accepted';exception when invalid_parameter_value then null;end;begin perform public.e10_org_market_observation_drilldown(o,fp,repeat('a',64),'completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','none',null,null,1,null);raise exception'arbitrary cohort accepted';exception when invalid_parameter_value then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u2,'role','authenticated')::text,true);begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','none',null,null,1,null);raise exception'foreign actor parent accepted';exception when invalid_parameter_value then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);screen:=public.e10_org_market_screener(o,'catalog','variant','count','completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','explicit','manual','["one"]','{}','cohort_asc',50,null);fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','explicit','manual','["one"]',50,null);if jsonb_array_length(drill->'rows')is distinct from 1 or jsonb_array_length(drill#>'{rows,0,provenance}')is distinct from 1 or drill#>>'{rows,0,provenance,0,source_reference}'is distinct from'allowed-one'or drill::text~'private-two|secret'then raise exception'allow-listed provenance failed: %',drill;end if;
 screen:=public.e10_org_market_screener(o,'catalog','variant','count','completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','explicit','manual','["selected-dup"]','{}','cohort_asc',50,null);fp:=screen->>'query_fingerprint';ck:=screen#>>'{rows,0,cohort_key}';drill:=public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','explicit','manual','["selected-dup"]',50,null);if jsonb_array_length(drill->'rows')is distinct from 1 or drill#>>'{rows,0,observation_id}'is distinct from a::text or drill#>>'{rows,0,provenance,0,observation_id}'is distinct from x::text or drill::text~'allowed-one|private-two|excluded-predecessor' then raise exception'selected duplicate canonical provenance failed: %',drill;end if;
 update public.e10_catalog_releases set release_name='Drill revised'where id=rel;begin perform public.e10_org_market_observation_drilldown(o,fp,ck,'completed_sale','2026-01-01','2026-02-01','2026-02-01','USD','explicit','manual','["selected-dup"]',50,null);raise exception'stale parent context accepted';exception when invalid_parameter_value then null;end;
 if has_function_privilege('anon','public.e10_org_market_observation_drilldown(uuid,text,text,text,timestamptz,timestamptz,timestamptz,text,text,text,jsonb,integer,uuid)','execute')or not has_function_privilege('authenticated','public.e10_org_market_observation_drilldown(uuid,text,text,text,timestamptz,timestamptz,timestamptz,text,text,text,jsonb,integer,uuid)','execute')then raise exception'drilldown ACL mismatch';end if;
end $$;
rollback;
select'TA-X7d.2 public drilldown PASS'result;
