\set ON_ERROR_STOP on
begin;
do $$
declare o uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();r uuid:=gen_random_uuid();v uuid:=gen_random_uuid();p uuid:=gen_random_uuid();p2 uuid:=gen_random_uuid();u uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();h uuid:=gen_random_uuid();c uuid:=gen_random_uuid();z uuid:=gen_random_uuid();pm uuid:=gen_random_uuid();cfg uuid:=gen_random_uuid();cvn uuid:=gen_random_uuid();q1 uuid:=gen_random_uuid();q2 uuid:=gen_random_uuid();g1 uuid:=gen_random_uuid();g2 uuid:=gen_random_uuid();g3 uuid:=gen_random_uuid();g4 uuid:=gen_random_uuid();g5 uuid:=gen_random_uuid();g6 uuid:=gen_random_uuid();g7 uuid:=gen_random_uuid();g8 uuid:=gen_random_uuid();term uuid:=gen_random_uuid();globalterm uuid:=gen_random_uuid();termid uuid;finishterm uuid:=gen_random_uuid();finishglobal uuid:=gen_random_uuid();finishid uuid;fact_key uuid:=gen_random_uuid();fact_b uuid;eqid uuid;ovkey uuid:=gen_random_uuid();ovid uuid;clearid uuid;fp1 text;fp2 text;n integer;
begin
 insert into public.e10_organizations(id,slug,name)values(o,'x7dp-'||substr(o::text,1,8),'Projection'),(o2,'x7dpf-'||substr(o2::text,1,8),'Foreign');
 insert into public.e10_catalog_releases(id,release_name,release_year,sport)values(r,'Projection Release',2026,'soccer');insert into public.e10_players(id,name)values(p,'Subject'),(p2,'Second Subject');insert into public.e10_catalog_variants(id,release_id,card_number,exact_parallel,print_run_denominator)values(v,r,'10','Blue',99);insert into public.e10_catalog_variant_subjects(variant_id,player_id,position)values(v,p,1),(v,p2,2);insert into public.e10_unique_items(id,organization_id,catalog_variant_id,item_kind)values(u,o,v,'card');
 insert into public.e10_product_masters(id,organization_id,name)values(pm,o,'Product');insert into public.e10_product_configurations(id,organization_id,product_master_id,name)values(cfg,o,pm,'Config');insert into public.e10_product_configuration_versions(id,organization_id,configuration_id,version_no,state,packaging_kind,base_unit,base_units_per_package)values(cvn,o,cfg,1,'active','box','card',1);
 set local session_replication_role=replica;
 insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,unique_item_id,product_master_id,configuration_version_id,occurred_at,currency,amount,quantity,source_kind,source_connection_id,source_reference,raw_payload_snapshot)
 values(a,o,'completed_sale',v,null,null,null,'2026-01-01T00:00:00Z','USD',500,5,'manual',null,'a','{}'),(b,o,'completed_sale',v,null,null,null,'2026-01-01T00:00:00Z','USD',500,5,'csv','shop','b','{}'),(h,o,'completed_sale',v,null,null,null,'2026-01-01T00:00:00Z','USD',500,5,'api','feed','h','{}'),(c,o,'asking_price',null,u,null,null,'2026-01-02T00:00:00Z','USD',25,1,'manual',null,'c','{}'),(z,o2,'completed_sale',v,null,null,null,'2026-01-01T00:00:00Z','USD',500,5,'manual',null,'z','{}'),(q1,o,'estimated_value',null,null,pm,null,'2026-01-03T00:00:00Z','USD',40,null,'manual',null,'q1','{}'),(q2,o,'asking_price',null,null,null,cvn,'2026-01-04T00:00:00Z','USD',30,3,'manual',null,'q2','{}'),(g1,o,'completed_sale',v,null,null,null,'2026-01-05T00:00:00Z','USD',100,1,'manual',null,'g1','{}'),(g2,o,'completed_sale',v,null,null,null,'2026-01-06T00:00:00Z','USD',100,1,'manual',null,'g2','{}'),(g3,o,'completed_sale',v,null,null,null,'2026-01-07T00:00:00Z','USD',100,1,'manual',null,'g3','{}'),(g4,o,'completed_sale',v,null,null,null,'2026-01-08T00:00:00Z','USD',100,1,'manual',null,'g4','{}'),(g5,o,'completed_sale',v,null,null,null,'2026-01-09T00:00:00Z','USD',100,1,'manual',null,'g5','{}'),(g6,o,'completed_sale',v,null,null,null,'2026-01-10T00:00:00Z','USD',100,1,'manual',null,'g6','{}'),(g7,o,'completed_sale',v,null,null,null,'2026-01-11T00:00:00Z','USD',100,1,'manual',null,'g7','{}'),(g8,o,'completed_sale',v,null,null,null,'2026-01-12T00:00:00Z','USD',100,1,'manual',null,'g8','{}');
 set local session_replication_role=origin;
 insert into public.e10_catalog_facet_term_keys(id,namespace)values(term,'color_family'),(globalterm,'color_family'),(finishterm,'finish_family'),(finishglobal,'finish_family');insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(term,'color_family','Blue',1,'assert','x','{}','projection-term','fp')returning id into termid;insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(globalterm,'color_family','Green',1,'assert','x','{}','projection-global-term','fp'),(finishglobal,'finish_family','Chrome',1,'assert','x','{}','projection-finish-global','fp');insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(finishterm,'finish_family','Refractor',1,'assert','x','{}','projection-finish-private','fp')returning id into finishid;
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,term_key,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,'color_family',1,'assert',globalterm,'x','{}','projection-color','fp'),(gen_random_uuid(),v,'finish_family',1,'assert',finishglobal,'x','{}','projection-finish','fp');
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,facet_key,revision,action,boolean_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,'rookie_designation',1,'assert',true,'x','{}','projection-rookie','fp');
 insert into public.e10_catalog_variant_facet_decisions(decision_key,variant_id,subject_id,facet_key,revision,action,boolean_value,reason,evidence,idempotency_key,request_fingerprint)values(gen_random_uuid(),v,p,'rookie_designation',1,'assert',true,'x','{}','projection-rookie-p','fp'),(gen_random_uuid(),v,p2,'rookie_designation',1,'assert',false,'x','{}','projection-rookie-p2','fp');
 insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,facet_key,revision,action,reason,evidence,idempotency_key,request_fingerprint)values(o,ovkey,v,'color_family',1,'mask','x','{}','projection-mask','fp')returning id into ovid;
 insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,facet_key,revision,action,term_key,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),v,'finish_family',1,'assert',finishterm,'x','{}','projection-finish-org','fp');
 insert into public.e10_unique_item_facet_decisions(organization_id,decision_key,unique_item_id,subject_id,revision,action,marking_text,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),u,p,1,'assert','factory dot','x','{}','projection-copy','fp');
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),a,1,'assert','raw',5,'transaction_total',100,'x','{}','projection-fa','fp');
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,fact_key,b,1,'assert','raw',5,'transaction_total',100,'x','{}','projection-fb','fp')returning id into fact_b;
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),h,1,'assert','raw',5,'transaction_total',100,'x','{}','projection-fh','fp'),(o,gen_random_uuid(),c,1,'assert','raw',1,'transaction_total',null,'x','{}','projection-fc','fp'),(o,gen_random_uuid(),q1,1,'assert',null,null,'unknown',null,'x','{}','projection-fq1','fp'),(o,gen_random_uuid(),q2,1,'assert',null,null,'unknown',null,'x','{}','projection-fq2','fp');
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,grader_code,grade_label,grade_qualifier,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),g1,1,'assert','graded','PSA','9',null,1,'unit_price',100,'x','{}','projection-g1','fp'),(o,gen_random_uuid(),g2,1,'assert','graded','BGS','9',null,1,'unit_price',100,'x','{}','projection-g2','fp'),(o,gen_random_uuid(),g3,1,'assert','graded','PSA','10',null,1,'unit_price',100,'x','{}','projection-g3','fp'),(o,gen_random_uuid(),g4,1,'assert','graded','PSA','10','OC',1,'unit_price',100,'x','{}','projection-g4','fp');
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,grader_code,grade_label,grade_qualifier,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),g5,1,'assert','graded','A|B','C',null,1,'unit_price',100,'x','{}','projection-g5','fp'),(o,gen_random_uuid(),g6,1,'assert','graded','A','B|C',null,1,'unit_price',100,'x','{}','projection-g6','fp'),(o,gen_random_uuid(),g7,1,'assert','graded','PSA','8',null,1,'unit_price',100,'x','{}','projection-g7','fp'),(o,gen_random_uuid(),g8,1,'assert','graded','PSA','8','unknown',1,'unit_price',100,'x','{}','projection-g8','fp');
 fp1:=e10.market_observation_fingerprint(o,a);fp2:=e10.market_observation_fingerprint(o,b);insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),a,b,1,'link',fp1,fp2,'x','{}','projection-eq','fp')returning id into eqid;
 insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),h,a,1,'link',e10.market_observation_fingerprint(o,h),e10.market_observation_fingerprint(o,a),'x','{}','projection-eq-h','fp');
 select count(*)into n from public.e10_market_eligible_canonical_observations where organization_id=o;if n<>12 then raise exception'expected 12 canonical rows got %',n;end if;
 select count(distinct metric_cohort_key)into n from public.e10_market_eligible_canonical_observations where organization_id=o and observation_id=any(array[b,g1,g2,g3,g4,g5,g6,g7,g8]);if n<>9 then raise exception'metric cohort collapsed grade dimensions, distinct %',n;end if;
 if not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=b and provenance_count=3 and provenance_observation_ids@>array[a,b,h]::uuid[] and catalog_variant_id=v and release_id=r and subject_ids=array[p,p2]::uuid[] and condition_state='raw'and transaction_total_amount=500 and reviewed_unit_price_amount=100 and known_unit_quantity=5 and color_family_term_id is null and color_family_status='org_masked'and rookie_designation is true and rookie_designation_status='global_reviewed'and rookie_designation_by_subject->p::text->'value'='true'::jsonb and rookie_designation_by_subject->p2::text->'value'='false'::jsonb)then raise exception'merged canonical projection mismatch';end if;
 insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,facet_key,revision,action,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,ovkey,v,'color_family',2,'clear',ovid,'x','{}','projection-clear','fp')returning id into clearid;
 if not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=b and color_family_term_id=globalterm and color_family_status='global_reviewed')then raise exception'org clear did not fall back to global';end if;
 insert into public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key,variant_id,facet_key,revision,action,term_key,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,ovkey,v,'color_family',3,'assert',term,clearid,'x','{}','projection-reassert','fp');
 if not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=b and color_family_term_id=term and color_family_status='org_override')then raise exception'org reassert precedence mismatch';end if;
 insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,supersedes_term_id,reason,evidence,idempotency_key,request_fingerprint)values(term,'color_family','Blue',2,'revoke',termid,'x','{}','projection-term-revoke','fp');
 if not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=b and color_family_term_id is null and color_family_status='org_term_revoked')then raise exception'revoked term remained filterable';end if;
 insert into public.e10_catalog_facet_taxonomy_terms(term_key,namespace,canonical_name,revision,action,supersedes_term_id,reason,evidence,idempotency_key,request_fingerprint)values(finishterm,'finish_family','Refractor',2,'revoke',finishid,'x','{}','projection-finish-revoke','fp');
 if not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=b and finish_family_term_id is null and finish_family_status='org_term_revoked')then raise exception'revoked finish term fell through to global';end if;
 if not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=c and unique_item_id=u and catalog_variant_id=v and copy_marking_texts=array['factory dot']::text[] and amount_basis_known=true and reviewed_unit_price_amount is null)then raise exception'copy/unallocated projection mismatch';end if;
 if not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=q1 and product_master_id=pm and known_unit_quantity is null and amount_basis='unknown'and amount_basis_known=false)or not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id=q2 and configuration_version_id=cvn and product_master_id=pm and known_unit_quantity=3 and amount_basis='unknown'and amount_basis_known=false)then raise exception'unknown amount or product/config mapping mismatch';end if;
 if exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o and observation_id=z)or not exists(select 1 from public.e10_market_eligible_canonical_observations where organization_id=o2 and observation_id=z)then raise exception'populated foreign organization partition mismatch';end if;
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,fact_key,b,2,'assert','raw',5,'unit_price',500,fact_b,'corrected','{}','projection-fb2','fp');
 select count(*)into n from public.e10_market_eligible_canonical_observations where organization_id=o;if n<>13 then raise exception'stale equivalence silently merged, rows %',n;end if;
 if(select count(*)from public.e10_market_eligible_canonical_observations where organization_id=o and canonical_observation_id in(a,b)and review_required_equivalence_count=1)<>2 then raise exception'stale equivalence disclosure mismatch';end if;
 if has_table_privilege('authenticated','public.e10_market_eligible_canonical_observations','select')or has_function_privilege('authenticated','e10.resolve_market_observation_canonical(uuid,uuid)','execute')then raise exception'projection ACL leak';end if;
end $$;
rollback;
select'TA-X7d.1 canonical projection PASS'as result;
