const { Client } = require('pg');
const cs = process.env.DATABASE_URL || 'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const run = Date.now().toString(); const uid = n => `d3220000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const x={org:uid(1),actor:uid(2),role:uid(3),supplier:uid(4),location:uid(5),product:uid(6),config:uid(7),version:uid(8)};
for(let n=0;n<4;n++){x[`po${n}`]=uid(10+n*4);x[`pol${n}`]=uid(11+n*4);x[`inv${n}`]=uid(12+n*4);x[`il${n}`]=uid(13+n*4)}
const admin=new Client({connectionString:cs}),a=new Client({connectionString:cs}),b=new Client({connectionString:cs});const timeout=8000;
async function claims(c){await c.query('set local role authenticated');await c.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:x.actor,role:'authenticated'})])}
async function bounded(p){let t;try{return await Promise.race([p,new Promise((_,r)=>t=setTimeout(()=>r(Error('workflow race timeout')),timeout))])}finally{clearTimeout(t)}}
async function wait(pid){const end=Date.now()+timeout;while(Date.now()<end){const q=await admin.query("select count(*)::int n from pg_locks where pid=$1 and locktype='advisory' and not granted",[pid]);if(q.rows[0].n)return;await new Promise(r=>setTimeout(r,25))}throw Error(`backend ${pid} did not enter exact advisory wait`)}
const lockInvoice=(c,n)=>c.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`${x.org}|financial-document|supplier_invoice|${x[`inv${n}`]}`]);
const lockPo=(c,n)=>c.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`${x.org}|purchase-order|${x[`po${n}`]}`]);
const alloc=(c,n,key)=>c.query('select public.e10_org_allocate_invoice_to_po($1,$2,$3,1,1,1,$4,$4) r',[x.org,x[`il${n}`],x[`pol${n}`],key]);
async function setup(){await Promise.all([admin.connect(),a.connect(),b.connect()]);
 await admin.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.actor,`x3d1d-races-${run}@example.invalid`]);
 await admin.query('insert into public.e10_organizations(id,name,slug) values($1,$2,$3)',[x.org,'X3d1d workflow races',`x3d1d-races-${run}`]);
 await admin.query("insert into public.e10_organization_roles(id,organization_id,key,name) values($1,$2,'race','Race')",[x.role,x.org]);
 await admin.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status) values($1,$2,$3,'active')",[x.org,x.actor,x.role]);
 await admin.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed) values($1,$2,'act.purchasing_prepare',true),($1,$2,'act.purchasing_cancel',true),($1,$2,'act.create_receiving',true)",[x.org,x.role]);
 await admin.query("insert into public.e10_suppliers(id,organization_id,name,status) values($1,$2,'supplier','active')",[x.supplier,x.org]);
 await admin.query("insert into public.e10_locations(id,organization_id,name,status) values($1,$2,'location','active')",[x.location,x.org]);
 await admin.query('insert into public.e10_location_role_permissions(organization_id,location_id,role_id,can_receive) values($1,$2,$3,true)',[x.org,x.location,x.role]);
 await admin.query("insert into public.e10_product_masters(id,organization_id,name) values($1,$2,'product')",[x.product,x.org]);
 await admin.query("insert into public.e10_product_configurations(id,organization_id,product_master_id,name) values($1,$2,$3,'config')",[x.config,x.org,x.product]);
 await admin.query("insert into public.e10_product_configuration_versions(id,organization_id,configuration_id,version_no,state,packaging_kind,base_unit,base_units_per_package) values($1,$2,$3,1,'active','unit','unit',1)",[x.version,x.org,x.config]);
 for(let n=0;n<4;n++){await admin.query("insert into public.e10_purchase_orders(id,organization_id,supplier_id,destination_location_id,order_number,status,currency,created_by) values($1,$2,$3,$4,$5,'approved','CAD',$6)",[x[`po${n}`],x.org,x.supplier,x.location,`PO-${run}-${n}`,x.actor]);await admin.query('insert into public.e10_purchase_order_lines(id,organization_id,purchase_order_id,configuration_version_id,line_no,ordered_quantity) values($1,$2,$3,$4,1,6)',[x[`pol${n}`],x.org,x[`po${n}`],x.version]);await admin.query("insert into public.e10_supplier_invoices(id,organization_id,supplier_id,supplier_document_number,currency,total_amount,created_by) values($1,$2,$3,$4,'CAD',60,$5)",[x[`inv${n}`],x.org,x.supplier,`INV-${run}-${n}`,x.actor]);await admin.query('insert into public.e10_supplier_invoice_lines(id,organization_id,supplier_invoice_id,configuration_version_id,line_no,invoiced_quantity,unit_cost,line_amount) values($1,$2,$3,$4,1,6,10,60)',[x[`il${n}`],x.org,x[`inv${n}`],x.version]);}
 await admin.query('insert into public.e10_inventory_items(id,name,qty,organization_id) values($1,$2,0,$3)',[`race-item-${run}`,'Race item',x.org]);
}
async function scenarioAmend(){await a.query('begin');await claims(a);await lockInvoice(a,0);await b.query('begin');await claims(b);const pid=(await b.query('select pg_backend_pid() pid')).rows[0].pid;const pending=alloc(b,0,`amend-alloc-${run}`);await wait(pid);const lines=JSON.stringify([{id:x.il0,line_no:1,configuration_version_id:x.version,description:'amended',invoiced_quantity:6,unit_cost:10,line_amount:60}]);await a.query('select public.e10_org_amend_supplier_invoice($1,$2,1,$3,null,60,$4::jsonb,$5,$6)',[x.org,x.inv0,'CAD',lines,'race amendment',`amend-${run}`]);await a.query('commit');let denied;try{await bounded(pending)}catch(e){denied=e}await b.query('rollback');if(!denied||denied.code!=='40001')throw Error(`allocation-vs-amend invalid ${denied&&denied.code}`);console.log(`[proof] backend ${pid} waited on amendment; stale allocation denied`)}
async function scenarioVoid(){await a.query('begin');await claims(a);await lockInvoice(a,1);await b.query('begin');await claims(b);const pid=(await b.query('select pg_backend_pid() pid')).rows[0].pid;const pending=alloc(b,1,`void-alloc-${run}`);await wait(pid);await a.query('select public.e10_org_void_supplier_invoice($1,$2,1,$3,$4)',[x.org,x.inv1,'void first',`void-${run}`]);await a.query('commit');let denied;try{await bounded(pending)}catch(e){denied=e}await b.query('rollback');if(!denied||denied.code!=='55000')throw Error(`void-first race invalid ${denied&&denied.code}`);
 await a.query('begin');await claims(a);await lockInvoice(a,2);await alloc(a,2,`match-first-${run}`);await b.query('begin');await claims(b);const pid2=(await b.query('select pg_backend_pid() pid')).rows[0].pid;const voiding=b.query('select public.e10_org_void_supplier_invoice($1,$2,1,$3,$4)',[x.org,x.inv2,'void second',`void-second-${run}`]);await wait(pid2);await a.query('commit');let blocked;try{await bounded(voiding)}catch(e){blocked=e}await b.query('rollback');if(!blocked||!['40001','55000'].includes(blocked.code))throw Error(`match-first race invalid ${blocked&&blocked.code}`);console.log(`[proof] void/match serialized in both orders; backends ${pid}/${pid2} preserved terminal and allocation barriers`)}
async function scenarioReceive(){await a.query('begin');await claims(a);await lockPo(a,3);await b.query('begin');await claims(b);const pid=(await b.query('select pg_backend_pid() pid')).rows[0].pid;const pending=alloc(b,3,`receive-alloc-${run}`);await wait(pid);const receipt=await a.query("select public.e10_org_receive_po_line($1,$2,$3,1,0,0,null,now(),'[]'::jsonb,$4) r",[x.org,x.pol3,`race-item-${run}`,`receive-${run}`]);await a.query('commit');const matched=await bounded(pending);await b.query('commit');if(!receipt.rows[0].r.receipt_id||matched.rows[0].r.allocated_quantity!==1)throw Error('receive/allocation result invalid');const q=await admin.query('select qty from public.e10_inventory_items where organization_id=$1 and id=$2',[x.org,`race-item-${run}`]);if(Number(q.rows[0].qty)!==1)throw Error('receipt stock changed incorrectly');console.log(`[proof] backend ${pid} waited on real receipt writer; receipt and match both completed with conserved state`)}
const tables=['e10_credit_invoice_allocation_events','e10_invoice_po_allocation_events','e10_financial_allocation_commands','e10_financial_document_events','e10_financial_document_commands','e10_supplier_credit_revisions','e10_supplier_invoice_revisions','e10_credit_invoice_allocations','e10_invoice_po_allocations','e10_receipt_po_allocations','e10_stock_receipt_reversals','e10_stock_receipt_lines','e10_stock_receipts','e10_inventory_lots','e10_inventory_movements','e10_supplier_credit_lines','e10_supplier_credits','e10_supplier_invoice_lines','e10_supplier_invoices','e10_purchase_order_commands','e10_purchase_order_revisions','e10_commercial_events','e10_purchase_order_lines','e10_purchase_orders','e10_inventory_items','e10_product_configuration_versions','e10_product_configurations','e10_product_masters','e10_location_role_permissions','e10_locations','e10_suppliers','e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles'];
async function cleanup(){await admin.query('begin');await admin.query("set local session_replication_role='replica'");for(const t of tables)await admin.query(`delete from public.${t} where organization_id=$1`,[x.org]);await admin.query('delete from public.e10_organizations where id=$1',[x.org]);await admin.query('delete from auth.users where id=$1',[x.actor]);await admin.query('commit');for(const t of tables){const q=await admin.query(`select count(*)::int n from public.${t} where organization_id=$1`,[x.org]);if(q.rows[0].n)throw Error(`cleanup residue ${t}=${q.rows[0].n}`)}const q=await admin.query('select (select count(*) from public.e10_organizations where id=$1)+(select count(*) from auth.users where id=$2) n',[x.org,x.actor]);if(Number(q.rows[0].n))throw Error('identity cleanup residue')}
(async()=>{try{await setup();await scenarioAmend();await scenarioVoid();await scenarioReceive();await cleanup();console.log('TA-X3d.1d allocation vs amend/void/receiving races: PASS (fixture-free)')}catch(e){await Promise.allSettled([a.query('rollback'),b.query('rollback')]);try{await cleanup()}catch(c){console.error(c)}console.error(e);process.exitCode=1}finally{await Promise.allSettled([admin.end(),a.end(),b.end()])}})();
