const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres',WAIT=8000;
async function client(actor){const c=new Client({connectionString:db});await c.connect();await c.query("set statement_timeout='8s';set lock_timeout='7s'");if(actor){await c.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:actor,role:'authenticated'})]);await c.query('set role authenticated')}return c}
async function waitBlocked(s,pid,blocker,label){const until=Date.now()+WAIT;while(Date.now()<until){const r=await s.query('select $1=any(pg_blocking_pids($2)) ok', [blocker,pid]);if(r.rows[0].ok){console.log(`[proof] ${label}: backend ${pid} blocked by ${blocker}`);return}await new Promise(r=>setTimeout(r,30))}throw Error(`timeout waiting for ${label}`)}
async function bounded(p,label){let timer;try{return await Promise.race([p,new Promise((_,rej)=>{timer=setTimeout(()=>rej(Error(`timeout ${label}`)),WAIT)})])}finally{clearTimeout(timer)}}
const result=p=>p.then(value=>({ok:true,value}),error=>({ok:false,error}));
async function main(){const s=await client(),lock=await client();await s.query("set statement_timeout='8s';set lock_timeout='7s'");await lock.query("set statement_timeout='8s';set lock_timeout='7s'");const x={org:randomUUID(),user:randomUUID(),role:randomUUID(),release:randomUUID(),variant:randomUUID(),a:randomUUID(),b:randomUUID(),run:randomUUID()};let u1,u2,cov,ok=false;const pending=[];
 try{
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.user,`x7dec-${x.run}@x.invalid`]);await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7d concurrency')",[x.org,'x7dec-'+x.run.slice(0,8)]);await s.query("insert into public.e10_organization_roles(organization_id,id,key,name)values($1,$2,$3,'reviewer')",[x.org,x.role,x.run]);await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active')",[x.org,x.user,x.role]);await s.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed)values($1,$2,'act.curate_market_analytics',true)",[x.org,x.role]);await s.query("insert into public.e10_catalog_releases(id,release_name)values($1,'X7d')",[x.release]);await s.query('insert into public.e10_catalog_variants(id,release_id)values($1,$2)',[x.variant,x.release]);await s.query("insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,occurred_at,currency,amount,quantity,source_kind,raw_payload_snapshot)values($1,$2,'completed_sale',$3,'2026-01-01','USD',10,1,'manual','{}'),($4,$2,'completed_sale',$3,'2026-01-01','USD',10,1,'csv','{}')",[x.a,x.org,x.variant,x.b]);
  [u1,u2,cov]=await Promise.all([client(x.user),client(x.user),client(x.user)]);const p1=(await u1.query('select pg_backend_pid() pid')).rows[0].pid,p2=(await u2.query('select pg_backend_pid() pid')).rows[0].pid,lp=(await lock.query('select pg_backend_pid() pid')).rows[0].pid;
  await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.org+'|market-equivalence-graph']);
  const q=(cl,dup,canon,key)=>cl.query("select public.e10_org_review_market_observation_equivalence($1,null,$2,$3,0,'link','race','{}',$4) r",[x.org,dup,canon,key]);
  const q1=result(q(u1,x.a,x.b,x.run+'-ab')),q2=result(q(u2,x.b,x.a,x.run+'-ba'));pending.push(q1,q2);await waitBlocked(s,p1,lp,'opposite edge A');await waitBlocked(s,p2,lp,'opposite edge B');await lock.query('commit');
  const settled=await bounded(Promise.all([q1,q2]),'opposite equivalence completion');const wins=settled.filter(v=>v.ok),losses=settled.filter(v=>!v.ok);if(wins.length!==1||losses.length!==1||losses[0].error.code!=='23514'||losses[0].error.message!=='observation_equivalence_cycle')throw Error('opposite edges did not serialize to one link and one cycle denial');console.log('[proof] opposite equivalence edges serialized: one link, one cycle denial');

  await lock.query('begin');await lock.query('select revision from public.e10_market_org_revisions where organization_id=$1 for update',[x.org]);const cp=(await cov.query('select pg_backend_pid() pid')).rows[0].pid;const coveragePending=result(cov.query("select public.e10_org_review_market_observation_coverage($1,null,'completed_sale','csv','shop','USD','2026-01-01T00:00:00Z','2026-02-01T00:00:00Z',0,'assert','complete','race','{}',$2)",[x.org,x.run+'-coverage']));pending.push(coveragePending);await waitBlocked(s,cp,lp,'coverage revision recheck');await s.query("delete from public.e10_organization_role_permissions where organization_id=$1 and role_id=$2 and capability='act.curate_market_analytics'",[x.org,x.role]);await lock.query('commit');const denied=await bounded(coveragePending,'coverage authority completion');if(denied.ok||denied.error.code!=='42501'||denied.error.message!=='market_evidence_curation_denied')throw Error('coverage writer did not deny after capability revoke');if((await s.query("select count(*)::int n from public.e10_market_observation_coverage_decisions where organization_id=$1 and idempotency_key=$2",[x.org,x.run+'-coverage'])).rows[0].n!==0)throw Error('denied coverage write persisted');console.log('[proof] coverage writer reread revoked capability after exact revision wait');ok=true;
 }finally{
  await lock.query('rollback').catch(()=>{});await Promise.allSettled(pending.map(p=>bounded(p,'cleanup pending').catch(()=>{})));for(const c of[u1,u2,cov])if(c){await c.query('rollback').catch(()=>{});await c.query('reset role').catch(()=>{});await c.end().catch(()=>{})}await lock.end();await s.query('set session_replication_role=replica');for(const t of['e10_market_observation_equivalence_decisions','e10_market_observation_coverage_decisions','e10_market_observations'])await s.query(`delete from public.${t} where organization_id=$1`,[x.org]);await s.query('delete from public.e10_catalog_variants where id=$1',[x.variant]);await s.query('delete from public.e10_catalog_releases where id=$1',[x.release]);for(const t of['e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles','e10_market_org_revisions'])await s.query(`delete from public.${t} where organization_id=$1`,[x.org]);await s.query('delete from public.e10_organizations where id=$1',[x.org]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=$1',[x.user]);const residue=Number((await s.query("select (select count(*)from public.e10_organizations where id=$1)+(select count(*)from public.e10_market_observation_equivalence_decisions where idempotency_key like $2)+(select count(*)from public.e10_market_observation_coverage_decisions where idempotency_key like $2)n",[x.org,x.run+'%'])).rows[0].n);await s.end();if(residue)throw Error('concurrency cleanup residue');
 }
 if(ok)console.log('TA-X7d.0 market evidence writer concurrency: PASS');
}
main().catch(e=>{console.error(e.stack);process.exit(1)});
