const {Client}=require('pg');const {randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
async function denied(p,code,msg){try{await p;return false}catch(e){return e.code===code&&(!msg||e.message===msg)}}
async function main(){const s=new Client({connectionString:db}),a=new Client({connectionString:db}),h=new Client({connectionString:db});await Promise.all([s.connect(),a.connect(),h.connect()]);
 const org=randomUUID(),org2=randomUUID(),user=randomUUID(),hostile=randomUUID(),role=randomUUID(),role2=randomUUID(),loc=randomUUID();let ok=false;
 try{
  await s.query("set statement_timeout='30s';set session_replication_role=replica");
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now()),($3,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$4,now(),now())",[user,`x7f-${user}@x.invalid`,hostile,`x7fh-${hostile}@x.invalid`]);
  await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7f'),($3,$4,'X7f hostile')",[org,'x7f-'+org.slice(0,8),org2,'x7fh-'+org2.slice(0,8)]);
  await s.query('insert into public.e10_reporting_dataset_revisions(organization_id)values($1),($2) on conflict do nothing',[org,org2]);
  await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,'reader','Reader',false),($3,$4,'hostile','Hostile',false)",[role,org,role2,org2]);
  await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active'),($4,$5,$6,'active')",[org,user,role,org2,hostile,role2]);
  await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_financials',true)",[org,role]);
  await s.query("insert into public.e10_locations(id,organization_id,name,status)values($1,$2,'X7f Store','active')",[loc,org]);
  await s.query("insert into public.e10_customers(id,organization_id,display_name)select gen_random_uuid(),$1,case when i=205 then null else 'Buyer '||lpad(i::text,3,'0')end from generate_series(1,205)i",[org]);
  await s.query("insert into public.e10_customer_transactions(id,organization_id,customer_id,currency,occurred_at,occurred_at_precision,source_draft_id,source_draft_revision,commercial_event_id)select gen_random_uuid(),organization_id,id,'USD','2026-01-15','exact',gen_random_uuid(),1,gen_random_uuid()from public.e10_customers where organization_id=$1",[org]);
  await s.query("insert into public.e10_customer_transaction_lines(id,organization_id,transaction_id,line_no,purchase_kind,sales_channel,location_id,capture_source,source_line_id,quantity,merchandise_gross,merchandise_discount,shipping_amount,tax_amount,raw_evidence)select gen_random_uuid(),$1,t.id,1,'retail',case when row_number()over(order by t.customer_id)%2=0 then'web'else'store'end,$2,'manual',t.id::text,1,10,0,0,0,'{}'from public.e10_customer_transactions t where t.organization_id=$1",[org,loc]);
  const target=(await s.query("select customer_id from public.e10_customer_transactions where organization_id=$1 order by customer_id offset 150 limit 1",[org])).rows[0].customer_id;
  await s.query("update public.e10_customer_transaction_lines l set merchandise_gross=999,merchandise_discount=0 where l.organization_id=$1 and l.transaction_id=(select id from public.e10_customer_transactions where organization_id=$1 and customer_id=$2)",[org,target]);
  await s.query("update public.e10_customer_transactions set occurred_at='2024-01-15' where organization_id=$1 and customer_id=(select customer_id from public.e10_customer_transactions where organization_id=$1 and customer_id<>$2 order by customer_id limit 1)",[org,target]);
  for(const [q,id]of[[a,user],[h,hostile]]){await q.query("select set_config('request.jwt.claims',jsonb_build_object('sub',$1::text,'role','authenticated')::text,false)",[id]);await q.query('set role authenticated')}
  const x8ctx=(await a.query("select public.e10_org_create_query_context($1,'workspace',600,$2)r",[org,'x7f-'+org])).rows[0].r.context_id;
  const call=(extra={})=>a.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>$2,p_from=>$3,p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1,p_channel=>$4,p_min_known_official_subtotal=>$5,p_max_known_official_subtotal=>$6,p_sort=>$7,p_limit=>$8,p_cursor=>$9,p_expected_dataset_revision=>$10,p_expected_query_fingerprint=>$11)j",[org,extra.mode||'bounded',extra.mode==='known_history'?null:'2026-01-01',extra.channel??null,extra.min??null,extra.max??null,extra.sort||'customer_id_asc',extra.limit||100,extra.cursor||null,extra.rev||null,extra.fp||null]);
  let first=(await call()).rows[0].j;if(first.items.length!==100||Number(first.full_cohort_totals.customer_count)!==204||!first.has_more)throw Error('full cohort page one failed '+JSON.stringify(first.full_cohort_totals));
  let ids=[...first.items.map(x=>x.effective_customer_id)],p=first;while(p.has_more){p=(await call({cursor:p.next_cursor,rev:p.dataset_revision,fp:p.query_fingerprint})).rows[0].j;if(Number(p.full_cohort_totals.customer_count)!==204)throw Error('page totals drifted');ids.push(...p.items.map(x=>x.effective_customer_id))}if(ids.length!==204||new Set(ids).size!==204||ids.slice(0,100).includes(target))throw Error('cursor traversal failed');
  for(const sort of['display_name_asc','known_official_subtotal_asc','known_official_subtotal_desc']){let q=(await call({sort,limit:37})).rows[0].j,seen=[];for(;;){seen.push(...q.items.map(v=>v.effective_customer_id));if(!q.has_more)break;q=(await call({sort,limit:37,cursor:q.next_cursor,rev:q.dataset_revision,fp:q.query_fingerprint})).rows[0].j}if(seen.length!==204||new Set(seen).size!==204)throw Error(sort+' traversal failed');const order=sort==='display_name_asc'?'lower(c.display_name)collate"C",c.display_name collate"C",c.id':sort==='known_official_subtotal_asc'?'l.merchandise_net,c.id':'l.merchandise_net desc,c.id';const expected=(await s.query(`select c.id from public.e10_customers c join public.e10_customer_transactions t on(t.organization_id,t.customer_id)=(c.organization_id,c.id)join public.e10_customer_transaction_lines l on(l.organization_id,l.transaction_id)=(t.organization_id,t.id)where c.organization_id=$1 and t.occurred_at>='2026-01-01'order by ${order}`,[org])).rows.map(r=>r.id);if(JSON.stringify(seen)!==JSON.stringify(expected))throw Error(sort+' ordering mismatch')}
  const forged={...first.next_cursor,display_name:'zzzz',normalized_display_name:'zzzz',known_official_subtotal:'-999'};const forgedPage=(await call({cursor:forged,rev:first.dataset_revision,fp:first.query_fingerprint})).rows[0].j;const honestPage=(await call({cursor:first.next_cursor,rev:first.dataset_revision,fp:first.query_fingerprint})).rows[0].j;if(JSON.stringify(forgedPage.items)!==JSON.stringify(honestPage.items))throw Error('forged cursor tuple steered page');
  const filtered=(await call({channel:(await s.query("select sales_channel from public.e10_customer_transaction_lines l join public.e10_customer_transactions t on t.id=l.transaction_id where t.customer_id=$1",[target])).rows[0].sales_channel,min:900,max:1000,sort:'known_official_subtotal_desc'})).rows[0].j;if(filtered.items.length!==1||filtered.items[0].effective_customer_id!==target||Number(filtered.full_cohort_totals.known_official_subtotal)!==999)throw Error('server aggregate filter failed '+JSON.stringify(filtered));
  await s.query("insert into public.e10_organization_role_permissions values($1,$2,'act.view_customer_engagement',true)",[org,role]);
  const life=(await call({mode:'known_history',min:900,max:1000})).rows[0].j;if(life.items[0].effective_customer_id!==target||life.items[0].attended_ratio_status!=='unsupported_known_history_window'||life.coverage.source_history_completeness!=='unknown')throw Error('known history failed '+JSON.stringify(life));
  const lifeAll=(await call({mode:'known_history'})).rows[0].j;if(Number(lifeAll.full_cohort_totals.customer_count)!==205)throw Error('known history omitted old row '+JSON.stringify(lifeAll.full_cohort_totals));
  const x8=(await a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)j",[org,x8ctx,{window_mode:'known_history',from:null,to:'2026-02-01T00:00:00Z',observation_cutoff:'2026-02-01T00:00:00Z',currency:'USD',timezone:'UTC',week_start:1,min_known_official_subtotal:'900',max_known_official_subtotal:'1000',sort:'display_name_asc',limit:1}])).rows[0].j;if(x8.result.items.length!==1||'display_name'in x8.result.items[0]||x8.result.next_cursor&&('display_name'in x8.result.next_cursor||'normalized_display_name'in x8.result.next_cursor))throw Error('X8 v2 projection leaked name '+JSON.stringify(x8));
  const x8page=(await a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)j",[org,x8ctx,{window_mode:'bounded',from:'2026-01-01T00:00:00Z',to:'2026-02-01T00:00:00Z',observation_cutoff:'2026-02-01T00:00:00Z',currency:'USD',timezone:'UTC',week_start:1,sort:'display_name_asc',limit:1,cursor:null}])).rows[0].j;if(!x8page.result.next_cursor||'display_name'in x8page.result.next_cursor)throw Error('X8 redacted cursor missing');const x8next=(await a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)j",[org,x8ctx,{window_mode:'bounded',from:'2026-01-01T00:00:00Z',to:'2026-02-01T00:00:00Z',observation_cutoff:'2026-02-01T00:00:00Z',currency:'USD',timezone:'UTC',week_start:1,sort:'display_name_asc',limit:1,cursor:x8page.result.next_cursor,expected_dataset_revision:x8page.result.dataset_revision,expected_query_fingerprint:x8page.result.query_fingerprint}])).rows[0].j;if(!x8next.result.items.length||'display_name'in x8next.result.items[0])throw Error('X8 redacted cursor continuation failed');
  if(!await denied(a.query("select public.e10_org_typed_query($1,$2,'customer.spend_summary',$3)",[org,x8ctx,{window_mode:'known_history',from:null,to:'2026-02-01',observation_cutoff:'2026-02-01',currency:'USD',timezone:'UTC',week_start:1,limit:1,after_customer_id:target}]),'22023','x8_query_args_invalid'))throw Error('mixed v1/v2 cursor accepted');
  const renamePage=(await call({sort:'display_name_asc',limit:1})).rows[0].j;await s.query('set session_replication_role=origin');await s.query("update public.e10_customers set display_name='Renamed customer'where organization_id=$1 and id=$2",[org,target]);await s.query('set session_replication_role=replica');if(!await denied(call({sort:'display_name_asc',limit:1,cursor:renamePage.next_cursor,rev:renamePage.dataset_revision,fp:renamePage.query_fingerprint}),'40001','customer_spend_revision_stale'))throw Error('rename did not invalidate cursor');
  if(!await denied(h.query("select public.e10_org_customer_spend_grid_v2(p_org=>$1,p_window_mode=>'bounded',p_from=>'2026-01-01',p_to=>'2026-02-01',p_observation_cutoff=>'2026-02-01',p_currency=>'USD',p_timezone=>'UTC',p_week_start=>1)",[org]),'42501','customer_spend_denied'))throw Error('hostile member allowed');
  ok=true;
 }finally{for(const q of[a,h]){await q.query('reset role').catch(()=>{})}await s.query('set session_replication_role=replica');for(const t of['e10_query_context_commands','e10_query_contexts','e10_customer_transaction_lines','e10_customer_transactions','e10_reporting_dataset_revisions','e10_locations','e10_customers','e10_organization_role_permissions','e10_organization_memberships','e10_organization_roles'])await s.query(`delete from public.${t} where organization_id in($1,$2)`,[org,org2]);await s.query('delete from public.e10_organizations where id in($1,$2)',[org,org2]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id in($1,$2)',[user,hostile]);await Promise.all([s.end(),a.end(),h.end()])}
 if(ok)console.log('TA-X7f customer spend grid: PASS');
}main().catch(e=>{console.error(e);process.exit(1)});
