const {Client}=require('pg');const{randomUUID}=require('crypto');
const db=process.env.E10_DB_URL||'postgresql://postgres:postgres@127.0.0.1:54322/postgres',WAIT=8000;
const guarded=p=>{p.catch(()=>{});return p};
const bounded=p=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(Error('TA-X7d.3 bounded completion timeout')),WAIT))]);
async function client(){const c=new Client({connectionString:db});await c.connect();await c.query("set statement_timeout='8s';set lock_timeout='7s'");return c}
async function jwt(c,u){await c.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:u,role:'authenticated'})]);await c.query('set role authenticated')}
async function waitBlocked(s,pid,blocker,label,kind){const until=Date.now()+WAIT;while(Date.now()<until){const q=await s.query("select $2=any(pg_blocking_pids(a.pid)) intended,a.wait_event_type,exists(select 1 from pg_locks l where l.pid=a.pid and not l.granted and l.locktype='advisory') advisory_wait from pg_stat_activity a where a.pid=$1",[pid,blocker]);const v=q.rows[0];if(v?.intended&&v.wait_event_type==='Lock'&&(kind!=='advisory'||v.advisory_wait)){console.log(`[proof] ${label}: exact backend pid=${pid} blocked by pid=${blocker}`);return}await new Promise(r=>setTimeout(r,25))}throw Error(`timeout establishing ${label}`)}
async function denied(p){try{await bounded(p);return false}catch(e){if(e.code!=='42501')throw e;return true}}
const call=(c,o,mode='none',kind=null,grouping='entity',limit=50,filters={})=>c.query("select public.e10_org_market_screener($1,'catalog',$5,'count','completed_sale','2026-01-01','2026-02-01','2026-02-01',$2,$3,$4,null,$7,'cohort_asc',$6,null) r",[o,mode==='none'?null:'USD',mode,kind,grouping,limit,filters]);
async function main(){const s=await client(),lock=await client(),b=await client();const x={org:randomUUID(),u:randomUUID(),role:randomUUID(),source:'fresh-'+randomUUID(),rel:randomUUID(),variant:randomUUID(),variant2:randomUUID(),a:randomUUID(),b:randomUUID()};let pending=null,ok=false;const bp=(await b.query('select pg_backend_pid() pid')).rows[0].pid,lp=(await lock.query('select pg_backend_pid() pid')).rows[0].pid;
 try{
  await s.query("insert into auth.users(id,instance_id,aud,role,email,created_at,updated_at)values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,now(),now())",[x.u,`x7d3-${x.u}@x.invalid`]);
  await s.query("insert into public.e10_organizations(id,slug,name)values($1,$2,'X7d3 race')",[x.org,'x7d3-'+x.org.slice(0,8)]);await s.query("insert into public.e10_organization_roles(id,organization_id,key,name,is_system)values($1,$2,'reader','Reader',false)",[x.role,x.org]);await s.query("insert into public.e10_organization_memberships(organization_id,user_id,role_id,status)values($1,$2,$3,'active')",[x.org,x.u,x.role]);await s.query("insert into public.e10_organization_role_permissions(organization_id,role_id,capability,allowed)values($1,$2,'act.view_market_analytics',true)",[x.org,x.role]);await jwt(b,x.u);
  await s.query("with r as(insert into public.e10_catalog_releases(id,release_name,release_year,sport)values($1,'X7d3',2026,'baseball')returning id)insert into public.e10_catalog_variants(id,release_id,card_number)select v.id,r.id,v.n from r cross join(values($2::uuid,'1'),($3::uuid,'2'))v(id,n)",[x.rel,x.variant,x.variant2]);
  await s.query('set session_replication_role=replica');await s.query("insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,occurred_at,currency,amount,quantity,source_kind,source_connection_id,raw_payload_snapshot)values($1,$3,'completed_sale',$4,'2026-01-10 00:00:00.000001Z','USD',10,1,'manual','fixture','{}'),($2,$3,'completed_sale',$4,'2026-01-10 00:00:00.000002Z','USD',20,1,'manual','fixture','{}')",[x.a,x.b,x.org,x.variant]);await s.query('set session_replication_role=origin');
  await s.query("insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values($1,gen_random_uuid(),$2,1,'assert','raw',1,'unit_price',10,'x','{}',$4,'fp'),($1,gen_random_uuid(),$3,1,'assert','raw',1,'unit_price',20,'x','{}',$5,'fp')",[x.org,x.a,x.b,'x7d3-a-'+x.a,'x7d3-b-'+x.b]);

  // Catalog revision lock: authority revoked while this exact reader backend waits.
  await lock.query('begin');await lock.query('select revision from public.e10_market_catalog_revision where singleton for update');pending=guarded(call(b,x.org));await waitBlocked(s,bp,lp,'catalog revision reader','row');await s.query("update public.e10_organization_role_permissions set allowed=false where organization_id=$1 and role_id=$2 and capability='act.view_market_analytics'",[x.org,x.role]);await lock.query('commit');if(!await denied(pending))throw Error('catalog-lock post-wait revocation allowed');pending=null;console.log('[proof] catalog revision post-wait authorization recheck denied');await s.query("update public.e10_organization_role_permissions set allowed=true where organization_id=$1 and role_id=$2 and capability='act.view_market_analytics'",[x.org,x.role]);

  // Organization revision lock: the same post-wait authority rule applies independently.
  await lock.query('begin');await lock.query('select revision from public.e10_market_org_revisions where organization_id=$1 for update',[x.org]);pending=guarded(call(b,x.org));await waitBlocked(s,bp,lp,'organization revision reader','row');await s.query("update public.e10_organization_memberships set status='suspended' where organization_id=$1 and user_id=$2",[x.org,x.u]);await lock.query('commit');if(!await denied(pending))throw Error('org-lock post-wait revocation allowed');pending=null;console.log('[proof] organization revision post-wait authorization recheck denied');await s.query("update public.e10_organization_memberships set status='active' where organization_id=$1 and user_id=$2",[x.org,x.u]);

  // Source resolution occurs after both revision locks, so it cannot mix an old source set with a new revision.
  await lock.query('begin');await lock.query('select revision from public.e10_market_catalog_revision where singleton for update');pending=guarded(call(b,x.org,'all_reviewed_connections','manual'));await waitBlocked(s,bp,lp,'source snapshot reader','row');await s.query("insert into public.e10_market_observation_coverage_decisions(organization_id,decision_key,observation_kind,source_kind,source_connection_id,currency,covered_from,covered_to,revision,action,coverage_status,reason,evidence,idempotency_key,request_fingerprint)values($1,gen_random_uuid(),'completed_sale','manual',$2,'USD','2026-01-01','2026-02-01',1,'assert','complete','race','{}',$3,'race')",[x.org,x.source,'x7d3-'+x.source]);const expectedRev=Number((await s.query('select revision from public.e10_market_org_revisions where organization_id=$1',[x.org])).rows[0].revision);await lock.query('commit');const fresh=(await bounded(pending)).rows[0].r;pending=null;if(JSON.stringify(fresh.resolved_source_universe)!==JSON.stringify([x.source])||Number(fresh.organization_revision)!==expectedRev)throw Error(`post-wait source/revision mismatch: ${JSON.stringify(fresh)}`);console.log('[proof] source universe resolved after snapshot wait at matching org revision');

  // Context/cursor state is transactional: revocation during its advisory wait rolls the whole statement back.
  const fixtureFilter={release_id:x.rel},counts=async()=>{const q=await s.query('select count(distinct q.id)::int contexts,count(c.id)::int cursors from public.e10_market_query_contexts q left join public.e10_market_query_cursors c on c.context_id=q.id where q.organization_id=$1 and q.actor_id=$2',[x.org,x.u]);return q.rows[0]};const positiveScreen=(await call(b,x.org,'none',null,'variant',1,fixtureFilter)).rows[0].r;if(!positiveScreen.next_cursor)throw Error('fixture did not force screener cursor');let before=await counts();await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.org+'|'+x.u+'|market-query-state']);pending=guarded(call(b,x.org,'none',null,'variant',1,fixtureFilter));await waitBlocked(s,bp,lp,'screener query-state reader','advisory');await s.query("update public.e10_organization_role_permissions set allowed=false where organization_id=$1 and role_id=$2 and capability='act.view_market_analytics'",[x.org,x.role]);await lock.query('commit');if(!await denied(pending))throw Error('screener query-state post-wait revocation allowed');pending=null;let after=await counts();if(JSON.stringify(after)!==JSON.stringify(before))throw Error(`denied screener left query-state residue: ${JSON.stringify({before,after})}`);console.log('[proof] screener denial rolled back forced context and cursor');await s.query("update public.e10_organization_role_permissions set allowed=true where organization_id=$1 and role_id=$2 and capability='act.view_market_analytics'",[x.org,x.role]);
  const parent=(await call(b,x.org,'none',null,'variant',50,fixtureFilter)).rows[0].r,cohort=parent.rows.find(r=>r.observed_count===2)?.cohort_key;if(!cohort)throw Error('fixture observation cohort missing');const positiveDrill=(await b.query("select public.e10_org_market_observation_drilldown($1,$2,$3,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,null) r",[x.org,parent.query_fingerprint,cohort])).rows[0].r;if(!positiveDrill.next_cursor||positiveDrill.rows[0].observation_id!==x.b)throw Error('drill first page/cursor order failed');const secondDrill=(await b.query("select public.e10_org_market_observation_drilldown($1,$2,$3,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,$4) r",[x.org,parent.query_fingerprint,cohort,positiveDrill.next_cursor])).rows[0].r;if(secondDrill.rows[0].observation_id!==x.a)throw Error('distinct-microsecond second page order failed');before=await counts();await lock.query('begin');await lock.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[x.org+'|'+x.u+'|market-query-state']);pending=guarded(b.query("select public.e10_org_market_observation_drilldown($1,$2,$3,'completed_sale','2026-01-01','2026-02-01','2026-02-01',null,'none',null,null,1,null) r",[x.org,parent.query_fingerprint,cohort]));await waitBlocked(s,bp,lp,'drilldown query-state reader','advisory');await s.query("update public.e10_organization_role_permissions set allowed=false where organization_id=$1 and role_id=$2 and capability='act.view_market_analytics'",[x.org,x.role]);await lock.query('commit');if(!await denied(pending))throw Error('drilldown query-state post-wait revocation allowed');pending=null;after=await counts();if(JSON.stringify(after)!==JSON.stringify(before))throw Error(`denied drilldown left query-state residue: ${JSON.stringify({before,after})}`);console.log('[proof] drilldown denial rolled back forced context and cursor');ok=true;
 }finally{let residue=0;await lock.query('rollback').catch(()=>{});if(pending){await s.query('select pg_cancel_backend($1)',[bp]).catch(()=>{});await Promise.allSettled([pending])}await b.query('reset role').catch(()=>{});try{await s.query('set session_replication_role=replica');for(const t of['e10_market_query_cursors','e10_market_query_contexts','e10_market_observation_fact_decisions','e10_market_observation_coverage_decisions','e10_market_observations','e10_market_org_revisions','e10_organization_memberships','e10_organization_role_permissions','e10_organization_roles'])await s.query(`delete from public.${t} where organization_id=$1`,[x.org]);await s.query('delete from public.e10_organizations where id=$1',[x.org]);await s.query('delete from public.e10_catalog_variants where id=any($1)',[[x.variant,x.variant2]]);await s.query('delete from public.e10_catalog_releases where id=$1',[x.rel]);await s.query('set session_replication_role=origin');await s.query('delete from auth.users where id=$1',[x.u]);residue=Number((await s.query("select(select count(*)from public.e10_organizations where id=$1)+(select count(*)from auth.users where id=$2)+(select count(*)from public.e10_market_query_contexts where organization_id=$1)+(select count(*)from public.e10_market_query_cursors where organization_id=$1)n",[x.org,x.u])).rows[0].n)}finally{await s.query('set session_replication_role=origin').catch(()=>{});await Promise.allSettled([s.end(),lock.end(),b.end()])}if(residue)throw Error(`X7d.3 cleanup residue ${residue}`)}if(ok)console.log('TA-X7d.3 market read concurrency: PASS')}
main().catch(e=>{console.error(e.stack);process.exit(1)});
