\set ON_ERROR_STOP on
do $$declare n int;begin
 select count(*)into n from pg_class c join pg_namespace s on s.oid=c.relnamespace where s.nspname='public'and c.relname in('e10_unique_item_facet_decisions','e10_market_observation_fact_decisions','e10_market_observation_equivalence_decisions','e10_market_observation_coverage_decisions')and c.relrowsecurity;
 if n<>4 then raise exception'evidence RLS count %',n;end if;
 if exists(select 1 from information_schema.role_table_grants where table_schema='public'and table_name like'e10%decisions'and grantee in('anon','authenticated'))then raise exception'evidence client grant leak';end if;
end $$;
begin;
do $$
declare o uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();r uuid:=gen_random_uuid();v uuid:=gen_random_uuid();p uuid:=gen_random_uuid();p2 uuid:=gen_random_uuid();u uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();d uuid:=gen_random_uuid();e uuid:=gen_random_uuid();f uuid:=gen_random_uuid();g uuid:=gen_random_uuid();h uuid:=gen_random_uuid();j uuid:=gen_random_uuid();k uuid:=gen_random_uuid();dk uuid:=gen_random_uuid();ek uuid:=gen_random_uuid();ck uuid:=gen_random_uuid();fact_key uuid:=gen_random_uuid();e1 uuid;cv1 uuid;fact1 uuid;fp1 text;fp2 text;rev0 bigint;rev2 bigint;chain_ids uuid[]:=array[]::uuid[];tail_ids uuid[]:=array[]::uuid[];i integer;
begin
 insert into public.e10_organizations(id,slug,name)values(o,'x7de-'||substr(o::text,1,8),'X7d evidence'),(o2,'x7de-'||substr(o2::text,1,8),'X7d evidence 2');
 insert into public.e10_catalog_releases(id,release_name)values(r,'X7d');insert into public.e10_players(id,name)values(p,'Subject'),(p2,'Foreign');insert into public.e10_catalog_variants(id,release_id)values(v,r);insert into public.e10_catalog_variant_subjects(variant_id,player_id)values(v,p);insert into public.e10_unique_items(id,organization_id,catalog_variant_id,item_kind)values(u,o,v,'card'),(u2,o,v,'card');
 set local session_replication_role=replica;
 insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,occurred_at,currency,amount,quantity,source_kind,raw_payload_snapshot)values(a,o,'completed_sale',v,'2026-01-01','USD',500,5,'manual','{}'),(b,o,'completed_sale',v,'2026-01-01','USD',500,5,'csv','{}'),(c,o2,'completed_sale',v,'2026-01-01','USD',500,5,'manual','{}'),(d,o,'completed_sale',v,'2026-01-02','USD',500,5,'manual','{}'),(e,o,'completed_sale',v,'2026-01-02','USD',500,5,'csv','{}'),(f,o,'completed_sale',v,'2026-01-03','USD',25,null,'manual','{}'),(g,o,'completed_sale',v,'2026-01-04','USD',25,null,'manual','{}'),(h,o,'completed_sale',v,'2026-01-06','USD',25,null,'manual','{}'),(j,o,'completed_sale',v,'2026-01-07','USD',500,5,'manual','{}'),(k,o,'completed_sale',v,'2026-01-08','USD',25,null,'manual','{}');
 for i in 1..34 loop chain_ids:=array_append(chain_ids,gen_random_uuid());tail_ids:=array_append(tail_ids,gen_random_uuid());insert into public.e10_market_observations(id,organization_id,observation_kind,catalog_variant_id,occurred_at,currency,amount,quantity,source_kind,raw_payload_snapshot)values(chain_ids[i],o,'asking_price',v,'2026-01-05','USD',10,1,'manual','{}'),(tail_ids[i],o,'asking_price',v,'2026-01-09','USD',10,1,'manual','{}');end loop;
 set local session_replication_role=origin;
 select revision into rev0 from public.e10_market_org_revisions where organization_id=o;select revision into rev2 from public.e10_market_org_revisions where organization_id=o2;

 insert into public.e10_unique_item_facet_decisions(organization_id,decision_key,unique_item_id,subject_id,revision,action,jersey_match,pictured_number,reason,evidence,idempotency_key,request_fingerprint)values(o,dk,u,p,1,'assert',true,'10','x','{}','copy1','fp');
 insert into public.e10_unique_item_facet_decisions(organization_id,decision_key,unique_item_id,subject_id,revision,action,marking_text,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),u2,p,1,'assert','factory dot','x','{}','copy-marking-only','fp');
 begin insert into public.e10_unique_item_facet_decisions(organization_id,decision_key,unique_item_id,subject_id,revision,action,jersey_match,pictured_number,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),u,p2,1,'assert',true,'11','x','{}','copy-bad-subject','fp');raise exception'foreign copy subject accepted';exception when check_violation then null;end;

 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,fact_key,a,1,'assert','raw',5,'transaction_total',100,'x','{}','fact1','fp')returning id into fact1;
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),b,1,'assert','raw',5,'transaction_total',100,'x','{}','fact2','fp');
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,grader_code,grade_label,serial_numerator,serial_denominator,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),f,1,'assert','graded','PSA','10',1,25,'x','{}','fact-graded-partial','fp');
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,transaction_quantity,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),g,1,'assert',2,'x','{}','fact-quantity-only','fp');
 begin insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),h,1,'assert','graded','x','{}','fact-graded-missing-labels','fp');raise exception'graded fact without grader/grade accepted';exception when check_violation then null;end;
 begin insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,grader_code,grade_label,transaction_quantity,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),k,1,'assert','PSA','10',1,'x','{}','fact-null-condition-graded','fp');raise exception'NULL condition with grade fields accepted';exception when check_violation then null;end;
 begin insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),j,1,'assert','raw',5,'transaction_total',99,'x','{}','fact-bad-unit','fp');raise exception'nonconserving amount accepted';exception when check_violation then null;end;

 fp1:=e10.market_observation_fingerprint(o,a);fp2:=e10.market_observation_fingerprint(o,b);insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,ek,a,b,1,'link',fp1,fp2,'x','{}','eq1','fp')returning id into e1;
 begin insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),b,a,1,'link',fp2,fp1,'x','{}','eq-cycle','fp');raise exception'equivalence cycle accepted';exception when check_violation then null;end;
 begin insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),a,c,1,'link',fp1,e10.market_observation_fingerprint(o2,c),'x','{}','eq-cross-org','fp');raise exception'cross-org equivalence accepted';exception when check_violation then null;end;

 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,grader_code,grade_label,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),d,1,'assert','graded','PSA','10',5,'transaction_total',100,'x','{}','fact-cohort-total','fp');
 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,grader_code,grade_label,transaction_quantity,amount_basis,reviewed_unit_amount,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),e,1,'assert','graded','PSA','10',5,'unit_price',500,'x','{}','fact-cohort-unit','fp');
 begin insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),d,e,1,'link',e10.market_observation_fingerprint(o,d),e10.market_observation_fingerprint(o,e),'x','{}','eq-incompatible-facts','fp');raise exception'incompatible fact cohorts accepted';exception when check_violation then null;end;

 insert into public.e10_market_observation_fact_decisions(organization_id,decision_key,observation_id,revision,action,condition_state,transaction_quantity,amount_basis,reviewed_unit_amount,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,fact_key,a,2,'assert','raw',5,'unit_price',500,fact1,'corrected','{}','fact1-correction','fp');
 if not exists(select 1 from public.e10_market_observation_equivalence_status where id=e1 and review_status='review_required')then raise exception'stale equivalence not review_required';end if;if exists(select 1 from public.e10_current_market_observation_equivalences where id=e1)then raise exception'stale equivalence remained current';end if;

 for i in 2..32 loop insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),chain_ids[i],chain_ids[i+1],1,'link',e10.market_observation_fingerprint(o,chain_ids[i]),e10.market_observation_fingerprint(o,chain_ids[i+1]),'x','{}','chain-'||i,'fp');end loop;
 insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),chain_ids[1],chain_ids[2],1,'link',e10.market_observation_fingerprint(o,chain_ids[1]),e10.market_observation_fingerprint(o,chain_ids[2]),'x','{}','chain-1','fp');
 begin insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),chain_ids[33],chain_ids[1],1,'link',e10.market_observation_fingerprint(o,chain_ids[33]),e10.market_observation_fingerprint(o,chain_ids[1]),'x','{}','chain-cycle','fp');raise exception'32-hop cycle accepted';exception when check_violation then null;end;
 begin insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),chain_ids[34],chain_ids[1],1,'link',e10.market_observation_fingerprint(o,chain_ids[34]),e10.market_observation_fingerprint(o,chain_ids[1]),'x','{}','chain-depth-33','fp');raise exception'33-hop chain accepted';exception when check_violation then null;end;

 for i in 1..32 loop insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),tail_ids[i],tail_ids[i+1],1,'link',e10.market_observation_fingerprint(o,tail_ids[i]),e10.market_observation_fingerprint(o,tail_ids[i+1]),'x','{}','tail-chain-'||i,'fp');end loop;
 begin insert into public.e10_market_observation_equivalence_decisions(organization_id,decision_key,duplicate_observation_id,canonical_observation_id,revision,action,duplicate_fingerprint,canonical_fingerprint,reason,evidence,idempotency_key,request_fingerprint)values(o,gen_random_uuid(),tail_ids[33],tail_ids[34],1,'link',e10.market_observation_fingerprint(o,tail_ids[33]),e10.market_observation_fingerprint(o,tail_ids[34]),'x','{}','tail-chain-depth-33','fp');raise exception'33-hop tail append accepted';exception when check_violation then null;end;

 insert into public.e10_market_observation_coverage_decisions(organization_id,decision_key,observation_kind,source_kind,source_connection_id,currency,covered_from,covered_to,revision,action,coverage_status,reason,evidence,idempotency_key,request_fingerprint)values(o,ck,'completed_sale','csv','shop-a','USD','2026-01-01','2026-02-01',1,'assert','complete','x','{}','cov1','fp')returning id into cv1;
 insert into public.e10_market_observation_coverage_decisions(organization_id,decision_key,observation_kind,source_kind,source_connection_id,currency,covered_from,covered_to,revision,action,coverage_status,supersedes_decision_id,reason,evidence,idempotency_key,request_fingerprint)values(o,ck,'completed_sale','csv','shop-a','USD','2026-01-01','2026-02-01',2,'assert','partial',cv1,'x','{}','cov2','fp');
 if not exists(select 1 from public.e10_current_market_observation_coverage where organization_id=o and decision_key=ck and coverage_status='partial')then raise exception'coverage terminal wrong';end if;if(select revision from public.e10_market_org_revisions where organization_id=o)<=rev0 then raise exception'org revision did not advance';end if;if(select revision from public.e10_market_org_revisions where organization_id=o2)<>rev2 then raise exception'foreign org revision advanced';end if;
end $$;
rollback;
select'TA-X7d.0 market evidence storage PASS'as result;
