-- TA-X7d.2h contributing canonical observations and bounded public drill-down.
create function e10.market_drilldown_rows(p_org uuid,p_request jsonb,p_cohort_key text)
returns table(observation_id uuid,occurred_at timestamptz,row_data jsonb)language sql stable security definer set search_path=public as $$
with p as(select p_request->>'scope'scope,p_request->>'grouping'grouping,p_request->>'metric'metric,p_request->>'observation_kind'kind,(p_request->>'observed_from')::timestamptz observed_from,(p_request->>'observed_to')::timestamptz observed_to,(p_request->>'as_of')::timestamptz as_of,p_request->>'currency'currency,p_request->>'source_mode'source_mode,p_request->>'source_kind'source_kind,p_request->'resolved_source_universe'sources,p_request->'filters'f),
base as(
 select o.*,case p.scope when'catalog'then o.catalog_variant_id when'owned'then o.unique_item_id else o.observation_id end entity_id,u.serial_numerator owned_serial_numerator
 from public.e10_market_eligible_canonical_observations o cross join p left join public.e10_unique_items u on u.organization_id=o.organization_id and u.id=o.unique_item_id
 where o.organization_id=p_org and o.observation_kind=p.kind and o.occurred_at>=p.observed_from and o.occurred_at<p.observed_to and o.occurred_at<=p.as_of and(p.currency is null or o.currency=p.currency)
 and(p.scope<>'catalog'or o.catalog_variant_id is not null)and(p.scope<>'owned'or o.unique_item_id is not null)and(p.source_mode='none'or jsonb_array_length(p.sources)>0 and e10.market_provenance_matches(p_org,o.provenance_observation_ids,p.source_kind,p.sources))
),filtered as(select b.*from base b,p where
 (not(p.f?'sport')or b.sport=p.f->>'sport')and(not(p.f?'league')or exists(select 1 from public.e10_catalog_releases rr where rr.id=b.release_id and rr.league=p.f->>'league'))and(not(p.f?'subject_id')or(p.f->>'subject_id')::uuid=any(b.subject_ids))and
 (not(p.f?'manufacturer')or b.manufacturer=p.f->>'manufacturer')and(not(p.f?'brand_line')or b.brand_line=p.f->>'brand_line')and(not(p.f?'release_id')or b.release_id=(p.f->>'release_id')::uuid)and(not(p.f?'release_name')or b.release_name=p.f->>'release_name')and
 (not(p.f?'release_year')or b.release_year=(p.f->>'release_year')::integer)and(not(p.f?'release_year_from')or b.release_year>=(p.f->>'release_year_from')::integer)and(not(p.f?'release_year_to')or b.release_year<=(p.f->>'release_year_to')::integer)and(not(p.f?'season_from')or b.release_season>=p.f->>'season_from')and(not(p.f?'season_to')or b.release_season<=p.f->>'season_to')and
 (not(p.f?'language')or coalesce(b.variant_language,b.release_language)=p.f->>'language')and(not(p.f?'region')or b.region=p.f->>'region')and(not(p.f?'edition')or coalesce(b.variant_edition,b.release_edition)=p.f->>'edition')and(not(p.f?'card_number')or b.card_number=p.f->>'card_number')and(not(p.f?'exact_parallel')or b.exact_parallel=p.f->>'exact_parallel')and
 (not(p.f?'color_family_term_id')or b.color_family_term_id=(p.f->>'color_family_term_id')::uuid)and(not(p.f?'finish_family_term_id')or b.finish_family_term_id=(p.f->>'finish_family_term_id')::uuid)and
 (not(p.f?'rookie_designation')or case when p.f?'subject_id'then b.rookie_designation_by_subject->(p.f->>'subject_id')->>'value'=p.f->>'rookie_designation'else b.rookie_designation=(p.f->>'rookie_designation')::boolean end)and(not(p.f?'rookie_season')or case when p.f?'subject_id'then b.rookie_season_by_subject->(p.f->>'subject_id')->>'value'=p.f->>'rookie_season'else exists(select 1 from jsonb_each(b.rookie_season_by_subject)x where x.value->>'value'=p.f->>'rookie_season')end)and
 (not(p.f?'variant_print_run_denominator')or b.print_run_denominator=(p.f->>'variant_print_run_denominator')::integer)and
 ((p.f->>'exact_subject')::boolean is not true or p.scope<>'owned'or exists(select 1 from public.e10_current_unique_item_facets x where x.organization_id=p_org and x.unique_item_id=b.unique_item_id and x.subject_id=(p.f->>'subject_id')::uuid))and
 ((p.f->>'exact_subject')::boolean is not true or p.scope<>'completed_sale_observation'or b.observation_subject_id=(p.f->>'subject_id')::uuid)and
 (p.scope<>'owned'or not(p.f?'serial_numerator')or b.owned_serial_numerator=(p.f->>'serial_numerator')::integer)and(p.scope<>'owned'or not(p.f?'jersey_match')or exists(select 1 from public.e10_current_unique_item_facets x where x.organization_id=p_org and x.unique_item_id=b.unique_item_id and x.jersey_match=(p.f->>'jersey_match')::boolean and(not(p.f?'subject_id')or x.subject_id=(p.f->>'subject_id')::uuid)))and
 (not(p.f?'condition_state')or b.condition_state=p.f->>'condition_state')and(not(p.f?'graded')or case when(p.f->>'graded')::boolean then b.condition_state='graded'else b.condition_state='raw'end)and(not(p.f?'grader_code')or b.grader_code=p.f->>'grader_code')and(not(p.f?'grade_label')or b.grade_label=p.f->>'grade_label')and(not(p.f?'grade_qualifier')or b.grade_qualifier=p.f->>'grade_qualifier')and
 (p.scope='owned'or not(p.f?'serial_numerator')or b.serial_numerator=(p.f->>'serial_numerator')::integer)and(not(p.f?'observed_serial_denominator')or b.serial_denominator=(p.f->>'observed_serial_denominator')::integer)and(p.scope='owned'or not(p.f?'jersey_match')or b.jersey_match=(p.f->>'jersey_match')::boolean)and
 (not(p.f?'amount_min')or(case when p.metric='transaction_total'then b.transaction_total_amount else b.reviewed_unit_price_amount end)>=(p.f->>'amount_min')::numeric)and(not(p.f?'amount_max')or(case when p.metric='transaction_total'then b.transaction_total_amount else b.reviewed_unit_price_amount end)<=(p.f->>'amount_max')::numeric)
),expanded as(select b.*,s.subject_id grouping_subject,case when p.metric<>'count'or p.grouping in('variant_condition','variant_grader_grade')then b.condition_state end gc,case when p.metric<>'count'or p.grouping='variant_grader_grade'then b.grader_code end gg,case when p.metric<>'count'or p.grouping='variant_grader_grade'then b.grade_label end gl,case when p.metric<>'count'or p.grouping='variant_grader_grade'then b.grade_qualifier end gq,case p.grouping when'entity'then b.entity_id when'variant'then b.catalog_variant_id when'variant_condition'then b.catalog_variant_id when'variant_grader_grade'then b.catalog_variant_id when'release'then b.release_id when'color'then b.color_family_term_id when'finish'then b.finish_family_term_id else s.subject_id end gid from filtered b,p cross join lateral(select x subject_id from unnest(case when p.grouping='subject'and cardinality(b.subject_ids)>0 then b.subject_ids else array[null::uuid]end)x)s),
keyed as(select x.*,encode(sha256(convert_to(jsonb_build_array('market-cohort-v1',p.scope,p.grouping,x.gid,x.gc,x.gg,x.gl,x.gq)::text,'UTF8')),'hex')ck from expanded x,p)
select k.observation_id,k.occurred_at,jsonb_build_object('observation_id',k.observation_id,'canonical_observation_id',k.canonical_observation_id,'occurred_at',k.occurred_at,'observation_kind',k.observation_kind,'currency',k.currency,'transaction_total_amount',k.transaction_total_amount,'reviewed_unit_price_amount',k.reviewed_unit_price_amount,'known_unit_quantity',k.known_unit_quantity,'condition_state',k.condition_state,'grader_code',k.grader_code,'grade_label',k.grade_label,'grade_qualifier',k.grade_qualifier,'serial_numerator',k.serial_numerator,'serial_denominator',k.serial_denominator,'jersey_match',k.jersey_match,'observation_subject_id',k.observation_subject_id,'corrected_observation_ids',k.corrected_observation_ids,'linked_provenance_count',k.provenance_count,'provenance',case when p.source_mode='none'then'[]'::jsonb else coalesce((select jsonb_agg(jsonb_build_object('observation_id',m.id,'source_kind',m.source_kind,'source_connection_id',m.source_connection_id,'source_reference',m.source_reference)order by m.id)from public.e10_current_market_observations m where m.organization_id=p_org and m.id=any(k.provenance_observation_ids)and m.source_kind=p.source_kind and exists(select 1 from jsonb_array_elements(p.sources)s where jsonb_typeof(s.value)='null'and m.source_connection_id is null or jsonb_typeof(s.value)='string'and s.value#>>'{}'=m.source_connection_id)),'[]'::jsonb)end)from keyed k,p where k.ck=p_cohort_key
$$;
revoke all on function e10.market_drilldown_rows(uuid,jsonb,text)from public,anon,authenticated;grant execute on function e10.market_drilldown_rows(uuid,jsonb,text)to service_role;

create function public.e10_org_market_observation_drilldown(p_org uuid,p_parent_query_fingerprint text,p_cohort_key text,p_observation_kind text,p_observed_from timestamptz,p_observed_to timestamptz,p_as_of timestamptz,p_currency text,p_source_mode text,p_source_kind text,p_source_connections jsonb,p_limit integer default 50,p_cursor uuid default null)
returns jsonb language plpgsql volatile security definer set search_path=public as $$
declare actor uuid;org_rev bigint;cat_rev bigint;parent_req jsonb;src jsonb;resolved jsonb;req jsonb;fp text;ctx uuid;ids text[];page_ids text[];rows jsonb:='[]';material jsonb;pos jsonb;pos_time timestamptz;pos_id uuid;last_id uuid;last_time timestamptz;next_cursor uuid;n integer;
begin
 if p_parent_query_fingerprint is null or p_parent_query_fingerprint!~'^[0-9a-f]{64}$'or p_cohort_key is null or length(p_cohort_key)not between 1 and 256 or p_limit is null or p_limit not between 1 and 200 then raise exception using errcode='22023',message='market_drilldown_request_invalid';end if;
 select s.actor_id,s.organization_revision,s.catalog_revision into actor,org_rev,cat_rev from e10.lock_market_read_snapshot(p_org)s;
 select q.normalized_request,q.resolved_source_universe into parent_req,src from public.e10_market_query_contexts q where q.organization_id=p_org and q.actor_id=actor and q.endpoint='screener'and q.query_fingerprint=p_parent_query_fingerprint and q.organization_revision=org_rev and q.catalog_revision=cat_rev and q.expires_at>clock_timestamp()and p_cohort_key=any(q.cohort_keys);
 if not found then raise exception using errcode='22023',message='market_parent_context_invalid';end if;
 if p_source_mode='none'and p_currency is null then if p_source_kind is not null or p_source_connections is not null then raise exception using errcode='22023',message='market_source_universe_invalid';end if;resolved:='[]'::jsonb;else resolved:=e10.market_source_universe(p_org,p_source_mode,p_observation_kind,p_source_kind,p_currency,p_source_connections);end if;
 if parent_req->>'observation_kind'is distinct from p_observation_kind or parent_req->>'observed_from'is distinct from to_char(p_observed_from at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')or parent_req->>'observed_to'is distinct from to_char(p_observed_to at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')or parent_req->>'as_of'is distinct from to_char(p_as_of at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')or parent_req->>'currency'is distinct from p_currency or parent_req->>'source_mode'is distinct from p_source_mode or parent_req->>'source_kind'is distinct from p_source_kind or src is distinct from resolved then raise exception using errcode='22023',message='market_drilldown_parent_mismatch';end if;
 req:=jsonb_build_object('api_version','market-read-v1','parent_query_fingerprint',p_parent_query_fingerprint,'cohort_key',p_cohort_key,'observation_kind',p_observation_kind,'observed_from',parent_req->>'observed_from','observed_to',parent_req->>'observed_to','as_of',parent_req->>'as_of','currency',p_currency,'source_mode',p_source_mode,'source_kind',p_source_kind,'resolved_source_universe',src,'limit',p_limit);fp:=e10.market_query_fingerprint('market-read-v1',p_org,actor,'drilldown',req,src,org_rev,cat_rev);
 if p_cursor is not null then select c.sort_position,c.context_id into pos,ctx from public.e10_market_query_cursors c join public.e10_market_query_contexts q on q.organization_id=c.organization_id and q.id=c.context_id where c.id=p_cursor and c.organization_id=p_org and c.actor_id=actor and c.endpoint='drilldown'and c.query_fingerprint=fp and c.parent_cohort_key=p_cohort_key and c.organization_revision=org_rev and c.catalog_revision=cat_rev and c.expires_at>clock_timestamp()and q.organization_id=p_org and q.actor_id=actor and q.endpoint='drilldown'and q.query_fingerprint=fp and q.organization_revision=org_rev and q.catalog_revision=cat_rev and q.expires_at>clock_timestamp();if not found then raise exception using errcode='22023',message='market_cursor_invalid';end if;pos_time:=(pos->>'occurred_at')::timestamptz;pos_id:=(pos->>'observation_id')::uuid;end if;
 select coalesce(jsonb_agg(to_jsonb(d)),'[]'::jsonb),count(*)into material,n from(select*from e10.market_drilldown_rows(p_org,parent_req,p_cohort_key)limit 100001)d;if n>100000 then raise exception using errcode='54000',message='market_query_cohort_limit';end if;
 select array_agg(observation_id::text order by occurred_at desc,observation_id desc)into ids from jsonb_to_recordset(material)as d(observation_id uuid,occurred_at timestamptz,row_data jsonb);ids:=coalesce(ids,array[]::text[]);
 ctx:=e10.save_market_query_context('market-read-v1',p_org,actor,'drilldown',fp,req,src,org_rev,cat_rev,array[p_cohort_key]);
 select array_agg(observation_id::text order by occurred_at desc,observation_id desc)into page_ids from(select*from jsonb_to_recordset(material)as d(observation_id uuid,occurred_at timestamptz,row_data jsonb)where p_cursor is null or occurred_at<pos_time or occurred_at=pos_time and observation_id<pos_id order by occurred_at desc,observation_id desc limit p_limit+1)s;page_ids:=coalesce(page_ids,array[]::text[]);
 select coalesce(jsonb_agg(d.row_data order by u.ord),'[]'::jsonb)into rows from unnest(page_ids[1:least(cardinality(page_ids),p_limit)])with ordinality u(id,ord)join jsonb_to_recordset(material)as d(observation_id uuid,occurred_at timestamptz,row_data jsonb)on d.observation_id=u.id::uuid;
 if cardinality(page_ids)>p_limit then last_id:=page_ids[p_limit]::uuid;select occurred_at into last_time from jsonb_to_recordset(material)as d(observation_id uuid,occurred_at timestamptz,row_data jsonb)where observation_id=last_id;next_cursor:=e10.save_market_query_cursor(ctx,p_org,actor,'drilldown',fp,jsonb_build_object('occurred_at',last_time,'observation_id',last_id),p_cohort_key,org_rev,cat_rev);end if;
 if auth.uid()is distinct from actor or not exists(select 1 from public.e10_organizations where id=p_org and status='active')or not e10.is_org_member(p_org)or not e10.has_org_cap(p_org,'act.view_market_analytics')then raise exception using errcode='42501',message='market_read_denied';end if;
 return jsonb_build_object('query_fingerprint',fp,'parent_query_fingerprint',p_parent_query_fingerprint,'cohort_key',p_cohort_key,'organization_revision',org_rev,'catalog_revision',cat_rev,'observation_kind',p_observation_kind,'resolved_source_universe',src,'rows',rows,'next_cursor',next_cursor);
end $$;
revoke all on function public.e10_org_market_observation_drilldown(uuid,text,text,text,timestamptz,timestamptz,timestamptz,text,text,text,jsonb,integer,uuid)from public,anon;grant execute on function public.e10_org_market_observation_drilldown(uuid,text,text,text,timestamptz,timestamptz,timestamptz,text,text,text,jsonb,integer,uuid)to authenticated,service_role;
