-- R2 customer truth and post-lock authority corrective.

create function e10.assert_customer_writer(p_org uuid,p_cap text,p_message text)
returns void language plpgsql stable security definer set search_path=public as $$
begin
 if auth.uid() is null or not exists(select 1 from public.e10_organizations where id=p_org and status='active')
   or not e10.is_org_member(p_org) or not e10.has_org_cap(p_org,p_cap)
 then raise exception using errcode='42501',message=p_message;end if;
end $$;
revoke all on function e10.assert_customer_writer(uuid,text,text) from public,anon,authenticated;
grant execute on function e10.assert_customer_writer(uuid,text,text) to service_role;

-- Released native sales remain evidence but no longer have an actionable customer.
create or replace function e10.customer_activity_effective_customer(p_org uuid,p_activity uuid)
returns uuid language sql stable security definer set search_path=public as $$
 select case
  when o.source_kind='native' and not exists(
    select 1 from public.e10_current_native_break_sales s
    where s.organization_id=o.organization_id and s.activity_observation_id=o.id)
   then null
  when a.id is not null then case when a.decision_action='attribute' then a.customer_id else null end
  else o.customer_id end
 from public.e10_customer_activity_observations o
 left join public.e10_current_customer_activity_attributions a
  on(a.organization_id,a.activity_observation_id)=(o.organization_id,o.id)
 where o.organization_id=p_org and o.id=p_activity
$$;

-- Validate before any draft line is written so malformed arrays fail atomically
-- with the contract error rather than a storage error.
create function e10.enforce_customer_draft_line_r2() returns trigger
language plpgsql security definer set search_path=public as $$
declare a record;header_currency text;
begin
 if new.quantity is null or new.quantity<=0 or new.quantity::text in('NaN','Infinity','-Infinity')
   or new.merchandise_gross is null or new.merchandise_gross<0 or new.merchandise_gross::text in('NaN','Infinity','-Infinity')
   or(new.merchandise_discount is not null and(new.merchandise_discount<0 or new.merchandise_discount>new.merchandise_gross or new.merchandise_discount::text in('NaN','Infinity','-Infinity')))
   or(new.shipping_amount is not null and(new.shipping_amount<0 or new.shipping_amount::text in('NaN','Infinity','-Infinity')))
   or(new.tax_amount is not null and(new.tax_amount<0 or new.tax_amount::text in('NaN','Infinity','-Infinity')))
 then raise exception using errcode='22023',message='draft_line_amount_invalid';end if;
 if new.activity_observation_id is not null then
  select o.* into a from public.e10_customer_activity_observations o
   where(o.organization_id,o.id)=(new.organization_id,new.activity_observation_id);
  select currency into header_currency from public.e10_customer_transaction_draft_revisions
   where(organization_id,draft_id,revision)=(new.organization_id,new.draft_id,new.revision);
  if a.id is null then raise exception using errcode='42501',message='draft_activity_denied';end if;
  if a.currency<>header_currency then raise exception using errcode='22023',message='draft_activity_currency_mismatch';end if;
  if exists(select 1 from public.e10_customer_transaction_draft_lines l
    where(l.organization_id,l.draft_id,l.revision,l.activity_observation_id)=
      (new.organization_id,new.draft_id,new.revision,new.activity_observation_id))
  then raise exception using errcode='22023',message='draft_activity_duplicate';end if;
  if a.source_kind='native' and not exists(select 1 from public.e10_current_native_break_sales s
    where(s.organization_id,s.activity_observation_id)=(a.organization_id,a.id))
  then raise exception using errcode='42501',message='released_native_sale_not_postable';end if;
 end if;
 if new.capture_source='import' and new.break_slot_id is not null and exists(
   select 1 from public.e10_native_break_sales s
   where(s.organization_id,s.session_id,s.slot_id)=(new.organization_id,new.break_session_id,new.break_slot_id))
 then raise exception using errcode='22023',message='slot_import_requires_reconciliation';end if;
 return new;
end $$;
revoke all on function e10.enforce_customer_draft_line_r2() from public,anon,authenticated;
grant execute on function e10.enforce_customer_draft_line_r2() to service_role;
create trigger e10_customer_draft_line_r2_trg before insert on public.e10_customer_transaction_draft_lines
 for each row execute function e10.enforce_customer_draft_line_r2();

-- Preserve public signatures while moving the prior bodies behind born-locked delegates.
alter function public.e10_org_record_customer_activity(uuid,text,uuid,uuid,text,uuid,uuid,numeric,numeric,numeric,numeric,numeric,text,text,timestamptz,text,text,text,text,text,jsonb,text,text) rename to _e10_org_record_customer_activity_r2;
alter function public.e10_org_create_customer(uuid,text,text) rename to _e10_org_create_customer_r2;
alter function public.e10_org_update_customer(uuid,uuid,bigint,text,text,text) rename to _e10_org_update_customer_r2;
alter function public.e10_org_decide_customer_identity(uuid,uuid,text,text,text,text,text,uuid,text,jsonb,text) rename to _e10_org_decide_customer_identity_r2;
alter function public.e10_org_attribute_customer_activity(uuid,uuid,uuid,text,jsonb,text) rename to _e10_org_attribute_customer_activity_r2;
alter function public.e10_org_create_customer_transaction_draft(uuid,uuid,text,timestamptz,text,text,jsonb,text) rename to _e10_org_create_customer_transaction_draft_r2;
alter function public.e10_org_amend_customer_transaction_draft(uuid,uuid,integer,uuid,text,timestamptz,text,text,jsonb,text) rename to _e10_org_amend_customer_transaction_draft_r2;
alter function public.e10_org_approve_customer_transaction_draft(uuid,uuid,integer,text) rename to _e10_org_approve_customer_transaction_draft_r2;
alter function public.e10_org_reopen_customer_transaction_draft(uuid,uuid,integer,text,text) rename to _e10_org_reopen_customer_transaction_draft_r2;
alter function public.e10_org_post_customer_transaction_draft(uuid,uuid,integer,text) rename to _e10_org_post_customer_transaction_draft_r2;
alter function public.e10_org_adjust_customer_transaction(uuid,uuid,uuid,text,text,text,numeric,numeric,numeric,timestamptz,text,text,text,text,text,text,uuid,jsonb,text) rename to _e10_org_adjust_customer_transaction_r2;
alter function public.e10_org_finalize_customer_transaction_component(uuid,uuid,uuid,text,numeric,text,text,text,text,text,text,jsonb,text) rename to _e10_org_finalize_customer_transaction_component_r2;

revoke all on function public._e10_org_record_customer_activity_r2(uuid,text,uuid,uuid,text,uuid,uuid,numeric,numeric,numeric,numeric,numeric,text,text,timestamptz,text,text,text,text,text,jsonb,text,text),public._e10_org_create_customer_r2(uuid,text,text),public._e10_org_update_customer_r2(uuid,uuid,bigint,text,text,text),public._e10_org_decide_customer_identity_r2(uuid,uuid,text,text,text,text,text,uuid,text,jsonb,text),public._e10_org_attribute_customer_activity_r2(uuid,uuid,uuid,text,jsonb,text),public._e10_org_create_customer_transaction_draft_r2(uuid,uuid,text,timestamptz,text,text,jsonb,text),public._e10_org_amend_customer_transaction_draft_r2(uuid,uuid,integer,uuid,text,timestamptz,text,text,jsonb,text),public._e10_org_approve_customer_transaction_draft_r2(uuid,uuid,integer,text),public._e10_org_reopen_customer_transaction_draft_r2(uuid,uuid,integer,text,text),public._e10_org_post_customer_transaction_draft_r2(uuid,uuid,integer,text),public._e10_org_adjust_customer_transaction_r2(uuid,uuid,uuid,text,text,text,numeric,numeric,numeric,timestamptz,text,text,text,text,text,text,uuid,jsonb,text),public._e10_org_finalize_customer_transaction_component_r2(uuid,uuid,uuid,text,numeric,text,text,text,text,text,text,jsonb,text) from public,anon,authenticated;
grant execute on function public._e10_org_record_customer_activity_r2(uuid,text,uuid,uuid,text,uuid,uuid,numeric,numeric,numeric,numeric,numeric,text,text,timestamptz,text,text,text,text,text,jsonb,text,text),public._e10_org_create_customer_r2(uuid,text,text),public._e10_org_update_customer_r2(uuid,uuid,bigint,text,text,text),public._e10_org_decide_customer_identity_r2(uuid,uuid,text,text,text,text,text,uuid,text,jsonb,text),public._e10_org_attribute_customer_activity_r2(uuid,uuid,uuid,text,jsonb,text),public._e10_org_create_customer_transaction_draft_r2(uuid,uuid,text,timestamptz,text,text,jsonb,text),public._e10_org_amend_customer_transaction_draft_r2(uuid,uuid,integer,uuid,text,timestamptz,text,text,jsonb,text),public._e10_org_approve_customer_transaction_draft_r2(uuid,uuid,integer,text),public._e10_org_reopen_customer_transaction_draft_r2(uuid,uuid,integer,text,text),public._e10_org_post_customer_transaction_draft_r2(uuid,uuid,integer,text),public._e10_org_adjust_customer_transaction_r2(uuid,uuid,uuid,text,text,text,numeric,numeric,numeric,timestamptz,text,text,text,text,text,text,uuid,jsonb,text),public._e10_org_finalize_customer_transaction_component_r2(uuid,uuid,uuid,text,numeric,text,text,text,text,text,text,jsonb,text) to service_role;

create function public.e10_org_record_customer_activity(p_org uuid,p_activity_kind text,p_customer_id uuid,p_buyer_user_id uuid,p_buyer_alias text,p_break_session_id uuid,p_break_slot_id uuid,p_quantity numeric,p_merchandise_gross numeric,p_merchandise_discount numeric,p_shipping_amount numeric,p_tax_amount numeric,p_currency text,p_sale_method text,p_occurred_at timestamptz,p_occurred_at_precision text,p_source_kind text,p_source_connection_id text,p_source_reference text,p_source_event_id text,p_raw_payload jsonb,p_evidence_quality text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-activity|'||p_idempotency_key,0));perform e10.assert_customer_writer(p_org,'act.record_commercial_events','record_customer_activity_denied');return public._e10_org_record_customer_activity_r2(p_org,p_activity_kind,p_customer_id,p_buyer_user_id,p_buyer_alias,p_break_session_id,p_break_slot_id,p_quantity,p_merchandise_gross,p_merchandise_discount,p_shipping_amount,p_tax_amount,p_currency,p_sale_method,p_occurred_at,p_occurred_at_precision,p_source_kind,p_source_connection_id,p_source_reference,p_source_event_id,p_raw_payload,p_evidence_quality,p_idempotency_key);end$$;
create function public.e10_org_create_customer(p_org uuid,p_display_name text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-mutation|'||p_idempotency_key,0));perform e10.assert_customer_writer(p_org,'act.manage_customers','manage_customer_denied');return public._e10_org_create_customer_r2(p_org,p_display_name,p_idempotency_key);end$$;
create function public.e10_org_update_customer(p_org uuid,p_customer_id uuid,p_expected_revision bigint,p_display_name text,p_status text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform e10.assert_customer_writer(p_org,'act.manage_customers','manage_customer_denied');perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-resolution-topology',0));perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-mutation|'||p_idempotency_key,0));perform 1 from public.e10_customers where organization_id=p_org and id=p_customer_id for update;perform e10.assert_customer_writer(p_org,'act.manage_customers','manage_customer_denied');return public._e10_org_update_customer_r2(p_org,p_customer_id,p_expected_revision,p_display_name,p_status,p_idempotency_key);end$$;
create function public.e10_org_decide_customer_identity(p_org uuid,p_customer_id uuid,p_identity_kind text,p_channel text,p_external_account_id text,p_alias_text text,p_identity_action text,p_viewer_handle_claim_id uuid,p_reason text,p_evidence jsonb,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform e10.assert_customer_writer(p_org,'act.manage_customers','manage_customer_identity_denied');perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-resolution-topology',0));perform 1 from public.e10_customers where organization_id=p_org and id=p_customer_id for update;perform e10.assert_customer_writer(p_org,'act.manage_customers','manage_customer_identity_denied');return public._e10_org_decide_customer_identity_r2(p_org,p_customer_id,p_identity_kind,p_channel,p_external_account_id,p_alias_text,p_identity_action,p_viewer_handle_claim_id,p_reason,p_evidence,p_idempotency_key);end$$;
create function public.e10_org_attribute_customer_activity(p_org uuid,p_activity_id uuid,p_customer_id uuid,p_reason text,p_evidence jsonb,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|activity-attribution|'||p_activity_id::text,0));perform e10.assert_customer_writer(p_org,'act.manage_customers','attribute_customer_activity_denied');return public._e10_org_attribute_customer_activity_r2(p_org,p_activity_id,p_customer_id,p_reason,p_evidence,p_idempotency_key);end$$;

create function public.e10_org_create_customer_transaction_draft(p_org uuid,p_customer uuid,p_currency text,p_occurred_at timestamptz,p_precision text,p_note text,p_lines jsonb,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-commercial|'||p_idempotency_key,0));perform e10.assert_customer_writer(p_org,'act.prepare_customer_transactions','prepare_customer_transaction_denied');return public._e10_org_create_customer_transaction_draft_r2(p_org,p_customer,p_currency,p_occurred_at,p_precision,p_note,p_lines,p_idempotency_key);end$$;
create function public.e10_org_amend_customer_transaction_draft(p_org uuid,p_draft uuid,p_expected_revision integer,p_customer uuid,p_currency text,p_occurred_at timestamptz,p_precision text,p_note text,p_lines jsonb,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-commercial|'||p_idempotency_key,0));perform 1 from public.e10_customer_transaction_drafts where organization_id=p_org and id=p_draft for update;perform e10.assert_customer_writer(p_org,'act.prepare_customer_transactions','prepare_customer_transaction_denied');return public._e10_org_amend_customer_transaction_draft_r2(p_org,p_draft,p_expected_revision,p_customer,p_currency,p_occurred_at,p_precision,p_note,p_lines,p_idempotency_key);end$$;
create function public.e10_org_approve_customer_transaction_draft(p_org uuid,p_draft uuid,p_expected_revision integer,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare a uuid;begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-commercial|'||p_idempotency_key,0));perform 1 from public.e10_customer_transaction_drafts where organization_id=p_org and id=p_draft for update;for a in select distinct activity_observation_id from public.e10_customer_transaction_draft_lines where organization_id=p_org and draft_id=p_draft and revision=p_expected_revision and activity_observation_id is not null order by 1 loop perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|activity-attribution|'||a::text,0));end loop;perform e10.assert_customer_writer(p_org,'act.approve_customer_transactions','approve_customer_transaction_denied');return public._e10_org_approve_customer_transaction_draft_r2(p_org,p_draft,p_expected_revision,p_idempotency_key);end$$;
create function public.e10_org_reopen_customer_transaction_draft(p_org uuid,p_draft uuid,p_expected_revision integer,p_reason text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-commercial|'||p_idempotency_key,0));perform 1 from public.e10_customer_transaction_drafts where organization_id=p_org and id=p_draft for update;perform e10.assert_customer_writer(p_org,'act.approve_customer_transactions','reopen_customer_transaction_denied');return public._e10_org_reopen_customer_transaction_draft_r2(p_org,p_draft,p_expected_revision,p_reason,p_idempotency_key);end$$;

create function public.e10_org_post_customer_transaction_draft(p_org uuid,p_draft uuid,p_expected_revision integer,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare a uuid;k text;begin
 perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-commercial|'||p_idempotency_key,0));perform 1 from public.e10_customer_transaction_drafts where organization_id=p_org and id=p_draft for update;
 for a in select distinct activity_observation_id from public.e10_customer_transaction_draft_lines where organization_id=p_org and draft_id=p_draft and revision=p_expected_revision and activity_observation_id is not null order by 1 loop perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|activity-attribution|'||a::text,0));end loop;
 for k in select lock_key from(select distinct 'activity|'||activity_observation_id::text lock_key from public.e10_customer_transaction_draft_lines where organization_id=p_org and draft_id=p_draft and revision=p_expected_revision and activity_observation_id is not null union select distinct 'source|'||capture_source||'|'||coalesce(source_connection_id,'')||'|'||source_line_id from public.e10_customer_transaction_draft_lines where organization_id=p_org and draft_id=p_draft and revision=p_expected_revision)s order by 1 loop perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|posted|'||k,0));end loop;
 perform 1 from public.e10_break_slots sl where(sl.organization_id,sl.id) in(select l.organization_id,l.break_slot_id from public.e10_customer_transaction_draft_lines l where l.organization_id=p_org and l.draft_id=p_draft and l.revision=p_expected_revision and l.break_slot_id is not null) order by sl.id for update;
 if exists(select 1 from public.e10_customer_transaction_draft_lines l join public.e10_customer_activity_observations o on(o.organization_id,o.id)=(l.organization_id,l.activity_observation_id) where l.organization_id=p_org and l.draft_id=p_draft and l.revision=p_expected_revision and o.source_kind='native' and not exists(select 1 from public.e10_current_native_break_sales s where(s.organization_id,s.activity_observation_id)=(o.organization_id,o.id)))then raise exception using errcode='42501',message='released_native_sale_not_postable';end if;
 if exists(select 1 from public.e10_customer_transaction_draft_lines l join public.e10_customer_transaction_draft_revisions r on(r.organization_id,r.draft_id,r.revision)=(l.organization_id,l.draft_id,l.revision) join public.e10_customer_activity_observations o on(o.organization_id,o.id)=(l.organization_id,l.activity_observation_id) where l.organization_id=p_org and l.draft_id=p_draft and l.revision=p_expected_revision and o.currency<>r.currency)then raise exception using errcode='22023',message='draft_activity_currency_mismatch';end if;
 if exists(select 1 from public.e10_customer_transaction_draft_lines l where l.organization_id=p_org and l.draft_id=p_draft and l.revision=p_expected_revision and l.activity_observation_id is not null group by l.activity_observation_id having count(*)>1)then raise exception using errcode='22023',message='draft_activity_duplicate';end if;
 if exists(select 1 from public.e10_customer_transaction_draft_lines l where l.organization_id=p_org and l.draft_id=p_draft and l.revision=p_expected_revision and l.capture_source='import' and l.break_slot_id is not null and exists(select 1 from public.e10_native_break_sales s where(s.organization_id,s.session_id,s.slot_id)=(l.organization_id,l.break_session_id,l.break_slot_id)))then raise exception using errcode='22023',message='slot_import_requires_reconciliation';end if;
 perform e10.assert_customer_writer(p_org,'act.post_customer_transactions','post_customer_transaction_denied');return public._e10_org_post_customer_transaction_draft_r2(p_org,p_draft,p_expected_revision,p_idempotency_key);end$$;

create function public.e10_org_adjust_customer_transaction(p_org uuid,p_transaction_id uuid,p_transaction_line_id uuid,p_adjustment_kind text,p_effect text,p_currency text,p_merchandise_amount numeric,p_shipping_amount numeric,p_tax_amount numeric,p_occurred_at timestamptz,p_occurred_at_precision text,p_reason text,p_source_kind text,p_source_connection_id text,p_source_event_id text,p_source_component_id text,p_reinstates_cancellation_id uuid,p_evidence jsonb,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-commercial|'||p_idempotency_key,0));perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-adjustment|'||p_transaction_line_id::text,0));perform e10.assert_customer_writer(p_org,'act.adjust_customer_transactions','adjust_customer_transaction_denied');return public._e10_org_adjust_customer_transaction_r2(p_org,p_transaction_id,p_transaction_line_id,p_adjustment_kind,p_effect,p_currency,p_merchandise_amount,p_shipping_amount,p_tax_amount,p_occurred_at,p_occurred_at_precision,p_reason,p_source_kind,p_source_connection_id,p_source_event_id,p_source_component_id,p_reinstates_cancellation_id,p_evidence,p_idempotency_key);end$$;
create function public.e10_org_finalize_customer_transaction_component(p_org uuid,p_transaction_id uuid,p_transaction_line_id uuid,p_component text,p_final_amount numeric,p_currency text,p_reason text,p_source_kind text,p_source_connection_id text,p_source_event_id text,p_source_component_id text,p_evidence jsonb,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$begin perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-commercial|'||p_idempotency_key,0));perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|customer-adjustment|'||p_transaction_line_id::text,0));perform e10.assert_customer_writer(p_org,'act.reconcile_customer_transactions','finalize_customer_component_denied');return public._e10_org_finalize_customer_transaction_component_r2(p_org,p_transaction_id,p_transaction_line_id,p_component,p_final_amount,p_currency,p_reason,p_source_kind,p_source_connection_id,p_source_event_id,p_source_component_id,p_evidence,p_idempotency_key);end$$;

revoke all on function public.e10_org_record_customer_activity(uuid,text,uuid,uuid,text,uuid,uuid,numeric,numeric,numeric,numeric,numeric,text,text,timestamptz,text,text,text,text,text,jsonb,text,text),public.e10_org_create_customer(uuid,text,text),public.e10_org_update_customer(uuid,uuid,bigint,text,text,text),public.e10_org_decide_customer_identity(uuid,uuid,text,text,text,text,text,uuid,text,jsonb,text),public.e10_org_attribute_customer_activity(uuid,uuid,uuid,text,jsonb,text),public.e10_org_create_customer_transaction_draft(uuid,uuid,text,timestamptz,text,text,jsonb,text),public.e10_org_amend_customer_transaction_draft(uuid,uuid,integer,uuid,text,timestamptz,text,text,jsonb,text),public.e10_org_approve_customer_transaction_draft(uuid,uuid,integer,text),public.e10_org_reopen_customer_transaction_draft(uuid,uuid,integer,text,text),public.e10_org_post_customer_transaction_draft(uuid,uuid,integer,text),public.e10_org_adjust_customer_transaction(uuid,uuid,uuid,text,text,text,numeric,numeric,numeric,timestamptz,text,text,text,text,text,text,uuid,jsonb,text),public.e10_org_finalize_customer_transaction_component(uuid,uuid,uuid,text,numeric,text,text,text,text,text,text,jsonb,text) from public,anon;
grant execute on function public.e10_org_record_customer_activity(uuid,text,uuid,uuid,text,uuid,uuid,numeric,numeric,numeric,numeric,numeric,text,text,timestamptz,text,text,text,text,text,jsonb,text,text),public.e10_org_create_customer(uuid,text,text),public.e10_org_update_customer(uuid,uuid,bigint,text,text,text),public.e10_org_decide_customer_identity(uuid,uuid,text,text,text,text,text,uuid,text,jsonb,text),public.e10_org_attribute_customer_activity(uuid,uuid,uuid,text,jsonb,text),public.e10_org_create_customer_transaction_draft(uuid,uuid,text,timestamptz,text,text,jsonb,text),public.e10_org_amend_customer_transaction_draft(uuid,uuid,integer,uuid,text,timestamptz,text,text,jsonb,text),public.e10_org_approve_customer_transaction_draft(uuid,uuid,integer,text),public.e10_org_reopen_customer_transaction_draft(uuid,uuid,integer,text,text),public.e10_org_post_customer_transaction_draft(uuid,uuid,integer,text),public.e10_org_adjust_customer_transaction(uuid,uuid,uuid,text,text,text,numeric,numeric,numeric,timestamptz,text,text,text,text,text,text,uuid,jsonb,text),public.e10_org_finalize_customer_transaction_component(uuid,uuid,uuid,text,numeric,text,text,text,text,text,text,jsonb,text) to authenticated,service_role;
