-- TA-X7d.0a governed catalog facets. Additive and client-closed.
create table public.e10_catalog_facet_term_keys(
 id uuid primary key default gen_random_uuid(),namespace text not null check(namespace in('color_family','finish_family')));
create table public.e10_catalog_facet_taxonomy_terms(
 id uuid primary key default gen_random_uuid(),term_key uuid not null references public.e10_catalog_facet_term_keys(id),
 namespace text not null check(namespace in('color_family','finish_family')),canonical_name text not null check(length(btrim(canonical_name))between 1 and 100),
 revision bigint not null check(revision>0),action text not null check(action in('assert','revoke')),supersedes_term_id uuid references public.e10_catalog_facet_taxonomy_terms(id),
 reason text not null check(length(btrim(reason))between 1 and 2000),evidence jsonb not null check(jsonb_typeof(evidence)='object'and octet_length(evidence::text)<=65536),
 idempotency_key text not null unique check(length(btrim(idempotency_key))between 1 and 500),request_fingerprint text not null check(btrim(request_fingerprint)<>''),reviewed_by uuid references auth.users(id),reviewed_at timestamptz not null default clock_timestamp(),unique(term_key,revision));
create unique index e10_facet_term_root_uq on public.e10_catalog_facet_taxonomy_terms(term_key)where supersedes_term_id is null;
create unique index e10_facet_term_name_root_uq on public.e10_catalog_facet_taxonomy_terms(namespace,lower(btrim(canonical_name)))where supersedes_term_id is null;
create unique index e10_facet_term_successor_uq on public.e10_catalog_facet_taxonomy_terms(supersedes_term_id)where supersedes_term_id is not null;

create table public.e10_catalog_facet_taxonomy_aliases(
 id uuid primary key default gen_random_uuid(),alias_key uuid not null,namespace text not null check(namespace in('color_family','finish_family')),alias text not null check(length(btrim(alias))between 1 and 100),term_key uuid references public.e10_catalog_facet_term_keys(id),
 revision bigint not null check(revision>0),action text not null check(action in('assert','revoke')),supersedes_alias_id uuid references public.e10_catalog_facet_taxonomy_aliases(id),
 reason text not null check(length(btrim(reason))between 1 and 2000),evidence jsonb not null check(jsonb_typeof(evidence)='object'and octet_length(evidence::text)<=65536),idempotency_key text not null unique,request_fingerprint text not null check(btrim(request_fingerprint)<>''),reviewed_by uuid references auth.users(id),reviewed_at timestamptz not null default clock_timestamp(),unique(alias_key,revision),check((action='assert'and term_key is not null)or(action='revoke'and term_key is null)));
create unique index e10_facet_alias_root_uq on public.e10_catalog_facet_taxonomy_aliases(alias_key)where supersedes_alias_id is null;
create unique index e10_facet_alias_name_root_uq on public.e10_catalog_facet_taxonomy_aliases(namespace,lower(btrim(alias)))where supersedes_alias_id is null;
create unique index e10_facet_alias_successor_uq on public.e10_catalog_facet_taxonomy_aliases(supersedes_alias_id)where supersedes_alias_id is not null;

create table public.e10_catalog_variant_facet_decisions(
 id uuid primary key default gen_random_uuid(),decision_key uuid not null,variant_id uuid not null references public.e10_catalog_variants(id),subject_id uuid references public.e10_players(id),facet_key text not null check(facet_key in('rookie_designation','rookie_season','color_family','finish_family')),
 revision bigint not null check(revision>0),action text not null check(action in('assert','revoke')),boolean_value boolean,integer_value integer,term_key uuid references public.e10_catalog_facet_term_keys(id),supersedes_decision_id uuid references public.e10_catalog_variant_facet_decisions(id),
 reason text not null check(length(btrim(reason))between 1 and 2000),evidence jsonb not null check(jsonb_typeof(evidence)='object'and octet_length(evidence::text)<=65536),idempotency_key text not null unique,request_fingerprint text not null check(btrim(request_fingerprint)<>''),reviewed_by uuid references auth.users(id),reviewed_at timestamptz not null default clock_timestamp(),unique(decision_key,revision),
 check((facet_key='rookie_designation'and integer_value is null and term_key is null and((action='assert'and boolean_value is not null)or(action='revoke'and boolean_value is null)))or(facet_key='rookie_season'and subject_id is not null and boolean_value is null and term_key is null and((action='assert'and integer_value is not null and integer_value between 1800 and 2200)or(action='revoke'and integer_value is null)))or(facet_key in('color_family','finish_family')and subject_id is null and boolean_value is null and integer_value is null and((action='assert'and term_key is not null)or(action='revoke'and term_key is null)))));
create unique index e10_variant_facet_root_uq on public.e10_catalog_variant_facet_decisions(decision_key)where supersedes_decision_id is null;
create unique index e10_variant_facet_logical_root_uq on public.e10_catalog_variant_facet_decisions(variant_id,subject_id,facet_key)nulls not distinct where supersedes_decision_id is null;
create unique index e10_variant_facet_successor_uq on public.e10_catalog_variant_facet_decisions(supersedes_decision_id)where supersedes_decision_id is not null;

create table public.e10_org_catalog_variant_facet_overrides(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.e10_organizations(id),decision_key uuid not null,variant_id uuid not null references public.e10_catalog_variants(id),subject_id uuid references public.e10_players(id),facet_key text not null check(facet_key in('rookie_designation','rookie_season','color_family','finish_family')),
 revision bigint not null check(revision>0),action text not null check(action in('assert','mask','clear')),boolean_value boolean,integer_value integer,term_key uuid references public.e10_catalog_facet_term_keys(id),supersedes_decision_id uuid,
 reason text not null check(length(btrim(reason))between 1 and 2000),evidence jsonb not null check(jsonb_typeof(evidence)='object'and octet_length(evidence::text)<=65536),idempotency_key text not null,request_fingerprint text not null check(btrim(request_fingerprint)<>''),reviewed_by uuid references auth.users(id),reviewed_at timestamptz not null default clock_timestamp(),unique(organization_id,id),unique(organization_id,idempotency_key),unique(organization_id,decision_key,revision),foreign key(organization_id,supersedes_decision_id)references public.e10_org_catalog_variant_facet_overrides(organization_id,id),
 check((facet_key='rookie_designation'and integer_value is null and term_key is null and((action='assert'and boolean_value is not null)or(action in('mask','clear')and boolean_value is null)))or(facet_key='rookie_season'and subject_id is not null and boolean_value is null and term_key is null and((action='assert'and integer_value is not null and integer_value between 1800 and 2200)or(action in('mask','clear')and integer_value is null)))or(facet_key in('color_family','finish_family')and subject_id is null and boolean_value is null and integer_value is null and((action='assert'and term_key is not null)or(action in('mask','clear')and term_key is null)))));
create unique index e10_org_variant_facet_root_uq on public.e10_org_catalog_variant_facet_overrides(organization_id,decision_key)where supersedes_decision_id is null;
create unique index e10_org_variant_facet_logical_root_uq on public.e10_org_catalog_variant_facet_overrides(organization_id,variant_id,subject_id,facet_key)nulls not distinct where supersedes_decision_id is null;
create unique index e10_org_variant_facet_successor_uq on public.e10_org_catalog_variant_facet_overrides(organization_id,supersedes_decision_id)where supersedes_decision_id is not null;

create function e10.validate_facet_evidence_insert()returns trigger language plpgsql security definer set search_path=public as $$declare p record;ns text;begin
 if tg_table_name='e10_catalog_facet_taxonomy_terms'then select namespace into ns from public.e10_catalog_facet_term_keys where id=new.term_key;if ns is distinct from new.namespace then raise exception using errcode='23514',message='term_namespace_mismatch';end if;if new.supersedes_term_id is null then if new.revision<>1 then raise exception using errcode='23514',message='root_revision_invalid';end if;else if new.supersedes_term_id=new.id then raise exception using errcode='23514',message='self_successor_invalid';end if;select*into p from public.e10_catalog_facet_taxonomy_terms where id=new.supersedes_term_id;if not found or p.term_key<>new.term_key or p.namespace<>new.namespace or p.canonical_name<>new.canonical_name or new.revision<>p.revision+1 then raise exception using errcode='23514',message='successor_key_mismatch';end if;end if;
 elsif tg_table_name='e10_catalog_facet_taxonomy_aliases'then if new.term_key is not null and not exists(select 1 from public.e10_catalog_facet_taxonomy_terms t where t.term_key=new.term_key and t.namespace=new.namespace and t.action='assert'and not exists(select 1 from public.e10_catalog_facet_taxonomy_terms n where n.supersedes_term_id=t.id))then raise exception using errcode='23514',message='alias_term_invalid';end if;if new.supersedes_alias_id is null then if new.revision<>1 then raise exception using errcode='23514',message='root_revision_invalid';end if;else if new.supersedes_alias_id=new.id then raise exception using errcode='23514',message='self_successor_invalid';end if;select*into p from public.e10_catalog_facet_taxonomy_aliases where id=new.supersedes_alias_id;if not found or p.alias_key<>new.alias_key or p.namespace<>new.namespace or p.alias<>new.alias or new.revision<>p.revision+1 then raise exception using errcode='23514',message='successor_key_mismatch';end if;end if;
 else if new.subject_id is not null and not exists(select 1 from public.e10_catalog_variant_subjects where variant_id=new.variant_id and player_id=new.subject_id)then raise exception using errcode='23514',message='subject_not_on_variant';end if;if new.term_key is not null then ns:=case new.facet_key when'color_family'then'color_family'else'finish_family'end;if not exists(select 1 from public.e10_catalog_facet_taxonomy_terms t where t.term_key=new.term_key and t.namespace=ns and t.action='assert'and not exists(select 1 from public.e10_catalog_facet_taxonomy_terms n where n.supersedes_term_id=t.id))then raise exception using errcode='23514',message='facet_term_invalid';end if;end if;
  if tg_table_name='e10_catalog_variant_facet_decisions'then if new.supersedes_decision_id is null then if new.revision<>1 then raise exception using errcode='23514',message='root_revision_invalid';end if;else if new.supersedes_decision_id=new.id then raise exception using errcode='23514',message='self_successor_invalid';end if;select*into p from public.e10_catalog_variant_facet_decisions where id=new.supersedes_decision_id;if not found or p.decision_key<>new.decision_key or p.variant_id<>new.variant_id or p.subject_id is distinct from new.subject_id or p.facet_key<>new.facet_key or new.revision<>p.revision+1 then raise exception using errcode='23514',message='successor_key_mismatch';end if;end if;
  else if new.supersedes_decision_id is null then if new.revision<>1 then raise exception using errcode='23514',message='root_revision_invalid';end if;else if new.supersedes_decision_id=new.id then raise exception using errcode='23514',message='self_successor_invalid';end if;select*into p from public.e10_org_catalog_variant_facet_overrides where organization_id=new.organization_id and id=new.supersedes_decision_id;if not found or p.decision_key<>new.decision_key or p.variant_id<>new.variant_id or p.subject_id is distinct from new.subject_id or p.facet_key<>new.facet_key or new.revision<>p.revision+1 then raise exception using errcode='23514',message='successor_key_mismatch';end if;end if;end if;
 end if;return new;end $$;
revoke all on function e10.validate_facet_evidence_insert()from public,anon,authenticated;grant execute on function e10.validate_facet_evidence_insert()to service_role;
do $$declare t text;begin foreach t in array array['e10_catalog_facet_term_keys','e10_catalog_facet_taxonomy_terms','e10_catalog_facet_taxonomy_aliases','e10_catalog_variant_facet_decisions','e10_org_catalog_variant_facet_overrides']loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant all on public.%I to service_role',t);execute format('create trigger %I before update or delete on public.%I for each row execute function e10.reject_append_only_change()',t||'_append_only',t);end loop;end $$;
do $$declare t text;begin foreach t in array array['e10_catalog_facet_taxonomy_terms','e10_catalog_facet_taxonomy_aliases','e10_catalog_variant_facet_decisions','e10_org_catalog_variant_facet_overrides']loop execute format('create trigger %I before insert on public.%I for each row execute function e10.validate_facet_evidence_insert()',t||'_insert_guard',t);end loop;end $$;
create view public.e10_current_catalog_facet_taxonomy_terms with(security_invoker=true)as select d.*from public.e10_catalog_facet_taxonomy_terms d where not exists(select 1 from public.e10_catalog_facet_taxonomy_terms n where n.supersedes_term_id=d.id);
create view public.e10_current_catalog_variant_facets with(security_invoker=true)as select d.*from public.e10_catalog_variant_facet_decisions d where not exists(select 1 from public.e10_catalog_variant_facet_decisions n where n.supersedes_decision_id=d.id);
create view public.e10_current_org_catalog_variant_facet_overrides with(security_invoker=true)as select d.*from public.e10_org_catalog_variant_facet_overrides d where not exists(select 1 from public.e10_org_catalog_variant_facet_overrides n where n.organization_id=d.organization_id and n.supersedes_decision_id=d.id);
revoke all on public.e10_current_catalog_facet_taxonomy_terms,public.e10_current_catalog_variant_facets,public.e10_current_org_catalog_variant_facet_overrides from public,anon,authenticated;grant select on public.e10_current_catalog_facet_taxonomy_terms,public.e10_current_catalog_variant_facets,public.e10_current_org_catalog_variant_facet_overrides to service_role;
