-- TA-X7d.2e one validation and normalization boundary for both market read APIs.
create function e10.normalize_market_screener_request(
 p_org uuid,p_scope text,p_grouping text,p_metric text,p_observation_kind text,
 p_observed_from timestamptz,p_observed_to timestamptz,p_as_of timestamptz,p_currency text,
 p_source_mode text,p_source_kind text,p_source_connections jsonb,p_filters jsonb,p_sort text,p_limit integer
)returns jsonb language plpgsql stable security definer set search_path=public as $$
declare
 allowed_keys constant text[]:=array['sport','league','subject_id','manufacturer','brand_line','release_id','release_name','release_year','release_year_from','release_year_to','season_from','season_to','language','region','edition','card_number','exact_parallel','color_family_term_id','finish_family_term_id','rookie_designation','rookie_season','exact_subject','condition_state','graded','grader_code','grade_label','grade_qualifier','serial_numerator','observed_serial_denominator','variant_print_run_denominator','jersey_match','amount_min','amount_max','sale_count_min','sale_count_max','mean_min','mean_max','median_min','median_max','latest_min','latest_max','minimum_min','minimum_max','maximum_min','maximum_max'];
 string_keys constant text[]:=array['sport','league','manufacturer','brand_line','release_name','season_from','season_to','language','region','edition','card_number','exact_parallel','condition_state','grader_code','grade_label','grade_qualifier'];
 uuid_keys constant text[]:=array['subject_id','release_id','color_family_term_id','finish_family_term_id'];
 integer_keys constant text[]:=array['release_year','release_year_from','release_year_to','rookie_season','serial_numerator','observed_serial_denominator','variant_print_run_denominator','sale_count_min','sale_count_max'];
 numeric_keys constant text[]:=array['amount_min','amount_max','mean_min','mean_max','median_min','median_max','latest_min','latest_max','minimum_min','minimum_max','maximum_min','maximum_max'];
 boolean_keys constant text[]:=array['rookie_designation','exact_subject','graded','jersey_match'];
 k text;v jsonb;resolved jsonb;normalized_filters jsonb:='{}'::jsonb;nv numeric;iv bigint;uv uuid;
begin
 if p_org is null or p_scope is null or p_grouping is null or p_metric is null or p_observation_kind is null or p_source_mode is null or p_sort is null or p_limit is null or p_scope not in('catalog','owned','completed_sale_observation')or p_grouping not in('entity','variant','variant_condition','variant_grader_grade','subject','release','color','finish')or p_metric not in('count','transaction_total','reviewed_unit_price')or p_observation_kind not in('acquisition_cost','asking_price','completed_sale','estimated_value')or p_sort not in('cohort_asc','observed_count_desc','latest_desc','mean_asc','mean_desc','median_asc','median_desc')or p_limit not between 1 and 200 then raise exception using errcode='22023',message='market_read_request_invalid';end if;
 if p_scope='completed_sale_observation'and p_observation_kind<>'completed_sale'then raise exception using errcode='22023',message='market_scope_kind_mismatch';end if;
 if p_source_mode='none'and(p_source_kind is not null or p_source_connections is not null)then raise exception using errcode='22023',message='market_source_universe_invalid';end if;
 if p_observed_from is null or p_observed_to is null or p_as_of is null or not isfinite(p_observed_from)or not isfinite(p_observed_to)or not isfinite(p_as_of)or p_observed_from>=p_observed_to or p_observed_to>p_as_of then raise exception using errcode='22023',message='market_window_invalid';end if;
 if(p_metric<>'count'or p_source_mode<>'none')and(p_currency is null or p_currency!~'^[A-Z]{3}$')then raise exception using errcode='22023',message='market_currency_required';end if;
 if p_currency is not null and p_currency!~'^[A-Z]{3}$'then raise exception using errcode='22023',message='market_currency_invalid';end if;
 if p_filters is null or jsonb_typeof(p_filters)<>'object'or octet_length(p_filters::text)>65536 then raise exception using errcode='22023',message='market_filters_invalid';end if;
 for k,v in select key,value from jsonb_each(p_filters)loop
  if not(k=any(allowed_keys))or jsonb_typeof(v)='null'then raise exception using errcode='22023',message='market_filter_unknown_or_null';end if;
  if k=any(string_keys)then if jsonb_typeof(v)<>'string'or length(btrim(v#>>'{}'))not between 1 and 500 then raise exception using errcode='22023',message='market_filter_type_invalid';end if;normalized_filters:=normalized_filters||jsonb_build_object(k,btrim(v#>>'{}'));
  elsif k=any(uuid_keys)then begin if jsonb_typeof(v)<>'string'then raise invalid_text_representation;end if;uv:=(v#>>'{}')::uuid;exception when others then raise exception using errcode='22023',message='market_filter_type_invalid';end;normalized_filters:=normalized_filters||jsonb_build_object(k,uv);
  elsif k=any(integer_keys)then begin if jsonb_typeof(v)<>'number'or(v#>>'{}')!~'^-?[0-9]+$'then raise numeric_value_out_of_range;end if;iv:=(v#>>'{}')::bigint;if iv not between -2147483648 and 2147483647 then raise numeric_value_out_of_range;end if;exception when others then raise exception using errcode='22023',message='market_filter_type_invalid';end;normalized_filters:=normalized_filters||jsonb_build_object(k,iv);
  elsif k=any(numeric_keys)then begin if jsonb_typeof(v)<>'number'then raise numeric_value_out_of_range;end if;nv:=(v#>>'{}')::numeric;if abs(nv)>1000000000000000000::numeric then raise numeric_value_out_of_range;end if;exception when others then raise exception using errcode='22023',message='market_filter_type_invalid';end;normalized_filters:=normalized_filters||jsonb_build_object(k,nv);
  elsif k=any(boolean_keys)then if jsonb_typeof(v)<>'boolean'then raise exception using errcode='22023',message='market_filter_type_invalid';end if;normalized_filters:=normalized_filters||jsonb_build_object(k,(v#>>'{}')::boolean);
  end if;
 end loop;
 if normalized_filters?'release_year'and(normalized_filters?'release_year_from'or normalized_filters?'release_year_to')or(normalized_filters->>'exact_subject')::boolean is true and not(normalized_filters?'subject_id')or p_scope='catalog'and(normalized_filters->>'exact_subject')::boolean is true then raise exception using errcode='22023',message='market_filter_combination_invalid';end if;
 if p_metric='count'and(p_sort in('latest_desc','mean_asc','mean_desc','median_asc','median_desc')or p_filters?|array['mean_min','mean_max','median_min','median_max','latest_min','latest_max','minimum_min','minimum_max','maximum_min','maximum_max','amount_min','amount_max'])then raise exception using errcode='22023',message='market_metric_filter_invalid';end if;
 if p_observation_kind<>'completed_sale'and p_filters?|array['sale_count_min','sale_count_max']then raise exception using errcode='22023',message='market_sale_filter_invalid';end if;
 if normalized_filters?'release_year_from'and normalized_filters?'release_year_to'and(normalized_filters->>'release_year_from')::integer>(normalized_filters->>'release_year_to')::integer then raise exception using errcode='22023',message='market_filter_range_invalid';end if;
 foreach k in array array['amount','sale_count','mean','median','latest','minimum','maximum']loop if normalized_filters?(k||'_min')and normalized_filters?(k||'_max')and(normalized_filters->>(k||'_min'))::numeric>(normalized_filters->>(k||'_max'))::numeric then raise exception using errcode='22023',message='market_filter_range_invalid';end if;end loop;
 if p_source_mode='none'and p_currency is null then resolved:='[]'::jsonb;else resolved:=e10.market_source_universe(p_org,p_source_mode,p_observation_kind,p_source_kind,p_currency,p_source_connections);end if;
 return jsonb_build_object('api_version','market-read-v1','scope',p_scope,'grouping',p_grouping,'metric',p_metric,'observation_kind',p_observation_kind,'observed_from',to_char(p_observed_from at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'observed_to',to_char(p_observed_to at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'as_of',to_char(p_as_of at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'currency',p_currency,'source_mode',p_source_mode,'source_kind',p_source_kind,'resolved_source_universe',resolved,'filters',normalized_filters,'sort',p_sort,'limit',p_limit);
end $$;

revoke all on function e10.normalize_market_screener_request(uuid,text,text,text,text,timestamptz,timestamptz,timestamptz,text,text,text,jsonb,jsonb,text,integer)from public,anon,authenticated;
grant execute on function e10.normalize_market_screener_request(uuid,text,text,text,text,timestamptz,timestamptz,timestamptz,text,text,text,jsonb,jsonb,text,integer)to service_role;
comment on function e10.normalize_market_screener_request(uuid,text,text,text,text,timestamptz,timestamptz,timestamptz,text,text,text,jsonb,jsonb,text,integer)is'Binding validation and normalized-input contract for TA-X7d market reads; unknown keys and invalid cross-field combinations fail closed.';
