-- TA-X8b.3 reviewable proposal transitions and delegation to ordinary writers.

create function e10.x8b_authorized(p_org uuid,p_draft uuid,p_action text)returns boolean
language sql stable security definer set search_path=public as $$
 select auth.uid()is not null and exists(select 1 from public.e10_organizations where id=p_org and status='active')
  and e10.is_org_member(p_org) and exists(
   select 1 from public.e10_action_drafts d where d.organization_id=p_org and d.id=p_draft and(
    (p_action in('read','amend','cancel','commit')and(d.created_by=auth.uid()or e10.is_org_admin(p_org)))
    or(p_action in('preview','approve')and(d.created_by=auth.uid()or e10.is_org_admin(p_org)or e10.has_org_cap(p_org,e10.x8b_capability(d.operation,'approve'))))
   )and(case when p_action in('amend','commit')then e10.has_org_cap(p_org,e10.x8b_capability(d.operation,'prepare'))when p_action='approve'then e10.has_org_cap(p_org,e10.x8b_capability(d.operation,'approve'))else true end)
  )
$$;

create function e10.x8b_command(p_org uuid,p_key text,p_type text,p_draft uuid,p_fp text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r record;begin
 if p_key is null or length(btrim(p_key))not between 1 and 200 then raise exception using errcode='22004',message='action_idempotency_key_invalid';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_org::text||'|x8-action-command|'||auth.uid()::text||'|'||p_key,0));
 select * into r from public.e10_action_draft_commands where organization_id=p_org and actor_id=auth.uid()and idempotency_key=p_key;
 if found then if r.command_type<>p_type or p_draft is not null and r.draft_id<>p_draft or r.request_fingerprint<>p_fp then raise exception using errcode='22023',message='action_idempotency_key_mismatch';end if;return r.result||jsonb_build_object('replay',true);end if;
 return null;
end $$;

create function e10.x8b_lock_references(p_org uuid,p_operation text,p_values jsonb)returns void
language plpgsql security definer set search_path=public as $$
declare x uuid;begin
 if p_operation='purchase_order.create'then
  perform 1 from public.e10_suppliers where organization_id=p_org and id=(p_values->>'supplier_id')::uuid for update;
  perform 1 from public.e10_locations where organization_id=p_org and id=(p_values->>'destination_location_id')::uuid for update;
  for x in select distinct(value->>'configuration_version_id')::uuid from jsonb_array_elements(p_values->'lines')order by 1 loop perform 1 from public.e10_product_configuration_versions where organization_id=p_org and id=x for update;end loop;
 else
  if p_values->>'customer_id'is not null then perform 1 from public.e10_customers where organization_id=p_org and id=(p_values->>'customer_id')::uuid for update;end if;
  for x in select distinct(value->>'activity_observation_id')::uuid from jsonb_array_elements(p_values->'lines')where value->>'activity_observation_id'is not null order by 1 loop perform 1 from public.e10_customer_activity_observations where organization_id=p_org and id=x for update;end loop;
  for x in select distinct(value->>'location_id')::uuid from jsonb_array_elements(p_values->'lines')where value->>'location_id'is not null order by 1 loop perform 1 from public.e10_locations where organization_id=p_org and id=x for update;end loop;
  for x in select distinct(value->>'product_master_id')::uuid from jsonb_array_elements(p_values->'lines')where value->>'product_master_id'is not null order by 1 loop perform 1 from public.e10_product_masters where organization_id=p_org and id=x for update;end loop;
  for x in select distinct(value->>'configuration_version_id')::uuid from jsonb_array_elements(p_values->'lines')where value->>'configuration_version_id'is not null order by 1 loop perform 1 from public.e10_product_configuration_versions where organization_id=p_org and id=x for update;end loop;
  for x in select distinct(value->>'unique_item_id')::uuid from jsonb_array_elements(p_values->'lines')where value->>'unique_item_id'is not null order by 1 loop perform 1 from public.e10_unique_items where organization_id=p_org and id=x for update;end loop;
  for x in select distinct(value->>'break_session_id')::uuid from jsonb_array_elements(p_values->'lines')where value->>'break_session_id'is not null order by 1 loop perform 1 from public.e10_break_sessions where organization_id=p_org and id=x for update;end loop;
  for x in select distinct(value->>'break_slot_id')::uuid from jsonb_array_elements(p_values->'lines')where value->>'break_slot_id'is not null order by 1 loop perform 1 from public.e10_break_slots where organization_id=p_org and id=x for update;end loop;
 end if;
end $$;

create function public.e10_org_create_action_draft(p_org uuid,p_operation text,p_values jsonb,p_field_provenance jsonb,p_source_references jsonb,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare actor uuid:=auth.uid();d uuid:=gen_random_uuid();snap jsonb;fp text;old jsonb;result jsonb;begin
 if actor is null or not exists(select 1 from public.e10_organizations where id=p_org and status='active')or not e10.is_org_member(p_org)or not e10.has_org_cap(p_org,e10.x8b_capability(p_operation,'prepare'))then raise exception using errcode='42501',message='action_prepare_denied';end if;
 fp:=encode(extensions.digest(convert_to(jsonb_build_object('v','x8-action-create-v1','operation',p_operation,'values',p_values,'provenance',p_field_provenance,'sources',p_source_references)::text,'UTF8'),'sha256'),'hex');
 old:=e10.x8b_command(p_org,p_idempotency_key,'create',null,fp);
 if auth.uid()is distinct from actor or not exists(select 1 from public.e10_organizations where id=p_org and status='active')or not e10.is_org_member(p_org)or not e10.has_org_cap(p_org,e10.x8b_capability(p_operation,'prepare'))then raise exception using errcode='42501',message='action_prepare_denied';end if;
 if old is not null then return old;end if;
 snap:=e10.x8b_proposal_snapshot(p_org,p_operation,p_values,p_field_provenance,p_source_references);
 insert into public.e10_action_drafts(id,organization_id,created_by,operation)values(d,p_org,actor,p_operation);
 insert into public.e10_action_draft_revisions values(p_org,d,1,p_operation,snap->'values',array(select jsonb_array_elements_text(snap->'missing_fields')),p_field_provenance,p_source_references,snap->>'reference_fingerprint',fp,actor,statement_timestamp());
 result:=jsonb_build_object('ok',true,'replay',false,'draft_id',d,'revision',1,'status','draft','missing_fields',snap->'missing_fields');
 insert into public.e10_action_draft_commands values(p_org,actor,p_idempotency_key,'create',d,fp,null,result,statement_timestamp());return result;
end $$;

create function public.e10_org_amend_action_draft(p_org uuid,p_draft_id uuid,p_expected_revision integer,p_values jsonb,p_field_provenance jsonb,p_source_references jsonb,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare d record;snap jsonb;fp text;old jsonb;result jsonb;nextrev integer;begin
 if p_expected_revision is null or p_expected_revision<=0 then raise exception using errcode='22023',message='action_revision_invalid';end if;
 if not e10.x8b_authorized(p_org,p_draft_id,'amend')then raise exception using errcode='42501',message='action_amend_denied';end if;
 fp:=encode(extensions.digest(convert_to(jsonb_build_object('v','x8-action-amend-v1','draft',p_draft_id,'expected',p_expected_revision,'values',p_values,'provenance',p_field_provenance,'sources',p_source_references)::text,'UTF8'),'sha256'),'hex');old:=e10.x8b_command(p_org,p_idempotency_key,'amend',p_draft_id,fp);if old is not null then if not e10.x8b_authorized(p_org,p_draft_id,'amend')then raise exception using errcode='42501',message='action_amend_denied';end if;return old;end if;
 select * into d from public.e10_action_drafts where organization_id=p_org and id=p_draft_id for update;if not e10.x8b_authorized(p_org,p_draft_id,'amend')then raise exception using errcode='42501',message='action_amend_denied';end if;if not found or d.status not in('draft','approved')or d.current_revision<>p_expected_revision then raise exception using errcode='40001',message='action_revision_or_state_conflict';end if;
 snap:=e10.x8b_proposal_snapshot(p_org,d.operation,p_values,p_field_provenance,p_source_references);nextrev:=p_expected_revision+1;
 insert into public.e10_action_draft_revisions values(p_org,p_draft_id,nextrev,d.operation,snap->'values',array(select jsonb_array_elements_text(snap->'missing_fields')),p_field_provenance,p_source_references,snap->>'reference_fingerprint',fp,auth.uid(),statement_timestamp());
 update public.e10_action_drafts set current_revision=nextrev,status='draft',approved_revision=null,updated_at=statement_timestamp()where organization_id=p_org and id=p_draft_id;
 result:=jsonb_build_object('ok',true,'replay',false,'draft_id',p_draft_id,'revision',nextrev,'status','draft','missing_fields',snap->'missing_fields');insert into public.e10_action_draft_commands values(p_org,auth.uid(),p_idempotency_key,'amend',p_draft_id,fp,null,result,statement_timestamp());return result;
end $$;

create function public.e10_org_preview_action_draft(p_org uuid,p_draft_id uuid,p_revision integer)
returns jsonb language plpgsql security definer set search_path=public as $$
declare d record;r record;begin if not e10.x8b_authorized(p_org,p_draft_id,'preview')then raise exception using errcode='42501',message='action_preview_denied';end if;select * into d from public.e10_action_drafts where organization_id=p_org and id=p_draft_id;select * into r from public.e10_action_draft_revisions where organization_id=p_org and draft_id=p_draft_id and revision=p_revision;if not found then raise exception using errcode='22023',message='action_revision_not_found';end if;return jsonb_build_object('draft_id',d.id,'operation',d.operation,'status',d.status,'current_revision',d.current_revision,'revision',r.revision,'approved_revision',d.approved_revision,'values',r.proposed_values,'missing_fields',r.missing_fields,'field_provenance',r.field_provenance,'source_references',r.source_references,'reference_fingerprint',r.reference_fingerprint);end $$;

create function public.e10_org_approve_action_draft(p_org uuid,p_draft_id uuid,p_expected_revision integer,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare d record;r record;snap jsonb;fp text;old jsonb;result jsonb;begin if not e10.x8b_authorized(p_org,p_draft_id,'approve')then raise exception using errcode='42501',message='action_approve_denied';end if;fp:=encode(extensions.digest(convert_to(jsonb_build_object('v','x8-action-approve-v1','draft',p_draft_id,'revision',p_expected_revision)::text,'UTF8'),'sha256'),'hex');old:=e10.x8b_command(p_org,p_idempotency_key,'approve',p_draft_id,fp);if old is not null then if not e10.x8b_authorized(p_org,p_draft_id,'approve')then raise exception using errcode='42501',message='action_approve_denied';end if;return old;end if;select * into d from public.e10_action_drafts where organization_id=p_org and id=p_draft_id for update;if not found or d.status<>'draft'or d.current_revision<>p_expected_revision then raise exception using errcode='40001',message='action_revision_or_state_conflict';end if;if not e10.x8b_authorized(p_org,p_draft_id,'approve')then raise exception using errcode='42501',message='action_approve_denied';end if;select * into r from public.e10_action_draft_revisions where organization_id=p_org and draft_id=p_draft_id and revision=p_expected_revision;if cardinality(r.missing_fields)>0 then raise exception using errcode='22023',message='action_required_fields_missing';end if;snap:=e10.x8b_proposal_snapshot(p_org,d.operation,r.proposed_values,r.field_provenance,r.source_references);if snap->>'reference_fingerprint'<>r.reference_fingerprint or jsonb_array_length(snap->'missing_fields')>0 then raise exception using errcode='40001',message='action_references_stale';end if;insert into public.e10_action_draft_decisions(organization_id,draft_id,revision,decision_action,decided_by)values(p_org,p_draft_id,p_expected_revision,'approve',auth.uid());update public.e10_action_drafts set status='approved',approved_revision=p_expected_revision,updated_at=statement_timestamp()where organization_id=p_org and id=p_draft_id;result:=jsonb_build_object('ok',true,'replay',false,'draft_id',p_draft_id,'revision',p_expected_revision,'status','approved');insert into public.e10_action_draft_commands values(p_org,auth.uid(),p_idempotency_key,'approve',p_draft_id,fp,null,result,statement_timestamp());return result;end $$;

create function public.e10_org_cancel_action_draft(p_org uuid,p_draft_id uuid,p_expected_revision integer,p_reason text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare d record;fp text;old jsonb;result jsonb;begin if not e10.x8b_authorized(p_org,p_draft_id,'cancel')then raise exception using errcode='42501',message='action_cancel_denied';end if;if coalesce(btrim(p_reason),'')=''or length(p_reason)>2000 then raise exception using errcode='22023',message='action_cancel_reason_invalid';end if;fp:=encode(extensions.digest(convert_to(jsonb_build_object('v','x8-action-cancel-v1','draft',p_draft_id,'revision',p_expected_revision,'reason',btrim(p_reason))::text,'UTF8'),'sha256'),'hex');old:=e10.x8b_command(p_org,p_idempotency_key,'cancel',p_draft_id,fp);if old is not null then if not e10.x8b_authorized(p_org,p_draft_id,'cancel')then raise exception using errcode='42501',message='action_cancel_denied';end if;return old;end if;select * into d from public.e10_action_drafts where organization_id=p_org and id=p_draft_id for update;if not found or d.status not in('draft','approved')or d.current_revision<>p_expected_revision then raise exception using errcode='40001',message='action_revision_or_state_conflict';end if;if not e10.x8b_authorized(p_org,p_draft_id,'cancel')then raise exception using errcode='42501',message='action_cancel_denied';end if;insert into public.e10_action_draft_decisions(organization_id,draft_id,revision,decision_action,reason,decided_by)values(p_org,p_draft_id,p_expected_revision,'cancel',btrim(p_reason),auth.uid());update public.e10_action_drafts set status='cancelled',approved_revision=null,cancelled_at=statement_timestamp(),updated_at=statement_timestamp()where organization_id=p_org and id=p_draft_id;result:=jsonb_build_object('ok',true,'replay',false,'draft_id',p_draft_id,'revision',p_expected_revision,'status','cancelled');insert into public.e10_action_draft_commands values(p_org,auth.uid(),p_idempotency_key,'cancel',p_draft_id,fp,null,result,statement_timestamp());return result;end $$;

create function public.e10_org_commit_action_draft(p_org uuid,p_draft_id uuid,p_expected_revision integer,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare d record;r record;snap jsonb;fp text;old jsonb;result jsonb;downkey text;begin if not e10.x8b_authorized(p_org,p_draft_id,'commit')then raise exception using errcode='42501',message='action_commit_denied';end if;fp:=encode(extensions.digest(convert_to(jsonb_build_object('v','x8-action-commit-v1','draft',p_draft_id,'revision',p_expected_revision)::text,'UTF8'),'sha256'),'hex');old:=e10.x8b_command(p_org,p_idempotency_key,'commit',p_draft_id,fp);if old is not null then if not e10.x8b_authorized(p_org,p_draft_id,'commit')then raise exception using errcode='42501',message='action_commit_denied';end if;return old;end if;select * into d from public.e10_action_drafts where organization_id=p_org and id=p_draft_id for update;if not found or d.status<>'approved'or d.current_revision<>p_expected_revision or d.approved_revision<>p_expected_revision then raise exception using errcode='40001',message='action_revision_or_state_conflict';end if;if not e10.x8b_authorized(p_org,p_draft_id,'commit')then raise exception using errcode='42501',message='action_commit_denied';end if;select * into r from public.e10_action_draft_revisions where organization_id=p_org and draft_id=p_draft_id and revision=p_expected_revision;downkey:='x8:'||d.operation||':'||d.id||':'||p_expected_revision||':'||encode(extensions.digest(convert_to(p_idempotency_key,'UTF8'),'sha256'),'hex');perform pg_advisory_xact_lock(hashtextextended(p_org::text||case d.operation when'purchase_order.create'then'|purchase-order-command|'else'|customer-commercial|'end||downkey,0));if not e10.x8b_authorized(p_org,p_draft_id,'commit')then raise exception using errcode='42501',message='action_commit_denied';end if;perform e10.x8b_lock_references(p_org,d.operation,r.proposed_values);if not e10.x8b_authorized(p_org,p_draft_id,'commit')then raise exception using errcode='42501',message='action_commit_denied';end if;snap:=e10.x8b_proposal_snapshot(p_org,d.operation,r.proposed_values,r.field_provenance,r.source_references);if snap->>'reference_fingerprint'<>r.reference_fingerprint or jsonb_array_length(snap->'missing_fields')>0 then raise exception using errcode='40001',message='action_references_stale';end if;
 if d.operation='purchase_order.create'then result:=public.e10_org_create_purchase_order(p_org,(r.proposed_values->>'supplier_id')::uuid,(r.proposed_values->>'destination_location_id')::uuid,r.proposed_values->>'order_number',r.proposed_values->>'currency',(r.proposed_values->>'expected_at')::timestamptz,r.proposed_values->'lines',downkey);else result:=public.e10_org_create_customer_transaction_draft(p_org,(r.proposed_values->>'customer_id')::uuid,r.proposed_values->>'currency',(r.proposed_values->>'occurred_at')::timestamptz,r.proposed_values->>'precision',r.proposed_values->>'note',r.proposed_values->'lines',downkey);end if;
 update public.e10_action_drafts set status='committed',approved_revision=null,ordinary_result=result,committed_at=statement_timestamp(),updated_at=statement_timestamp()where organization_id=p_org and id=p_draft_id;result:=jsonb_build_object('ok',true,'replay',false,'draft_id',p_draft_id,'revision',p_expected_revision,'status','committed','ordinary_result',result);insert into public.e10_action_draft_commands values(p_org,auth.uid(),p_idempotency_key,'commit',p_draft_id,fp,downkey,result,statement_timestamp());return result;end $$;

revoke all on function e10.x8b_authorized(uuid,uuid,text),e10.x8b_command(uuid,text,text,uuid,text),e10.x8b_lock_references(uuid,text,jsonb)from public,anon,authenticated;
grant execute on function e10.x8b_authorized(uuid,uuid,text),e10.x8b_command(uuid,text,text,uuid,text),e10.x8b_lock_references(uuid,text,jsonb)to service_role;
revoke all on function public.e10_org_create_action_draft(uuid,text,jsonb,jsonb,jsonb,text),public.e10_org_amend_action_draft(uuid,uuid,integer,jsonb,jsonb,jsonb,text),public.e10_org_preview_action_draft(uuid,uuid,integer),public.e10_org_approve_action_draft(uuid,uuid,integer,text),public.e10_org_cancel_action_draft(uuid,uuid,integer,text,text),public.e10_org_commit_action_draft(uuid,uuid,integer,text)from public,anon;
grant execute on function public.e10_org_create_action_draft(uuid,text,jsonb,jsonb,jsonb,text),public.e10_org_amend_action_draft(uuid,uuid,integer,jsonb,jsonb,jsonb,text),public.e10_org_preview_action_draft(uuid,uuid,integer),public.e10_org_approve_action_draft(uuid,uuid,integer,text),public.e10_org_cancel_action_draft(uuid,uuid,integer,text,text),public.e10_org_commit_action_draft(uuid,uuid,integer,text)to authenticated,service_role;
